'use strict';
(function(){
const KEY='manabiSprint.tsukanshi.v140',OLD_KEY='manabiSprint.tsukanshi.v01',SCHEMA=2,PRODUCT_ID='jp.allsunday1122.tsukanshi.premium';
const app=document.getElementById('app');
const ALL=(window.TSUKANSHI_QUESTIONS||[]).filter(q=>q.auditStatus==='approved');
const BY_ID=Object.fromEntries(ALL.map(q=>[q.id,q]));
const SUBJECTS=['通関業法','関税法等','通関実務'];
const ROUNDS=[{key:'59',label:'第59回',year:'2025'},{key:'58',label:'第58回',year:'2024'},{key:'57',label:'第57回',year:'2023'}];
let VIEW='home',SESSION=null,entitlement={premium:false,displayPrice:'¥980',status:'unknown'};
const todayKey=()=>{const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
function fresh(){return{schemaVersion:SCHEMA,contentVersion:window.TSUKANSHI_CONTENT_VERSION||'tsukanshi-v21',lawBaselineDate:window.TSUKANSHI_LAW_BASELINE||'2026-07-01',weak:{},seenIds:{},sessionCompletions:{},stats:{totalAnswered:0,totalCorrect:0,history:[]},answerLog:[],settings:{fontSize:'normal',dailyGoal:8,examDate:''},inProgress:null,entitlementCache:'unknown'}}
function load(){let s=null;try{s=JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){}if(!s){try{s=JSON.parse(localStorage.getItem(OLD_KEY)||'null')}catch(e){}}if(!s||typeof s!=='object')s=fresh();const f=fresh();s={...f,...s,settings:{...f.settings,...(s.settings||{})},stats:{...f.stats,...(s.stats||{})}};s.schemaVersion=SCHEMA;s.contentVersion=f.contentVersion;s.lawBaselineDate=f.lawBaselineDate;s.answerLog=Array.isArray(s.answerLog)?s.answerLog.slice(-3000):[];s.stats.history=Array.isArray(s.stats.history)?s.stats.history.slice(0,80):[];if(![4,8,16].includes(Number(s.settings.dailyGoal)))s.settings.dailyGoal=8;if(!['normal','large','xlarge'].includes(s.settings.fontSize))s.settings.fontSize='normal';if(!s.weak||typeof s.weak!=='object')s.weak={};if(!s.seenIds||typeof s.seenIds!=='object')s.seenIds={};if(!s.sessionCompletions||typeof s.sessionCompletions!=='object')s.sessionCompletions={};if(s.inProgress&&(!Array.isArray(s.inProgress.ids)||s.inProgress.ids.some(id=>!BY_ID[id])))s.inProgress=null;return s}
let STATE=load();
function save(){try{localStorage.setItem(KEY,JSON.stringify(STATE))}catch(e){}native('state',{state:STATE})}
function esc(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function norm(v){return String(v??'').trim().replace(/[\s　,，￥¥]/g,'').toLowerCase()}
function shuffle(a){a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function native(handler,payload){try{const h=window.webkit&&window.webkit.messageHandlers&&window.webkit.messageHandlers[handler];if(h)h.postMessage(payload||{})}catch(e){}}
function premium(){return entitlement.premium||STATE.entitlementCache==='premium'}
window.__nativeStoreKitUpdate=function(x){if(!x||typeof x!=='object')return;entitlement={premium:!!x.premium,displayPrice:x.displayPrice||entitlement.displayPrice,status:x.status||'known'};STATE.entitlementCache=entitlement.premium?'premium':'free';save();render()};
function requestEntitlement(){native('storeKit',{action:'status',productId:PRODUCT_ID})}
function applyFont(){document.documentElement.dataset.font=STATE.settings.fontSize}
function icon(name){const paths={home:'M3 10.5 12 3l9 7.5V21h-6v-6H9v6H3z',mock:'M5 3h14v18H5z M8 7h8 M8 11h8 M8 15h5',history:'M4 19V9h4v10H4zm6 0V5h4v14h-4zm6 0v-7h4v7h-4z',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8zm8.5 4a6.7 6.7 0 0 0-.1-1l2-1.6-2-3.4-2.5 1a8 8 0 0 0-1.8-1L15.7 3h-4l-.4 3a8 8 0 0 0-1.8 1L7 6 5 9.4 7 11a7 7 0 0 0 0 2l-2 1.6L7 18l2.5-1a8 8 0 0 0 1.8 1l.4 3h4l.4-3a8 8 0 0 0 1.8-1l2.5 1 2-3.4-2-1.6c.1-.3.1-.7.1-1z',bolt:'M13 2 4 14h7l-1 8 9-12h-7z',repeat:'M17 1l4 4-4 4V6H7a4 4 0 0 0-4 4H1a6 6 0 0 1 6-6h10V1z M7 23l-4-4 4-4v3h10a4 4 0 0 0 4-4h2a6 6 0 0 1-6 6H7v3z',book:'M4 4h7a3 3 0 0 1 3 3v13a3 3 0 0 0-3-3H4z M20 4h-5a3 3 0 0 0-3 3v13a3 3 0 0 1 3-3h5z',arrow:'M5 12h14 M13 6l6 6-6 6'};return`<svg class="svg-ic" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.arrow}"/></svg>`}
function tabbar(active){return`<nav class="nav" aria-label="メインナビゲーション">${[['home','ホーム'],['mock','模試'],['history','記録'],['settings','設定']].map(([k,l])=>`<button data-tab="${k}" class="${active===k?'active':''}">${icon(k)}<span>${l}</span></button>`).join('')}</nav>`}
function bindTabs(){app.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>go(b.dataset.tab))}
function go(v){VIEW=v;render();scrollTo(0,0)}
function subjectQuestions(s){return ALL.filter(q=>q.subject===s&&q.answerType!=='declaration')}
function declarationQuestions(){return ALL.filter(q=>q.answerType==='declaration')}
function numericQuestions(){return ALL.filter(q=>q.answerType==='numeric')}
function weakList(){return ALL.filter(q=>STATE.weak[q.id]&&Number(STATE.weak[q.id].streak||0)<3)}
function completion(k){return Number(STATE.sessionCompletions[k]||0)}
function todayAnswered(){const k=todayKey();return STATE.answerLog.filter(x=>String(x.day||'')===k).length}
function todayCorrect(){const k=todayKey();return STATE.answerLog.filter(x=>String(x.day||'')===k&&x.correct).length}
function seenCount(){return Object.keys(STATE.seenIds).filter(id=>STATE.seenIds[id]).length}
function examInfo(){const s=STATE.settings.examDate;if(!s)return null;const end=new Date(`${s}T00:00:00`),now=new Date();const days=Math.ceil((end-new Date(now.getFullYear(),now.getMonth(),now.getDate()))/86400000);if(!Number.isFinite(days))return null;const unseen=Math.max(0,Math.min(480,480-seenCount()));return{days,pace:days>0?Math.max(1,Math.ceil(unseen/days)):0}}
function todayQuestions(){const n=Number(STATE.settings.dailyGoal)||8;const unseen=shuffle(ALL.filter(q=>q.answerType!=='declaration'&&!STATE.seenIds[q.id]));const weak=shuffle(weakList().filter(q=>q.answerType!=='declaration'));const seen=shuffle(ALL.filter(q=>q.answerType!=='declaration'&&STATE.seenIds[q.id]&&!STATE.weak[q.id]));const out=[],ids=new Set();for(const pool of [unseen,weak,seen])for(const q of pool){if(out.length>=n)break;if(!ids.has(q.id)){ids.add(q.id);out.push(q)}}return out}
function roundQuestions(round,subject){const base=subjectQuestions(subject),off=Math.max(0,ROUNDS.findIndex(r=>r.key===round));return base.slice(off).concat(base.slice(0,off)).slice(0,Math.min(40,base.length))}
function render(){applyFont();if(VIEW==='home')renderHome();else if(VIEW==='mock')renderMock();else if(VIEW==='history')renderHistory();else if(VIEW==='settings')renderSettings();else if(VIEW==='quiz')renderQuiz();else if(VIEW==='result')renderResult();else if(VIEW==='paywall')renderPaywall()}
function renderHome(){const done=todayAnswered(),goal=Number(STATE.settings.dailyGoal)||8,pct=Math.min(100,Math.round(done/goal*100)),weak=weakList().length,exam=examInfo(),ip=STATE.inProgress,total=STATE.stats.totalAnswered||0,acc=total?Math.round((STATE.stats.totalCorrect||0)/total*100):0;let h=`<div class="paper-grid"></div><header class="mast"><div class="eyebrow">学びスプリント</div><h1 class="title">通関士</h1><p>今日も1問、力に変える。</p></header>`;if(exam)h+=`<section class="countdown"><div><span>試験まで</span><b class="dnum">${exam.days>=0?exam.days:'—'}</b><span>日</span></div><p>${exam.days>0?`未学習を進める目安：1日 ${exam.pace}問`:'試験日を迎えました'}</p></section>`;h+=`<section class="today-card"><div class="today-ring" style="--p:${pct*3.6}deg"><div><b>${done}</b><span>/ ${goal}</span></div></div><div class="today-copy"><span class="sig">今日の学習</span><strong>${done>=goal?'今日の目標を達成':'あと'+Math.max(0,goal-done)+'問'}</strong><small>正解 ${todayCorrect()}問・完答 ${completion('today')}回</small></div></section>`;if(ip)h+=`<button class="resume" data-resume><span>${icon('repeat')}</span><span><small>続きから再開</small><b>${esc(ip.title||'学習中')}</b><em>${Math.min((ip.index||0)+1,(ip.ids||[]).length)} / ${(ip.ids||[]).length}</em></span>${icon('arrow')}</button>`;h+=`<main class="home-main"><button class="primary-cta" data-start-today><span class="cta-ic">${icon('bolt')}</span><span><small>今日のスプリント</small><b>${goal}問を解く</b></span>${icon('arrow')}</button><button class="weak-cta" data-weak><span>${icon('repeat')}</span><span><small>苦手をつぶす</small><b>${weak?weak+'問あります':'現在の苦手はありません'}</b></span><span class="weak-count">${weak}</span></button><button class="mock-link" data-open-mock><span>${icon('mock')}</span><span><small>模擬試験</small><b>直近3回・科目別</b></span>${icon('arrow')}</button><section class="block"><div class="section-head"><h2>分野から解く</h2><span>完答回数</span></div><div class="field-list">${SUBJECTS.map(s=>`<button data-subject="${s}"><span><b>${s}</b><small>${subjectQuestions(s).length}問</small></span><em>${completion('subject:'+s)}回</em>${icon('arrow')}</button>`).join('')}</div></section><section class="block"><div class="section-head"><h2>これまで</h2></div><div class="three-stats"><div><b>${total}</b><span>回答</span></div><div><b>${acc}%</b><span>正答率</span></div><div><b>${weak}</b><span>苦手</span></div></div></section></main>${tabbar('home')}`;app.innerHTML=h;app.querySelector('[data-start-today]').onclick=()=>startSession('today',todayQuestions(),'今日のスプリント');app.querySelector('[data-open-mock]').onclick=()=>go('mock');app.querySelector('[data-weak]').onclick=()=>{if(!premium())return openPaywall('苦手復習');const q=weakList();if(!q.length)return;startSession('weak',shuffle(q),'苦手をつぶす')};app.querySelectorAll('[data-subject]').forEach(b=>b.onclick=()=>startSession('subject:'+b.dataset.subject,shuffle(subjectQuestions(b.dataset.subject)).slice(0,Number(STATE.settings.dailyGoal)||8),b.dataset.subject));const r=app.querySelector('[data-resume]');if(r)r.onclick=resume;bindTabs()}
function renderMock(){let h=`<header class="subhead"><div><span>学びスプリント</span><h1>模擬試験</h1></div><p>本試験の3科目を、試験回・科目別に反復します。</p></header><main class="page-pad"><div class="notice">公式過去問本文は権利監査完了後に切り替えます。現在は同形式の監査済み独自問題です。</div><section class="mock-round"><div class="mocktitle"><b>通関実務トレーニング</b><span>短時間演習</span></div><button class="mock-card" data-practice="numeric"><span><b>計算演習</b><small>${numericQuestions().length}問・課税価格／関税額</small></span>${icon('arrow')}</button><button class="mock-card" data-practice="declaration"><span><b>申告書演習</b><small>${declarationQuestions().length}セット・資料読取／項目入力</small></span>${icon('arrow')}</button></section>${ROUNDS.map(r=>`<section class="mock-round"><div class="mocktitle"><b>${r.label}</b><span>${r.year}</span></div>${SUBJECTS.map(s=>`<button class="mock-card" data-round="${r.key}" data-ms="${s}"><span><b>${s}</b><small>完答 ${completion(`exam:${r.key}:${s}`)}回</small></span>${icon('arrow')}</button>`).join('')}</section>`).join('')}</main>${tabbar('mock')}`;app.innerHTML=h;app.querySelectorAll('[data-practice]').forEach(b=>b.onclick=()=>{if(b.dataset.practice==='declaration'&&!premium())return openPaywall('申告書演習');const all=b.dataset.practice==='numeric'?numericQuestions():declarationQuestions(),qs=b.dataset.practice==='numeric'&&!premium()?all.slice(0,12):all;startSession('practice:'+b.dataset.practice,shuffle(qs),b.dataset.practice==='numeric'?'計算演習':'申告書演習')});app.querySelectorAll('[data-round]').forEach(b=>b.onclick=()=>{if(!premium())return openPaywall('模擬試験');startSession(`exam:${b.dataset.round}:${b.dataset.ms}`,roundQuestions(b.dataset.round,b.dataset.ms),`第${b.dataset.round}回｜${b.dataset.ms}`)});bindTabs()}
function renderHistory(){const total=STATE.stats.totalAnswered||0,correct=STATE.stats.totalCorrect||0,acc=total?Math.round(correct/total*100):0,master=Math.min(100,Math.round(seenCount()/480*100));const days=[];for(let i=34;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const k=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;const n=STATE.answerLog.filter(x=>x.day===k).length;days.push({k,n})}let h=`<header class="subhead"><div><span>学びスプリント</span><h1>学習記録</h1></div><p>積み上げと苦手を、ひと目で確認します。</p></header><main class="page-pad"><section class="record-top"><div class="donut" style="--p:${master*3.6}deg"><div><b>${master}%</b><span>達成度</span></div></div><div class="record-summary"><div><b>${total}</b><span>総回答</span></div><div><b>${acc}%</b><span>正答率</span></div><div><b>${weakList().length}</b><span>苦手</span></div></div></section><section class="record-card"><h2>分野別の進み具合</h2>${SUBJECTS.map(s=>{const qs=subjectQuestions(s),seen=qs.filter(q=>STATE.seenIds[q.id]).length,p=qs.length?Math.round(seen/qs.length*100):0;return`<div class="bar-row"><div><b>${s}</b><span>${seen}/${qs.length}</span></div><div class="bar"><i style="width:${p}%"></i></div></div>`}).join('')}</section><section class="record-card"><h2>5週間の学習</h2><div class="heatmap">${days.map(d=>`<i class="lv${d.n===0?0:d.n<4?1:d.n<8?2:d.n<16?3:4}" title="${d.k}: ${d.n}問"></i>`).join('')}</div><div class="heat-legend"><span>少ない</span><i class="lv1"></i><i class="lv2"></i><i class="lv3"></i><i class="lv4"></i><span>多い</span></div></section><section class="record-card"><h2>苦手一覧</h2>${weakList().slice(0,12).map(q=>`<button class="weak-row" data-one="${q.id}"><span><b>${esc(q.topic)}</b><small>${esc(q.subject)}・連続正解 ${STATE.weak[q.id].streak||0}/3</small></span>${icon('arrow')}</button>`).join('')||'<p class="empty">現在の苦手はありません。</p>'}</section></main>${tabbar('history')}`;app.innerHTML=h;app.querySelectorAll('[data-one]').forEach(b=>b.onclick=()=>{if(!premium())return openPaywall('苦手復習');startSession('weak-one',[BY_ID[b.dataset.one]],'苦手をつぶす')});bindTabs()}
function renderSettings(){let h=`<header class="subhead"><div><span>学びスプリント</span><h1>設定</h1></div><p>学習ペースと表示を調整します。</p></header><main class="page-pad"><section class="setting-card"><label>1日の目標</label><div class="seg">${[4,8,16].map(n=>`<button data-goal="${n}" class="${STATE.settings.dailyGoal===n?'active':''}">${n}問</button>`).join('')}</div></section><section class="setting-card"><label>文字サイズ</label><div class="seg">${[['normal','標準'],['large','大'],['xlarge','特大']].map(([k,l])=>`<button data-font="${k}" class="${STATE.settings.fontSize===k?'active':''}">${l}</button>`).join('')}</div></section><section class="setting-card"><label for="examDate">試験日</label><input id="examDate" class="date-input" type="date" value="${esc(STATE.settings.examDate||'')}"><small>登録するとホームに残日数と必要ペースを表示します。</small></section><section class="setting-card"><label>学習データ</label><div class="stack"><button class="sub-btn" data-export>JSONを書き出す</button><label class="sub-btn file-btn">JSONを読み込む<input type="file" accept="application/json" data-import></label></div></section><section class="setting-card"><label>教材情報</label><p>法令基準日：${esc(STATE.lawBaselineDate)}<br>監査済み問題のみ表示：${ALL.length}件<br>通常学習480問＋申告書12セット</p></section><section class="setting-card"><label>プレミアム</label><p>${premium()?'購入済み':'買い切りで模試・苦手復習・申告書演習を解放'}</p><button class="sub-btn" data-buy>${premium()?'購入状態を確認':entitlement.displayPrice+'で解放'}</button><button class="text-btn" data-restore>購入を復元</button></section><section class="setting-card danger"><button data-reset>学習データをリセット</button></section></main>${tabbar('settings')}`;app.innerHTML=h;app.querySelectorAll('[data-goal]').forEach(b=>b.onclick=()=>{STATE.settings.dailyGoal=Number(b.dataset.goal);save();renderSettings()});app.querySelectorAll('[data-font]').forEach(b=>b.onclick=()=>{STATE.settings.fontSize=b.dataset.font;save();renderSettings()});app.querySelector('#examDate').onchange=e=>{STATE.settings.examDate=e.target.value;save()};app.querySelector('[data-export]').onclick=exportData;app.querySelector('[data-import]').onchange=importData;app.querySelector('[data-buy]').onclick=()=>native('storeKit',{action:premium()?'status':'purchase',productId:PRODUCT_ID});app.querySelector('[data-restore]').onclick=()=>native('storeKit',{action:'restore',productId:PRODUCT_ID});app.querySelector('[data-reset]').onclick=()=>{if(confirm('学習記録をすべて削除しますか？')){STATE=fresh();save();renderSettings()}};bindTabs()}
function exportData(){const blob=new Blob([JSON.stringify(STATE,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`tsukanshi-sprint-${todayKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importData(e){const f=e.target.files&&e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);localStorage.setItem(KEY,JSON.stringify(x));STATE=load();save();alert('学習データを読み込みました。');renderSettings()}catch(err){alert('JSONを読み込めませんでした。')}};r.readAsText(f)}
function startSession(key,questions,title){if(!questions.length)return;SESSION={key,title,questions,index:0,answers:[],answered:false,response:null,startedAt:Date.now(),draft:null,result:null};saveProgress();go('quiz')}
function saveProgress(){if(!SESSION)return;STATE.inProgress={key:SESSION.key,title:SESSION.title,ids:SESSION.questions.map(q=>q.id),index:SESSION.index,answers:SESSION.answers,answered:SESSION.answered,response:SESSION.response,result:SESSION.result,startedAt:SESSION.startedAt,draft:SESSION.draft};save()}
function resume(){const p=STATE.inProgress;if(!p)return;const qs=p.ids.map(id=>BY_ID[id]).filter(Boolean);if(!qs.length)return;SESSION={key:p.key,title:p.title,questions:qs,index:Math.min(p.index,qs.length-1),answers:Array.isArray(p.answers)?p.answers:[],answered:!!p.answered,response:p.response??null,result:p.result===true,startedAt:p.startedAt||Date.now(),draft:p.draft||null};go('quiz')}
function current(){return SESSION&&SESSION.questions[SESSION.index]}
function renderQuiz(){if(!SESSION)return go('home');const q=current(),pct=Math.round((SESSION.index/SESSION.questions.length)*100);let h=`<header class="quiz-head"><button data-quit>ホーム</button><div><small>${esc(q.subject)}・${esc(q.topic)}</small><b>${SESSION.index+1} / ${SESSION.questions.length}</b></div></header><main class="quiz-page"><div class="qprogress"><i style="width:${pct}%"></i></div><article class="question-card"><div class="qno">QUESTION ${String(SESSION.index+1).padStart(2,'0')}</div><div class="qtext">${esc(q.question)}</div>${SESSION.answered?`<div class="judge-mark ${SESSION.result?'ok':'ng'}">${SESSION.result?'○':'×'}</div>`:''}</article><section class="answers">${answerUI(q)}</section>${SESSION.answered?feedback(q):''}</main>`;app.innerHTML=h;bindQuiz(q);app.querySelector('[data-quit]').onclick=()=>{saveProgress();go('home')}}
function answerUI(q){if(q.answerType==='singleChoice')return q.choices.map((c,i)=>`<button class="choice ${SESSION.answered?(i===q.answer?'correct':SESSION.response===i?'wrong':''):''}" data-choice="${i}" ${SESSION.answered?'disabled':''}><span>${i+1}</span><b>${esc(c)}</b></button>`).join('')+(!SESSION.answered?'<button class="dontknow" data-unknown>わからない</button>':'');if(q.answerType==='multiChoice'){const a=Array.isArray(SESSION.response)?SESSION.response:[];return`<div class="hint">複数選択・${a.length}/${q.selectionCount||q.answers.length} 選択</div>${q.choices.map((c,i)=>`<button class="choice ${a.includes(i)?'selected':''} ${SESSION.answered?(q.answers.includes(i)?'correct':a.includes(i)?'wrong':''):''}" data-multi="${i}" ${SESSION.answered?'disabled':''}><span>${i+1}</span><b>${esc(c)}</b></button>`).join('')}${!SESSION.answered?'<button class="grade" data-grade>採点する</button><button class="dontknow" data-unknown>わからない</button>':''}`}if(q.answerType==='blankSelect'){const d=SESSION.response&&typeof SESSION.response==='object'&&!Array.isArray(SESSION.response)?SESSION.response:{};return q.blanks.map((b,bi)=>`<div class="blank"><label>${esc(b.label)}</label><div>${b.options.map(o=>`<button data-blank="${bi}" data-val="${esc(o)}" class="chip ${d[bi]===o?'selected':''} ${SESSION.answered?(o===b.answer?'correct':d[bi]===o?'wrong':''):''}" ${SESSION.answered?'disabled':''}>${esc(o)}</button>`).join('')}</div></div>`).join('')+(!SESSION.answered?'<button class="grade" data-grade>採点する</button><button class="dontknow" data-unknown>わからない</button>':'')}if(q.answerType==='numeric')return`<div class="numeric"><label>答え</label><div><input inputmode="decimal" data-num value="${esc(SESSION.response??'')}" ${SESSION.answered?'disabled':''}><span>${esc(q.unit||'')}</span></div></div>${!SESSION.answered?'<button class="grade" data-grade>採点する</button><button class="dontknow" data-unknown>わからない</button>':''}`;if(q.answerType==='declaration'){const d=SESSION.response&&typeof SESSION.response==='object'&&!Array.isArray(SESSION.response)?SESSION.response:{};return`<details class="source" open><summary>資料を確認</summary><pre>${esc(q.sourceText||'')}</pre></details>${(q.declarationFields||[]).map((f,i)=>`<div class="decl"><label>${i+1}. ${esc(f.label)}</label><input data-decl="${esc(f.key)}" value="${esc(d[f.key]||'')}" ${SESSION.answered?'disabled':''}></div>`).join('')}${!SESSION.answered?'<button class="grade" data-grade>まとめて採点</button><button class="dontknow" data-unknown>わからない</button>':''}`}return'<p class="empty">この回答形式は準備中です。</p>'}
function bindQuiz(q){if(SESSION.answered){const n=app.querySelector('[data-next]');if(n)n.onclick=next;return}app.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>commit(q,Number(b.dataset.choice)===q.answer,Number(b.dataset.choice),false));app.querySelectorAll('[data-multi]').forEach(b=>b.onclick=()=>{let a=Array.isArray(SESSION.response)?SESSION.response.slice():[];const n=Number(b.dataset.multi);a=a.includes(n)?a.filter(x=>x!==n):a.concat(n);SESSION.response=a;saveProgress();renderQuiz()});app.querySelectorAll('[data-blank]').forEach(b=>b.onclick=()=>{const d=SESSION.response&&typeof SESSION.response==='object'&&!Array.isArray(SESSION.response)?{...SESSION.response}:{};d[Number(b.dataset.blank)]=b.dataset.val;SESSION.response=d;saveProgress();renderQuiz()});const u=app.querySelector('[data-unknown]');if(u)u.onclick=()=>commit(q,false,null,true);const g=app.querySelector('[data-grade]');if(g)g.onclick=()=>{if(q.answerType==='multiChoice'){const a=Array.isArray(SESSION.response)?SESSION.response.slice().sort((x,y)=>x-y):[],c=q.answers.slice().sort((x,y)=>x-y);commit(q,JSON.stringify(a)===JSON.stringify(c),a,false)}else if(q.answerType==='blankSelect'){const d=SESSION.response||{},ok=q.blanks.every((b,i)=>d[i]===b.answer);commit(q,ok,d,false)}else if(q.answerType==='numeric'){const v=app.querySelector('[data-num]').value;SESSION.response=v;const n=Number(norm(v)),range=Number(q.acceptedRange||0);commit(q,Number.isFinite(n)&&Math.abs(n-Number(q.correctNumber))<=range,v,false)}else if(q.answerType==='declaration'){const d={};app.querySelectorAll('[data-decl]').forEach(i=>d[i.dataset.decl]=i.value);const ok=(q.declarationFields||[]).every(f=>[f.answer,...(f.aliases||[])].some(a=>norm(a)===norm(d[f.key])));commit(q,ok,d,false)}}}
function commit(q,correct,response,unknown){SESSION.answered=true;SESSION.response=response;SESSION.result=!!correct;SESSION.answers.push({id:q.id,correct:!!correct,unknown:!!unknown,type:q.answerType});STATE.stats.totalAnswered=(STATE.stats.totalAnswered||0)+1;if(correct)STATE.stats.totalCorrect=(STATE.stats.totalCorrect||0)+1;STATE.seenIds[q.id]=true;STATE.answerLog.push({day:todayKey(),ts:Date.now(),id:q.id,subject:q.subject,correct:!!correct});STATE.answerLog=STATE.answerLog.slice(-3000);if(!correct||unknown){const w=STATE.weak[q.id]||{streak:0,wrongCount:0};w.streak=0;w.wrongCount=(w.wrongCount||0)+1;w.lastAnsweredAt=new Date().toISOString();STATE.weak[q.id]=w}else if(STATE.weak[q.id]){STATE.weak[q.id].streak=(STATE.weak[q.id].streak||0)+1;STATE.weak[q.id].lastAnsweredAt=new Date().toISOString();if(STATE.weak[q.id].streak>=3)delete STATE.weak[q.id]}saveProgress();renderQuiz()}
function feedback(q){let breakdown='';if(q.answerType==='declaration'&&SESSION.response){breakdown=`<div class="breakdown">${q.declarationFields.map(f=>{const ok=[f.answer,...(f.aliases||[])].some(a=>norm(a)===norm(SESSION.response[f.key]));return`<div class="${ok?'ok':'ng'}"><span>${ok?'○':'×'} ${esc(f.label)}</span><b>${esc(f.answer)}</b></div>`}).join('')}</div>`}return`<section class="feedback"><div class="judge-text ${SESSION.result?'ok':'ng'}">${SESSION.result?'正解':'不正解'}</div><div class="memory"><span>ここだけ覚える</span><p>${esc(q.point||'')}</p></div>${breakdown}<details><summary>詳しい解説</summary><p>${esc(q.detail||'')}</p></details><button class="next" data-next>${SESSION.index+1>=SESSION.questions.length?'結果を見る':'次の問題へ'}${icon('arrow')}</button></section>`}
function next(){if(SESSION.index+1>=SESSION.questions.length)return finish();SESSION.index++;SESSION.answered=false;SESSION.response=null;SESSION.result=null;saveProgress();renderQuiz();scrollTo(0,0)}
function finish(){const answers=SESSION.answers||[],correct=answers.filter(x=>x.correct).length,key=SESSION.key;STATE.sessionCompletions[key]=(STATE.sessionCompletions[key]||0)+1;STATE.stats.history.unshift({title:SESSION.title,correct,total:answers.length,at:new Date().toISOString()});STATE.stats.history=STATE.stats.history.slice(0,80);STATE.inProgress=null;SESSION.summary={correct,total:answers.length,seconds:Math.round((Date.now()-SESSION.startedAt)/1000)};save();go('result')}
function renderResult(){if(!SESSION||!SESSION.summary)return go('home');const r=SESSION.summary,p=r.total?Math.round(r.correct/r.total*100):0;app.innerHTML=`<main class="result-page"><div class="result-seal">学びスプリント</div><h1 class="rmsg">${p===100?'よくできました。':p>=70?'着実に進んでいます。':'復習して定着させましょう。'}</h1><div class="score"><b>${r.correct}</b><span>/ ${r.total}</span></div><div class="result-metrics"><div><b>${p}%</b><span>正答率</span></div><div><b>${Math.floor(r.seconds/60)}:${String(r.seconds%60).padStart(2,'0')}</b><span>時間</span></div><div><b>${weakList().length}</b><span>苦手</span></div></div><button class="primary-cta" data-again><span><small>もう一度</small><b>${STATE.settings.dailyGoal}問進める</b></span>${icon('arrow')}</button><button class="weak-cta" data-result-weak><span>${icon('repeat')}</span><span><small>誤答を復習</small><b>苦手だけ解く</b></span><span class="weak-count">${weakList().length}</span></button><button class="text-home" data-home>ホームへ戻る</button></main>`;app.querySelector('[data-again]').onclick=()=>startSession('today',todayQuestions(),'今日のスプリント');app.querySelector('[data-result-weak]').onclick=()=>{if(!premium())return openPaywall('苦手復習');const w=weakList();if(!w.length)return go('home');startSession('weak',shuffle(w),'苦手をつぶす')};app.querySelector('[data-home]').onclick=()=>go('home')}
function openPaywall(reason){VIEW='paywall';SESSION&&saveProgress();renderPaywall(reason)}
function renderPaywall(reason='プレミアム'){app.innerHTML=`<main class="paywall"><div class="result-seal">学びスプリント</div><h1>${esc(reason)}</h1><p>無料範囲で操作感を確認したあと、買い切りで全教材を解放できます。</p><ul><li>480問すべて</li><li>苦手復習</li><li>直近3回の模試</li><li>申告書12セット</li></ul><div class="pay-price">${esc(entitlement.displayPrice)}</div><button class="purchase" data-purchase>プレミアムを解放</button><button class="text-btn" data-restore>購入を復元</button><button class="text-home" data-home>戻る</button></main>`;app.querySelector('[data-purchase]').onclick=()=>native('storeKit',{action:'purchase',productId:PRODUCT_ID});app.querySelector('[data-restore]').onclick=()=>native('storeKit',{action:'restore',productId:PRODUCT_ID});app.querySelector('[data-home]').onclick=()=>go('home')}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));requestEntitlement();render();
})();