'use strict';
const TSUKANSHI_CONTENT_VERSION='tsukanshi-2026-07-v01';
const TSUKANSHI_LAW_BASELINE='2026-07-01';
const TSUKANSHI_QUESTIONS=[
{id:'TB-001',subject:'通関業法',topic:'通関業者の役割',answerType:'singleChoice',question:'通関業者が行う業務について、最も適切な説明はどれか。',choices:['依頼を受けて税関官署に対する通関手続を代理・代行する業務を含む','輸入貨物の所有権を当然に取得する','関税率を独自に決定できる','税関長に代わって輸入許可を行う','すべての輸出入者に代わり納税義務者となる'],answer:0,point:'通関業は、他人の依頼を受けて通関手続等を行う業務です。',detail:'通関業者は行政庁ではなく、依頼者に代わって申告等の手続を行います。許可や税率決定そのものを行う権限はありません。',auditStatus:'approved',sourceType:'original',lawBaseline:'2026-07-01'},
{id:'TB-002',subject:'通関業法',topic:'通関士の設置',answerType:'singleChoice',question:'通関業者の営業所における通関士について、学習上の考え方として適切なものはどれか。',choices:['通関書類の審査など、通関士が担うべき業務がある','通関士は輸入者本人でなければならない','通関士は税関職員の兼職である','通関士は関税の納税義務者に限られる','通関士制度は通関実務と無関係である'],answer:0,point:'通関士は、通関業務の適正な遂行を支える専門資格者です。',detail:'通関書類の審査等、通関士が関与すべき業務を区別して理解することが重要です。',auditStatus:'approved',sourceType:'original',lawBaseline:'2026-07-01'},
{id:'TB-003',subject:'通関業法',topic:'信用失墜行為',answerType:'multiChoice',selectionCount:2,question:'通関業務の適正性を損なうおそれが高い行為として、該当するものを2つ選べ。',choices:['依頼者から預かった情報を正当な理由なく第三者へ漏らす','法令改正を確認して申告内容を見直す','虚偽の内容と知りながら申告書作成に協力する','依頼者へ必要資料の追加提出を求める','税関からの照会内容を依頼者へ確認する'],answers:[0,2],point:'秘密保持と適正な申告は、通関業務の信頼性の基本です。',detail:'法令確認や追加資料の依頼、事実確認は適正な手続のための行為です。一方、秘密漏えいと虚偽申告への協力は信頼を損ないます。',auditStatus:'approved',sourceType:'original',lawBaseline:'2026-07-01'},
{id:'TB-004',subject:'通関業法',topic:'記帳と保存',answerType:'singleChoice',question:'通関業務に関する記録の扱いとして適切なものはどれか。',choices:['法令上必要な記録は、定められた方法・期間に従って保存する','依頼者が希望すればすべて即日廃棄できる','電子データであれば記録管理は不要である','税関から求められても提示する必要はない','通関士個人の私物端末だけに保存すれば足りる'],answer:0,point:'通関業務は後から検証できるよう、記録管理が重要です。',detail:'保存対象、保存期間、提示義務等は法令・運用に従って管理します。個人端末のみの管理は情報管理上も不適切です。',auditStatus:'approved',sourceType:'original',lawBaseline:'2026-07-01'},
{id:'TB-005',subject:'通関業法',topic:'依頼者確認',answerType:'singleChoice',question:'通関業者が依頼を受けた際の対応として適切なものはどれか。',choices:['申告に必要な事実や資料を確認し、不明点を解消してから手続する','依頼者の説明は確認せずそのまま申告する','品名が不明でも任意の品目番号を使う','価格資料がなくても常に最低価格を採用する','法令上の禁止・規制を確認しない'],answer:0,point:'正しい申告の出発点は、事実と資料の確認です。',detail:'品名・価格・原産地・規制など、申告に必要な情報を確認してから処理します。',auditStatus:'approved',sourceType:'original',lawBaseline:'2026-07-01'},
{id:'KS-001',subject:'関税法等',topic:'輸入申告',answerType:'singleChoice',question:'輸入申告について、最も適切な説明はどれか。',choices:['輸入しようとする貨物について、必要事項を税関に申告し、審査等を経て許可を受ける手続である','輸入後に必ず任意で行う届出である','税関の審査を一切伴わない','輸出貨物にのみ必要な手続である','貨物の価格にかかわらず申告内容は同一でよい'],answer:0,point:'輸入申告は、輸入許可へつながる中心手続です。',detail:'品名、数量、価格、原産地、適用税率、他法令該当性等を正確に申告します。',auditStatus:'approved',sourceType:'original',lawBaseline:'2026-07-01'},
{id:'KS-002',subject:'関税法等',topic:'納税申告',answerType:'singleChoice',question:'申告納税方式の理解として適切なものはどれか。',choices:['納税義務者側の申告を基礎として税額が確定する仕組みである','税関が必ず事前に税額を一方的に決める方式だけをいう','関税には一切用いられない','納税義務者は税額計算に関与しない','輸出時にのみ用いられる'],answer:0,point:'申告納税方式では、自ら正しく計算・申告することが前提です。',detail:'申告内容に誤りがあれば修正手続や追徴等につながるため、課税価格と税率の理解が重要です。',auditStatus:'approved',sourceType:'original',lawBaseline:'2026-07-01'},
{id:'KS-003',subject:'関税法等',topic:'課税価格',answerType:'multiChoice',selectionCount:3,question:'輸入貨物の課税価格を検討する際、確認対象となり得るものを3つ選べ。',choices:['実際の取引価格','買手が負担する運賃等の加算要素','価格に含まれるべき調整要素','輸入者の社内売上目標','通関担当者の個人的な予想価格'],answers:[0,1,2],point:'課税価格は、実際の取引価格を基礎に必要な加算・調整を行います。',detail:'価格決定は客観的な取引資料と法令上の要素に基づきます。社内目標や担当者の予想は根拠になりません。',auditStatus:'approved',sourceType:'original',lawBaseline:'2026-07-01'},
{id:'KS-004',subject:'関税法等',topic:'原産地',answerType:'singleChoice',question:'原産地の確認が重要となる理由として最も適切なものはどれか。',choices:['適用税率や経済連携協定上の取扱い等に影響することがあるため','貨物の色だけを決めるため','輸送会社を自動的に指定するため','輸入者の法人番号を決めるため','すべての貨物の関税率を0％にするため'],answer:0,point:'原産地は、税率やEPA等の適用判断に直結します。',detail:'特恵税率・EPA税率の適用では、原産地規則と証明方法の確認が重要です。',auditStatus:'approved',sourceType:'original',lawBaseline:'2026-07-01'},
{id:'KS-005',subject:'関税法等',topic:'禁止・規制貨物',answerType:'singleChoice',question:'輸入貨物に他法令上の規制がある可能性がある場合の対応として適切なものはどれか。',choices:['必要な許可・承認・検査等の有無を確認してから申告する','関税を払えば他法令は確認不要である','規制の有無は輸送会社だけが判断する','税関申告後は一切訂正できないので確認しない','品名を曖昧にすれば規制確認は不要である'],answer:0,point:'関税法だけでなく、他法令による輸入規制も確認します。',detail:'貨物によっては各所管法令に基づく許可・承認・検査等が必要です。',auditStatus:'approved',sourceType:'original',lawBaseline:'2026-07-01'},
{id:'KS-006',subject:'関税法等',topic:'保税制度',answerType:'singleChoice',question:'保税制度の学習上の理解として適切なものはどれか。',choices:['外国貨物を一定の管理下で蔵置・取扱いする仕組みがある','外国貨物は到着直後からどこでも自由に処分できる','保税地域では税関の管理は及ばない','保税制度は輸出入手続と無関係である','保税地域に置けば永久に申告不要である'],answer:0,point:'外国貨物は、税関の管理の下で取り扱われます。',detail:'保税地域の種類や蔵置・取扱いの条件を整理して理解します。',auditStatus:'approved',sourceType:'original',lawBaseline:'2026-07-01'},
{id:'KS-007',subject:'関税法等',topic:'修正申告',answerType:'singleChoice',question:'申告後に税額が過少であったことが判明した場合の対応として、まず検討すべきものはどれか。',choices:['適切な修正手続','申告データの削除','輸送会社への責任転嫁','貨物名の変更','何もしない'],answer:0,point:'申告誤りは放置せず、法令に従った修正手続を検討します。',detail:'過少申告と過大申告では用いる手続が異なるため、原因と税額影響を確認します。',auditStatus:'approved',sourceType:'original',lawBaseline:'2026-07-01'},
{id:'JM-001',subject:'通関実務',topic:'関税額計算',answerType:'numeric',question:'課税価格が1,000,000円、関税率が5％で、他の調整を考えない場合の関税額を求めよ。',correctNumber:50000,unit:'円',acceptedRange:0,point:'関税額は、課税価格 × 関税率で計算します。',detail:'1,000,000円 × 5％ ＝ 50,000円。実際の申告では端数処理や適用税率、加算要素等も確認します。',auditStatus:'approved',sourceType:'original',lawBaseline:'2026-07-01'},
{id:'JM-002',subject:'通関実務',topic:'課税価格計算',answerType:'numeric',question:'取引価格800,000円に、課税価格へ加算すべき運賃50,000円と保険料10,000円があるものとする。単純化して課税価格を求めよ。',correctNumber:860000,unit:'円',acceptedRange:0,point:'加算要素を取引価格に足して課税価格を求めます。',detail:'800,000円 + 50,000円 + 10,000円 ＝ 860,000円。実務では加算・控除要素の法的要件を確認します。',auditStatus:'approved',sourceType:'original',lawBaseline:'2026-07-01'},
{id:'JM-003',subject:'通関実務',topic:'申告事項',answerType:'blankSelect',question:'輸入申告の基本情報について、空欄に最も適切な語句を選べ。\n「貨物の【A】、数量、価格、【B】等を確認し、必要な情報を申告する。」',blanks:[{label:'A',options:['品名','天気','担当者の趣味'],answer:'品名'},{label:'B',options:['原産地','座席番号','広告費'],answer:'原産地'}],point:'品名・数量・価格・原産地は、申告内容の中核となる情報です。',detail:'貨物の性質や適用法令により必要事項は変わりますが、基本情報を資料と突合して正確に申告します。',auditStatus:'approved',sourceType:'original',lawBaseline:'2026-07-01'},
{id:'JM-004',subject:'通関実務',topic:'品目分類',answerType:'multiChoice',selectionCount:2,question:'品目分類を検討する際に重要な情報を2つ選べ。',choices:['貨物の材質・構造・用途','品名だけでなく客観的な商品資料','輸入者の希望税率','担当者の過去の感覚','広告コピーだけ'],answers:[0,1],point:'品目分類は、貨物の客観的な性状と分類ルールに基づきます。',detail:'カタログ、仕様書、成分表等を確認し、関税率表や分類通則等に照らして判断します。',auditStatus:'approved',sourceType:'original',lawBaseline:'2026-07-01'},
{id:'JM-005',subject:'通関実務',topic:'輸入申告書',answerType:'declaration',question:'次の資料を基に、簡易申告フォームの3項目を入力せよ。',sourceText:'商品：綿100％のシャツ\n数量：100枚\nインボイス価格：500,000円\n原産国：ベトナム\n※この問題はUI検証用に単純化しており、実際の税番判定・課税価格計算を代替するものではありません。',declarationFields:[{key:'goods',label:'品名',answer:'綿100％のシャツ',aliases:['綿シャツ','シャツ']},{key:'qty',label:'数量',answer:'100',aliases:['100枚']},{key:'origin',label:'原産国',answer:'ベトナム',aliases:['ベトナム社会主義共和国']}],point:'申告書では、資料から必要事項を正確に転記・判断する力が必要です。',detail:'製品版の申告書演習は、品目番号、課税価格、税額等を含む複数項目に分割し、スマホで資料と入力欄を往復しやすいUIにします。',auditStatus:'approved',sourceType:'original',lawBaseline:'2026-07-01'},
{id:'JM-006',subject:'通関実務',topic:'申告前確認',answerType:'singleChoice',question:'輸入申告直前の最終確認として最も適切なものはどれか。',choices:['インボイス等の資料と申告内容を照合し、税番・価格・数量・原産地等の整合を確認する','入力欄が埋まっていれば資料確認は不要である','価格だけ確認すればよい','輸入者名だけ確認すればよい','前回申告をそのまま流用する'],answer:0,point:'申告前は、資料と申告データの整合確認が重要です。',detail:'前回と同一商品に見えても、価格、数量、原産地、仕様、法令適用が変わることがあります。',auditStatus:'approved',sourceType:'original',lawBaseline:'2026-07-01'},
{id:'XR-001',subject:'関税法等',topic:'法令基準日',answerType:'singleChoice',question:'第60回通関士試験の学習で法令改正を扱う際、このアプリが基準として表示する日付はどれか。',choices:['2026年7月1日','2026年1月1日','2025年10月5日','2026年10月4日','2027年4月1日'],answer:0,point:'本アプリの第60回対策コンテンツは、2026年7月1日を法令基準として管理します。',detail:'問題ごとにlawBaselineとcontentVersionを持ち、改正検知後は影響問題を監査してから公開します。',auditStatus:'approved',sourceType:'appMetadata',lawBaseline:'2026-07-01'}
];
