import XCTest
@testable import KanriEiyoushiSprint
import LearningSprintCore

final class KanriEiyoushiSprintTests: XCTestCase {
    func testCanonicalIdentifiersDoNotDrift(){XCTAssertEqual(KanriAppConfig.bundleID,"jp.allsunday1122.kanrieiyoushi");XCTAssertEqual(KanriAppConfig.appStoreConnectID,"6799753841");XCTAssertEqual(KanriAppConfig.codemagicProfile,"kanrieiyoushi_appstore");XCTAssertEqual(KanriAppConfig.productID,"jp.allsunday1122.kanrieiyoushi.premium");XCTAssertEqual(KanriAppConfig.subjects.count,10);XCTAssertEqual(KanriAppConfig.expectedPerRound.values.reduce(0,+),200)}
    func testDailyTargetsAndShuffleSettingsPersistInJSONBackup() throws {let temp=FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString,isDirectory:true);defer{try? FileManager.default.removeItem(at:temp)};let s=LearningStateStore(bundleID:KanriAppConfig.bundleID,contentVersion:KanriAppConfig.contentVersion,directoryURL:temp);var state=LearningState(contentVersion:KanriAppConfig.contentVersion);state.dailyTarget=16;state.shuffleQuestions=false;state.shuffleChoices=true;let imported=try s.importBackup(s.exportBackup(state));XCTAssertEqual(imported.dailyTarget,16);XCTAssertEqual(imported.shuffleQuestions,false);XCTAssertEqual(imported.shuffleChoices,true)}
    func testLegacyNilShuffleGetsSafeDefaults() throws {let temp=FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString,isDirectory:true);defer{try? FileManager.default.removeItem(at:temp)};let s=LearningStateStore(bundleID:KanriAppConfig.bundleID,contentVersion:KanriAppConfig.contentVersion,directoryURL:temp);var state=LearningState(contentVersion:KanriAppConfig.contentVersion);state.shuffleQuestions=nil;state.shuffleChoices=nil;let imported=try s.importBackup(s.exportBackup(state));XCTAssertEqual(imported.shuffleQuestions,true);XCTAssertEqual(imported.shuffleChoices,false)}
    func testUnknownRegistersWeakAndThreeCorrectClears() throws {let q=LearningQuestion(id:"T1",subject:"基礎栄養",topic:"test",answerType:.singleChoice,prompt:"test",choices:["A","B","C","D","E"],correctIndices:[0],memoryPoint:"test",explanation:"test",sourceCheckedAt:"2026-08-09",lawBaselineDate:"2026-08-09",contentVersion:KanriAppConfig.contentVersion);var state=LearningState(contentVersion:KanriAppConfig.contentVersion);LearningEngine.record(question:q,evaluation:try LearningEngine.evaluate(q,answer:.unknown),state:&state);XCTAssertNotNil(state.weakQuestions[q.id]);for _ in 0..<3{LearningEngine.record(question:q,evaluation:try LearningEngine.evaluate(q,answer:AnswerPayload(selectedIndices:[0])),state:&state)};XCTAssertNil(state.weakQuestions[q.id])}
}
