import Foundation
#if canImport(Darwin)
import Darwin
#elseif canImport(Glibc)
import Glibc
#endif

public enum AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationTarget: String, Codable, Equatable, Sendable { case pendingMarker="PENDING_MARKER", immutableRecord="IMMUTABLE_RECORD", ledgerHead="LEDGER_HEAD" }
public enum AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationFaultPoint: String, Codable, Equatable, Sendable { case beforeDataSync="BEFORE_DATA_SYNC", afterDataSyncBeforePublish="AFTER_DATA_SYNC_BEFORE_PUBLISH", afterPublishBeforeDirectorySync="AFTER_PUBLISH_BEFORE_DIRECTORY_SYNC", afterDirectorySync="AFTER_DIRECTORY_SYNC" }
public struct AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationInjectedFault: Equatable, Sendable { public let target:AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationTarget; public let point:AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationFaultPoint; public init(target:AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationTarget,point:AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationFaultPoint){self.target=target;self.point=point} }
public enum AnalysisPhysicalRealAudioBridgeConsumptionDurableSyncMode: String, Codable, Equatable, Sendable { case darwinFullFSync="DARWIN_F_FULLFSYNC", darwinFSyncFallback="DARWIN_FSYNC_FALLBACK", posixFSync="POSIX_FSYNC" }
public struct AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationReceipt: Codable, Equatable, Sendable { public let schemaVersion:Int; public let target:AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationTarget; public let byteCount:Int; public let dataSyncMode:AnalysisPhysicalRealAudioBridgeConsumptionDurableSyncMode; public let atomicPublish:Bool; public let parentDirectorySynced:Bool; public init(schemaVersion:Int=1,target:AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationTarget,byteCount:Int,dataSyncMode:AnalysisPhysicalRealAudioBridgeConsumptionDurableSyncMode,atomicPublish:Bool,parentDirectorySynced:Bool){self.schemaVersion=schemaVersion;self.target=target;self.byteCount=byteCount;self.dataSyncMode=dataSyncMode;self.atomicPublish=atomicPublish;self.parentDirectorySynced=parentDirectorySynced} }
public enum AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationError: Error, Equatable, Sendable { case pathOutsideLedgerRoot, symbolicLinkRejected, nonRegularTargetRejected, oversizedFile, targetCollision, namespaceSubstitutionDetected, temporaryOpenFailed(Int32), writeFailed(Int32), dataSyncFailed(Int32), publishFailed(Int32), temporaryCleanupFailed(Int32), directoryOpenFailed(Int32), directorySyncFailed(Int32), postPublishVerificationFailed, injectedFault(AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationInjectedFault) }

enum AnalysisPhysicalRealAudioBridgeConsumptionDurablePublication {
 static let temporaryPrefix=".w53-pub-"; static let temporarySuffix=".tmp"; static let maximumInterruptedTemporaryFilesPerDirectory=32
 static func isInterruptedTemporaryFileName(_ name:String)->Bool{name.hasPrefix(temporaryPrefix)&&name.hasSuffix(temporarySuffix)&&name.count>temporaryPrefix.count+temporarySuffix.count}
 @discardableResult static func replaceAtomically(_ data:Data,to destinationURL:URL,within rootURL:URL,maximumBytes:Int,target:AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationTarget,injectedFault:AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationInjectedFault?=nil)throws->AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationReceipt{
  try validateRequest(data:data,destinationURL:destinationURL,rootURL:rootURL,maximumBytes:maximumBytes)
  return try mapNamespaceErrors {
   let parent=destinationURL.deletingLastPathComponent(); let destinationName=destinationURL.lastPathComponent
   return try AnalysisPhysicalRealAudioBridgeConsumptionNamespaceHardening.withPinnedDirectory(parent,within:rootURL){ directory in
    let initialDestination=try AnalysisPhysicalRealAudioBridgeConsumptionNamespaceHardening.entryIdentity(name:destinationName,in:directory)
    if let initialDestination { try AnalysisPhysicalRealAudioBridgeConsumptionNamespaceHardening.validateRegularEntry(initialDestination,maximumBytes:maximumBytes) }
    let tempName=temporaryPrefix+UUID().uuidString.lowercased()+temporarySuffix
    let fd=try AnalysisPhysicalRealAudioBridgeConsumptionNamespaceHardening.openExclusiveRegularFile(name:tempName,in:directory)
    var fdOpen=true; var preserveTemporary=false; var published=false
    defer { if fdOpen {_=close(fd)}; if !published && !preserveTemporary, let id=try? AnalysisPhysicalRealAudioBridgeConsumptionNamespaceHardening.entryIdentity(name:tempName,in:directory) { try? AnalysisPhysicalRealAudioBridgeConsumptionNamespaceHardening.unlinkExpectedEntry(name:tempName,expectedIdentity:id,in:directory) } }
    try writeAll(data,to:fd); try injectIfRequested(injectedFault,target:target,point:.beforeDataSync,preserveTemporary:&preserveTemporary); let syncMode=try syncFileDescriptor(fd); try injectIfRequested(injectedFault,target:target,point:.afterDataSyncBeforePublish,preserveTemporary:&preserveTemporary); _=close(fd); fdOpen=false
    guard let tempIdentity=try AnalysisPhysicalRealAudioBridgeConsumptionNamespaceHardening.entryIdentity(name:tempName,in:directory) else { throw AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationError.postPublishVerificationFailed }; try AnalysisPhysicalRealAudioBridgeConsumptionNamespaceHardening.validateRegularEntry(tempIdentity,maximumBytes:maximumBytes)
    try AnalysisPhysicalRealAudioBridgeConsumptionNamespaceHardening.renameEntry(sourceName:tempName,destinationName:destinationName,expectedDestinationIdentity:initialDestination,in:directory); published=true
    try injectIfRequested(injectedFault,target:target,point:.afterPublishBeforeDirectorySync,preserveTemporary:&preserveTemporary); try AnalysisPhysicalRealAudioBridgeConsumptionNamespaceHardening.synchronizeDirectory(directory); try injectIfRequested(injectedFault,target:target,point:.afterDirectorySync,preserveTemporary:&preserveTemporary)
    let reopened=try readEntry(name:destinationName,maximumBytes:maximumBytes,in:directory); guard reopened==data else{throw AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationError.postPublishVerificationFailed}
    return .init(target:target,byteCount:data.count,dataSyncMode:syncMode,atomicPublish:true,parentDirectorySynced:true)
   }
  }
 }
 @discardableResult static func createExclusive(_ data:Data,at destinationURL:URL,within rootURL:URL,maximumBytes:Int,target:AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationTarget,injectedFault:AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationInjectedFault?=nil)throws->AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationReceipt{
  try validateRequest(data:data,destinationURL:destinationURL,rootURL:rootURL,maximumBytes:maximumBytes)
  return try mapNamespaceErrors {
   let parent=destinationURL.deletingLastPathComponent(); let destinationName=destinationURL.lastPathComponent
   return try AnalysisPhysicalRealAudioBridgeConsumptionNamespaceHardening.withPinnedDirectory(parent,within:rootURL){ directory in
    if let existing=try AnalysisPhysicalRealAudioBridgeConsumptionNamespaceHardening.entryIdentity(name:destinationName,in:directory){ if existing.isSymbolicLink{throw AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationError.symbolicLinkRejected}; throw AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationError.targetCollision }
    let tempName=temporaryPrefix+UUID().uuidString.lowercased()+temporarySuffix; let fd=try AnalysisPhysicalRealAudioBridgeConsumptionNamespaceHardening.openExclusiveRegularFile(name:tempName,in:directory)
    var fdOpen=true; var preserveTemporary=false; var targetPublished=false
    defer { if fdOpen{_=close(fd)}; if !preserveTemporary, let id=try? AnalysisPhysicalRealAudioBridgeConsumptionNamespaceHardening.entryIdentity(name:tempName,in:directory) { try? AnalysisPhysicalRealAudioBridgeConsumptionNamespaceHardening.unlinkExpectedEntry(name:tempName,expectedIdentity:id,in:directory) } }
    try writeAll(data,to:fd); try injectIfRequested(injectedFault,target:target,point:.beforeDataSync,preserveTemporary:&preserveTemporary); let syncMode=try syncFileDescriptor(fd); try injectIfRequested(injectedFault,target:target,point:.afterDataSyncBeforePublish,preserveTemporary:&preserveTemporary); _=close(fd); fdOpen=false
    guard let tempIdentity=try AnalysisPhysicalRealAudioBridgeConsumptionNamespaceHardening.entryIdentity(name:tempName,in:directory) else{throw AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationError.postPublishVerificationFailed}; try AnalysisPhysicalRealAudioBridgeConsumptionNamespaceHardening.validateRegularEntry(tempIdentity,maximumBytes:maximumBytes)
    do { try AnalysisPhysicalRealAudioBridgeConsumptionNamespaceHardening.linkEntryExclusive(sourceName:tempName,destinationName:destinationName,in:directory) } catch let error as AnalysisPhysicalRealAudioBridgeConsumptionNamespaceError { if case .entryLinkFailed(let code)=error, code==EEXIST{throw AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationError.targetCollision}; throw error }
    targetPublished=true; try injectIfRequested(injectedFault,target:target,point:.afterPublishBeforeDirectorySync,preserveTemporary:&preserveTemporary)
    try AnalysisPhysicalRealAudioBridgeConsumptionNamespaceHardening.unlinkExpectedEntry(name:tempName,expectedIdentity:tempIdentity,in:directory); preserveTemporary=true; try AnalysisPhysicalRealAudioBridgeConsumptionNamespaceHardening.synchronizeDirectory(directory); try injectIfRequested(injectedFault,target:target,point:.afterDirectorySync,preserveTemporary:&preserveTemporary)
    let reopened=try readEntry(name:destinationName,maximumBytes:maximumBytes,in:directory); guard targetPublished && reopened==data else{throw AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationError.postPublishVerificationFailed}
    return .init(target:target,byteCount:data.count,dataSyncMode:syncMode,atomicPublish:true,parentDirectorySynced:true)
   }
  }
 }
 static func removeDurably(_ url:URL,within rootURL:URL)throws{
  guard AnalysisPhysicalRealAudioBridgeConsumptionSecureFilesystem.lexicallyContained(url,within:rootURL) else{throw AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationError.pathOutsideLedgerRoot}
  try mapNamespaceErrors { let parent=url.deletingLastPathComponent(); let name=url.lastPathComponent; try AnalysisPhysicalRealAudioBridgeConsumptionNamespaceHardening.withPinnedDirectory(parent,within:rootURL){directory in guard let identity=try AnalysisPhysicalRealAudioBridgeConsumptionNamespaceHardening.entryIdentity(name:name,in:directory) else{return}; try AnalysisPhysicalRealAudioBridgeConsumptionNamespaceHardening.validateRegularEntry(identity); try AnalysisPhysicalRealAudioBridgeConsumptionNamespaceHardening.unlinkExpectedEntry(name:name,expectedIdentity:identity,in:directory); try AnalysisPhysicalRealAudioBridgeConsumptionNamespaceHardening.synchronizeDirectory(directory)} }
 }
 static func syncDirectoryMetadata(_ directoryURL:URL,within rootURL:URL)throws{ try mapNamespaceErrors { try AnalysisPhysicalRealAudioBridgeConsumptionNamespaceHardening.withPinnedDirectory(directoryURL,within:rootURL){try AnalysisPhysicalRealAudioBridgeConsumptionNamespaceHardening.synchronizeDirectory($0)} } }
 static func validateInterruptedTemporaryFile(_ url:URL,within rootURL:URL,maximumBytes:Int)throws{ guard isInterruptedTemporaryFileName(url.lastPathComponent) else{throw AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationError.postPublishVerificationFailed}; try mapNamespaceErrors{ try AnalysisPhysicalRealAudioBridgeConsumptionNamespaceHardening.withPinnedDirectory(url.deletingLastPathComponent(),within:rootURL){dir in guard let identity=try AnalysisPhysicalRealAudioBridgeConsumptionNamespaceHardening.entryIdentity(name:url.lastPathComponent,in:dir) else{throw AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationError.postPublishVerificationFailed}; try AnalysisPhysicalRealAudioBridgeConsumptionNamespaceHardening.validateRegularEntry(identity,maximumBytes:maximumBytes)} } }
 private static func validateRequest(data:Data,destinationURL:URL,rootURL:URL,maximumBytes:Int)throws{guard data.count<=maximumBytes else{throw AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationError.oversizedFile}; guard AnalysisPhysicalRealAudioBridgeConsumptionSecureFilesystem.lexicallyContained(destinationURL,within:rootURL) else{throw AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationError.pathOutsideLedgerRoot}; try AnalysisPhysicalRealAudioBridgeConsumptionSecureFilesystem.validateDirectory(destinationURL.deletingLastPathComponent(),within:rootURL)}
 private static func readEntry(name:String,maximumBytes:Int,in directory:AnalysisPhysicalRealAudioBridgeConsumptionPinnedDirectory)throws->Data{ guard let identity=try AnalysisPhysicalRealAudioBridgeConsumptionNamespaceHardening.entryIdentity(name:name,in:directory) else{throw AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationError.postPublishVerificationFailed}; try AnalysisPhysicalRealAudioBridgeConsumptionNamespaceHardening.validateRegularEntry(identity,maximumBytes:maximumBytes); let fd=try AnalysisPhysicalRealAudioBridgeConsumptionNamespaceHardening.openRegularFileForRead(name:name,in:directory); defer{_=close(fd)}; var data=Data(); data.reserveCapacity(Int(identity.size)); var buffer=[UInt8](repeating:0,count:min(65536,max(1,maximumBytes))); while true{let count=buffer.withUnsafeMutableBytes{read(fd,$0.baseAddress,$0.count)}; if count<0{if errno==EINTR{continue};throw AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationError.postPublishVerificationFailed}; if count==0{break}; data.append(contentsOf:buffer.prefix(count)); if data.count>maximumBytes{throw AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationError.oversizedFile}}; guard data.count==Int(identity.size) else{throw AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationError.postPublishVerificationFailed}; return data }
 private static func writeAll(_ data:Data,to fd:Int32)throws{guard fd>=0 else{throw AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationError.temporaryOpenFailed(errno)}; try data.withUnsafeBytes{raw in guard let base=raw.baseAddress else{return}; var offset=0; while offset<raw.count{let result=write(fd,base.advanced(by:offset),raw.count-offset); if result<0{if errno==EINTR{continue};throw AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationError.writeFailed(errno)}; if result==0{throw AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationError.writeFailed(EIO)}; offset+=result}}}
 private static func syncFileDescriptor(_ fd:Int32)throws->AnalysisPhysicalRealAudioBridgeConsumptionDurableSyncMode{guard fd>=0 else{throw AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationError.temporaryOpenFailed(errno)}; #if canImport(Darwin)
  if fcntl(fd,F_FULLFSYNC)==0{return .darwinFullFSync}; guard fsync(fd)==0 else{throw AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationError.dataSyncFailed(errno)}; return .darwinFSyncFallback
  #else
  guard fsync(fd)==0 else{throw AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationError.dataSyncFailed(errno)}; return .posixFSync
  #endif
 }
 private static func injectIfRequested(_ injection:AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationInjectedFault?,target:AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationTarget,point:AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationFaultPoint,preserveTemporary:inout Bool)throws{guard let injection,injection.target==target,injection.point==point else{return}; if point != .afterDirectorySync{preserveTemporary=true}; throw AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationError.injectedFault(injection)}
 private static func mapNamespaceErrors<T>(_ body:()throws->T)throws->T{do{return try body()}catch let e as AnalysisPhysicalRealAudioBridgeConsumptionNamespaceError{switch e{case .pathOutsideRoot:throw AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationError.pathOutsideLedgerRoot;case .symbolicLinkRejected:throw AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationError.symbolicLinkRejected;case .nonRegularFileRejected:throw AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationError.nonRegularTargetRejected;case .oversizedTemporary:throw AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationError.oversizedFile;case .entryIdentityChanged,.directoryIdentityChanged:throw AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationError.namespaceSubstitutionDetected;case .entryOpenFailed(let c):throw AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationError.temporaryOpenFailed(c);case .entryRenameFailed(let c),.entryLinkFailed(let c),.entryRemovalFailed(let c):throw AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationError.publishFailed(c);case .directoryOpenFailed(let c):throw AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationError.directoryOpenFailed(c);case .directorySyncFailed(let c):throw AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationError.directorySyncFailed(c);default:throw AnalysisPhysicalRealAudioBridgeConsumptionDurablePublicationError.postPublishVerificationFailed}}}
}
