(function(){
'use strict';
var Q=(window.KANRI_Q||[]).filter(function(q){return !q.z||q.z==='approved';});
var C=['社会・環境','人体・疾病','食べ物','基礎栄養','応用栄養','栄養教育','臨床栄養','公衆栄養','給食経営','応用力'];
var EXPECTED={'社会・環境':16,'人体・疾病':26,'食べ物':25,'基礎栄養':14,'応用栄養':16,'栄養教育':13,'臨床栄養':26,'公衆栄養':16,'給食経営':18,'応用力':30};
var KEY='kanri_master_v061',OLD=['kanri_master_v060','kanri_master_v030','kanriStable021'];
var QMAP={};Q.forEach(function(q){QMAP[q.id]=q;});
var S,X=null;
function E(id){return document.getElementById(id);}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function clone(v){return JSON.parse(JSON.stringify(v));}
function dayKey(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
function todayKey(){return dayKey(new Date());}
function qRound(q){return Number(q&&q.round)||1;}
function compKey(r,c){return r+'|'+c;}
function fresh(){return{schema:61,goal:8,shuffleQ:true,shuffleA:false,font:'normal',examDate:'',selectedRound:1,weak:{},seen:{},hist:[],comp:{},mockComp:{1:0,2:0,3:0},ip:null,today:{date:todayKey(),count:0}};}
function validMap(obj){var out={};obj=obj||{};Object.keys(obj).forEach(function(id){if(QMAP[id])out[id]=obj[id];});return out;}
function normalize(raw){var n=fresh();if(!raw||typeof raw!=='object')return n;['goal','shuffleQ','shuffleA','font','examDate','selectedRound'].forEach(function(k){if(raw[k]!=null)n[k]=raw[k];});n.weak=validMap(raw.weak);n.seen=validMap(raw.seen);n.hist=(raw.hist||[]).filter(function(h){return h&&QMAP[h.id];}).map(function(h){var q=QMAP[h.id];return{id:h.id,c:h.c||q.c,round:Number(h.round)||qRound(q),ok:!!h.ok,ts:Number(h.ts)||Date.now(),mode:h.mode||h.k||'sprint'};});Object.keys(raw.comp||{}).forEach(function(k){if(k.indexOf('|')>0)n.comp[k]=Number(raw.comp[k])||0;else if(C.indexOf(k)>=0)n.comp[compKey(1,k)]=Number(raw.comp[k])||0;});n.mockComp=raw.mockComp||n.mockComp;n.today=raw.today||n.today;if(raw.ip&&Array.isArray(raw.ip.ids)){var ids=raw.ip.ids.filter(function(id){return !!QMAP[id];});if(ids.length){n.ip=clone(raw.ip);n.ip.ids=ids;n.ip.mode=n.ip.mode||n.ip.k||'today';n.ip.round=Number(n.ip.round)||qRound(QMAP[ids[0]]);n.ip.label=n.ip.label||'';n.ip.i=Math.min(Number(n.ip.i)||0,ids.length-1);n.ip.ok=Number(n.ip.ok)||0;n.ip.answered=!!n.ip.answered;}}n.schema=61;return n;}
function load(){var raw=null;try{var keys=[KEY].concat(OLD);for(var i=0;i<keys.length;i++){var t=localStorage.getItem(keys[i]);if(t){raw=JSON.parse(t);break;}}}catch(e){}S=normalize(raw);if(S.today.date!==todayKey())S.today={date:todayKey(),count:0};if([4,8,16].indexOf(Number(S.goal))<0)S.goal=8;if([1,2,3].indexOf(Number(S.selectedRound))<0)S.selectedRound=1;if(['small','normal','large'].indexOf(S.font)<0)S.font='normal';}
function save(){try{localStorage.setItem(KEY,JSON.stringify(S));}catch(e){}refreshHome();}
function toast(msg){var t=E('toast');t.textContent=msg;t.classList.remove('hidden');setTimeout(function(){t.classList.add('hidden');},1700);}
function show(v){['home','quiz','result','mock','history','settings'].forEach(function(id){E(id).classList.add('hidden');});E(v).classList.remove('hidden');E('nav').classList.toggle('hidden',v==='quiz'||v==='result');document.querySelectorAll('.nav button').forEach(function(b){b.classList.toggle('active',b.getAttribute('data-v')===v);});if(v==='mock')renderMock();if(v==='history')renderHistory();if(v==='settings')renderSettings();window.scrollTo(0,0);}
function shuffle(a){var b=a.slice();for(var i=b.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1)),t=b[i];b[i]=b[j];b[j]=t;}return b;}
function unique(a){var seen={},out=[];a.forEach(function(q){if(q&&!seen[q.id]){seen[q.id]=1;out.push(q);}});return out;}
function pick(pool,n){var u=[],w=[],s=[];pool.forEach(function(q){if(!S.seen[q.id])u.push(q);else if(S.weak[q.id])w.push(q);else s.push(q);});if(S.shuffleQ){u=shuffle(u);w=shuffle(w);s=shuffle(s);}return unique(u.concat(w,s)).slice(0,Math.min(n,pool.length));}
function renderCountdown(){var box=E('countdown');if(!S.examDate){box.classList.add('hidden');return;}var exam=new Date(S.examDate+'T00:00:00'),now=new Date();now.setHours(0,0,0,0);var days=Math.ceil((exam-now)/86400000);if(days<0){box.classList.add('hidden');return;}var remain=Math.max(0,600-Object.keys(S.seen).length),pace=days?Math.ceil(remain/days):remain;box.innerHTML='<span>試験まで</span><b class="dnum">'+days+'日</b><small>600問完走まで 1日約'+pace+'問</small>';box.classList.remove('hidden');}
function renderRoundSeg(){document.querySelectorAll('#roundSeg button').forEach(function(b){var on=Number(b.getAttribute('data-round'))===Number(S.selectedRound);b.classList.toggle('active',on);b.setAttribute('aria-pressed',on?'true':'false');});}
function renderSubjects(){var r=Number(S.selectedRound),root=E('subjects'),doneCats=0;root.innerHTML='';C.forEach(function(c){var arr=Q.filter(function(q){return qRound(q)===r&&q.c===c;}),complete=Number(S.comp[compKey(r,c)])||0;if(complete)doneCats++;var seen=arr.filter(function(q){return !!S.seen[q.id];}).length,pct=arr.length?Math.round(seen/arr.length*100):0,last=null;for(var i=S.hist.length-1;i>=0;i--){if(S.hist[i].c===c&&Number(S.hist[i].round)===r){last=S.hist[i];break;}}var pill=last?(last.ok?'<span class="pill good">前回 正解</span>':'<span class="pill bad">前回 誤答</span>'):'<span class="pill neutral">未受験</span>',b=document.createElement('button');b.className='subject';b.innerHTML='<div class="miniRing" style="--p:'+pct+'"><span>'+pct+'%</span></div><div class="subjectcopy"><b>'+esc(c)+'</b><small>'+arr.length+'問・解答済 '+seen+'問・完答 '+complete+'回</small>'+pill+'</div>';b.onclick=function(){startSession(pick(arr,Number(S.goal)||8),'subject',c,r);};root.appendChild(b);});E('subjectDone').textContent='第'+r+'回 完答 '+doneCats+'/10';}
function refreshHome(){if(S.today.date!==todayKey())S.today={date:todayKey(),count:0};var goal=Number(S.goal)||8,done=Math.min(Number(S.today.count)||0,goal),circ=2*Math.PI*35;E('ringfill').style.strokeDasharray=circ;E('ringfill').style.strokeDashoffset=circ*(1-done/goal);E('todayDone').textContent=done;E('todayGoal').textContent='/ '+goal;E('todayNote').textContent=done>=goal?'今日の目標を達成しました':'あと'+(goal-done)+'問で今日の目標';E('todayLabel').textContent=goal+'問で始める';E('weakN').textContent=Object.keys(S.weak).length;var total=S.hist.length,ok=S.hist.filter(function(h){return h.ok;}).length;E('homeTotal').textContent=total;E('homeRate').textContent=total?Math.round(ok/total*100)+'%':'—';E('homeWeak').textContent=Object.keys(S.weak).length;if(S.ip&&S.ip.ids&&S.ip.ids.length){E('resume').classList.remove('hidden');E('resumeText').textContent=(S.ip.mode==='mock'?'模試 第'+S.ip.round+'回 ':'')+(Math.min(S.ip.i+1,S.ip.ids.length))+' / '+S.ip.ids.length+'問';}else E('resume').classList.add('hidden');document.documentElement.setAttribute('data-font',S.font);renderCountdown();renderRoundSeg();renderSubjects();}
function startSession(arr,mode,label,round){if(!arr||!arr.length){toast('問題データを読み込めません');return;}X={mode:mode,label:label,round:Number(round)||0,ids:arr.map(function(q){return q.id;}),i:0,ok:0,answered:false,selected:null,started:Date.now()};S.ip=clone(X);save();show('quiz');renderQuestion();}
function startMock(r){var arr=Q.filter(function(q){return qRound(q)===r;});if(arr.length!==200){lockApp('第'+r+'回の問題数が200問ではありません。');return;}startSession(arr,'mock','第'+r+'回 模擬試験',r);}
function resume(){if(!S.ip||!S.ip.ids||!S.ip.ids.length)return;X=clone(S.ip);if(X.answered){if(X.i>=X.ids.length-1){finish();return;}X.i++;X.answered=false;X.selected=null;S.ip=clone(X);save();}show('quiz');renderQuestion();}
function current(){return X&&QMAP[X.ids[X.i]]?QMAP[X.ids[X.i]]:null;}
function mark(type){return type==='o'?'<svg class="mark mark-o" viewBox="0 0 44 44" aria-hidden="true"><circle cx="22" cy="22" r="16"></circle></svg>':'<svg class="mark mark-x" viewBox="0 0 44 44" aria-hidden="true"><path d="M11 11 L33 33"></path><path class="late" d="M33 11 L11 33"></path></svg>';}
function renderQuestion(){var q=current();if(!q){finish();return;}var mock=X.mode==='mock';E('mockNotice').classList.toggle('hidden',!mock);E('qcat').textContent=(mock?'第'+qRound(q)+'回｜':'')+q.c+'｜'+q.t;E('qprog').textContent=(X.i+1)+' / '+X.ids.length;E('qtext').textContent=q.q;E('choices').innerHTML='';E('feedback').innerHTML='';E('dont').classList.remove('hidden');var opts=q.a.map(function(text,i){return{text:text,orig:i};});if(S.shuffleA)opts=shuffle(opts);opts.forEach(function(o,i){var b=document.createElement('button');b.className='choice';b.setAttribute('data-orig',o.orig);b.innerHTML='<span class="choiceNo">'+(i+1)+'</span><span class="choiceText">'+esc(o.text)+'</span>';b.onclick=function(){answer(o.orig,false);};E('choices').appendChild(b);});X.answered=false;X.selected=null;S.ip=clone(X);save();}
function record(q,ok,mode){if(ok){if(S.weak[q.id]){S.weak[q.id].st=(S.weak[q.id].st||0)+1;if(S.weak[q.id].st>=3){delete S.weak[q.id];if(mode!=='mock')toast('苦手から卒業しました');}}}else{var w=S.weak[q.id]||{st:0,n:0};w.st=0;w.n=(w.n||0)+1;S.weak[q.id]=w;}S.seen[q.id]=1;S.hist.push({id:q.id,c:q.c,round:qRound(q),ok:ok,ts:Date.now(),mode:mode});S.today.count=(Number(S.today.count)||0)+1;}
function answer(sel,dont){if(!X||X.answered)return;var q=current(),ok=!dont&&sel===q.x,mock=X.mode==='mock';X.answered=true;X.selected=dont?'dont':sel;if(ok)X.ok++;record(q,ok,X.mode);Array.prototype.forEach.call(E('choices').children,function(b){var orig=Number(b.getAttribute('data-orig'));b.disabled=true;if(mock){if(!dont&&orig===sel)b.classList.add('mockselected');else b.classList.add('dim');}else if(orig===q.x){b.classList.add('correct');b.insertAdjacentHTML('beforeend',mark('o'));}else if(!dont&&orig===sel){b.classList.add('wrong');b.insertAdjacentHTML('beforeend',mark('x'));}else b.classList.add('dim');});E('dont').classList.add('hidden');if(mock){E('feedback').innerHTML='<div class="mockanswer">回答を記録しました。模試終了まで正誤は表示しません。<button id="next" class="next">'+(X.i===X.ids.length-1?'採点する':'次の問題へ')+'</button></div>';}else{var streak=S.weak[q.id]?S.weak[q.id].st||0:3,src=q.s?'<a class="sourceLink" href="'+esc(q.s)+'" target="_blank" rel="noopener">一次資料を確認</a>':'';E('feedback').innerHTML='<div class="feedback"><div class="feedbackhead '+(ok?'ok':'ng')+'">'+(ok?'正解':'惜しい')+'</div><div class="memorybox"><span>ここだけ覚える</span><div class="memory">'+esc(q.m)+'</div></div><p class="reason">'+esc(q.r)+'</p><details><summary>もう少し詳しく</summary><p>'+esc(q.d)+'</p><small>基準：'+esc(q.y)+'</small>'+src+'</details><div class="streak"><span>苦手習得</span><b>'+Math.min(streak,3)+' / 3</b><i style="--w:'+(Math.min(streak,3)/3*100)+'%"></i></div><button id="next" class="next">'+(X.i===X.ids.length-1?'結果を見る':'次の問題へ')+'</button></div>';}E('next').onclick=next;S.ip=clone(X);save();}
function next(){if(!X||!X.answered)return;if(X.i>=X.ids.length-1){finish();return;}X.i++;renderQuestion();}
function finish(){if(!X)return;var done=clone(X),total=done.ids.length,rate=total?Math.round(done.ok/total*100):0;if(done.mode==='subject')S.comp[compKey(done.round,done.label)]=(Number(S.comp[compKey(done.round,done.label)])||0)+1;if(done.mode==='mock')S.mockComp[done.round]=(Number(S.mockComp[done.round])||0)+1;S.ip=null;save();E('score').textContent=done.ok+' / '+total;E('resultRate').textContent=rate+'%';E('resultWeak').textContent=Object.keys(S.weak).length+'問';E('resultEyebrow').textContent=done.mode==='mock'?'MOCK COMPLETE':'SPRINT COMPLETE';if(done.mode==='mock'){var above=done.ok>=120;E('rmsg').textContent=above?'120点以上です。次は苦手を短くつぶします。':'120点未満です。模試で見つかった苦手を短い反復へ戻します。';E('resultThirdLabel').textContent='120点目安';E('resultToday').textContent=above?'以上':'未満';E('resultToday').className=above?'mockscorePass':'mockscoreFail';E('resultAgainLabel').textContent='同じ回を再受験';E('resultAgain').onclick=function(){startMock(done.round);};}else{E('rmsg').textContent=rate>=80?'よく積み上がっています。':rate>=60?'合格につながるペースです。':'苦手が見えた分だけ、次が強くなる。';E('resultThirdLabel').textContent='今日';E('resultToday').textContent=S.today.count+'問';E('resultToday').className='';E('resultAgainLabel').textContent='同じ問題を解く';E('resultAgain').onclick=function(){startSession(done.ids.map(function(id){return QMAP[id];}).filter(Boolean),done.mode,done.label,done.round);};}E('resultWeakBtn').onclick=weakStart;show('result');X=done;}
function todayStart(){startSession(pick(Q,Number(S.goal)||8),'today','今日のスプリント',0);}
function weakStart(){var arr=Object.keys(S.weak).map(function(id){return QMAP[id];}).filter(Boolean);if(!arr.length){toast('現在の苦手はありません');return;}arr.sort(function(a,b){return(Number(S.weak[b.id].n)||0)-(Number(S.weak[a.id].n)||0);});if(S.shuffleQ)arr=shuffle(arr);startSession(arr.slice(0,Number(S.goal)||8),'weak','苦手復習',0);}
function renderMock(){var root=E('mockRounds');root.innerHTML='';[1,2,3].forEach(function(r){var arr=Q.filter(function(q){return qRound(q)===r;}),seen=arr.filter(function(q){return !!S.seen[q.id];}).length,complete=Number(S.mockComp[r])||0,d=document.createElement('section');d.className='mockround';d.innerHTML='<div class="mockroundhead"><b>第'+r+'回</b><span>200問</span></div><p>社会・環境16／人体・疾病26／食べ物25／基礎14／応用16／栄養教育13／臨床26／公衆16／給食18／応用力30</p><div class="mockprogress"><span>解答済 '+seen+' / 200</span><span>完答 '+complete+'回</span></div><button class="primary"><span><small>本番形式</small><b>第'+r+'回 200問を開始</b></span><span class="arrow">→</span></button>';d.querySelector('button').onclick=function(){startMock(r);};root.appendChild(d);});}
function renderHistory(){var total=S.hist.length,ok=S.hist.filter(function(h){return h.ok;}).length;E('histTotal').textContent=total;E('histRate').textContent=total?Math.round(ok/total*100)+'%':'—';E('histWeak').textContent=Object.keys(S.weak).length;var mastery=Math.min(100,Math.round(Object.keys(S.seen).length/600*100));E('mastery').textContent=mastery+'%';E('donut').style.setProperty('--p',mastery);var rs=E('roundStats');rs.innerHTML='';[1,2,3].forEach(function(r){var seen=Q.filter(function(q){return qRound(q)===r&&S.seen[q.id];}).length,p=Math.round(seen/200*100),row=document.createElement('div');row.className='roundstat';row.style.setProperty('--w',p+'%');row.innerHTML='<div><b>第'+r+'回</b><span>'+seen+' / 200問</span></div><i></i><small>模試完答 '+(Number(S.mockComp[r])||0)+'回</small>';rs.appendChild(row);});var bars=E('bars');bars.innerHTML='';C.forEach(function(c){var a=S.hist.filter(function(h){return h.c===c;}),co=a.filter(function(h){return h.ok;}).length,p=a.length?Math.round(co/a.length*100):0,row=document.createElement('div');row.className='barrow';row.innerHTML='<div><span>'+esc(c)+'</span><b>'+(a.length?p+'%':'未学習')+'</b></div><i><u style="width:'+p+'%"></u></i>';bars.appendChild(row);});renderHeatmap();var wl=E('weakList'),ids=Object.keys(S.weak);wl.innerHTML='';if(!ids.length)wl.innerHTML='<div class="empty">苦手はありません。いい状態です。</div>';else{ids.sort(function(a,b){return(Number(S.weak[b].n)||0)-(Number(S.weak[a].n)||0);});ids.forEach(function(id){var q=QMAP[id];if(!q)return;var b=document.createElement('button');b.className='weakrow';b.innerHTML='<span><b>第'+qRound(q)+'回｜'+esc(q.c)+'</b><small>'+esc(q.m)+'</small></span><em>'+(S.weak[id].st||0)+'/3</em>';b.onclick=function(){startSession([q],'weak',q.c,qRound(q));};wl.appendChild(b);});}}
function renderHeatmap(){var root=E('heatmap'),counts={};root.innerHTML='';S.hist.forEach(function(h){var k=dayKey(new Date(h.ts||Date.now()));counts[k]=(counts[k]||0)+1;});var now=new Date();now.setHours(0,0,0,0);for(var n=34;n>=0;n--){var d=new Date(now.getTime()-n*86400000),k=dayKey(d),count=counts[k]||0,lv=count===0?0:count<3?1:count<6?2:count<9?3:4,cell=document.createElement('span');cell.className='heat h'+lv;cell.title=k+' '+count+'問';root.appendChild(cell);}}
function renderSettings(){document.querySelectorAll('#goalSeg button').forEach(function(b){b.classList.toggle('active',Number(b.getAttribute('data-goal'))===Number(S.goal));});document.querySelectorAll('#fontSeg button').forEach(function(b){b.classList.toggle('active',b.getAttribute('data-font')===S.font);});E('shuffleQ').checked=!!S.shuffleQ;E('shuffleA').checked=!!S.shuffleA;E('examDate').value=S.examDate||'';}
function exportData(){var blob=new Blob([JSON.stringify(S,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='kanrieiyoushi-manabi-sprint-v061.json';document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},500);}
function importData(file){var reader=new FileReader();reader.onload=function(){try{S=normalize(JSON.parse(reader.result));save();renderSettings();toast('学習データを読み込みました');}catch(e){toast('JSONを読み込めませんでした');}};reader.readAsText(file);}
function integrity(){if(Q.length!==600)return'問題数 '+Q.length+' / 600';var ids=Q.map(function(q){return q.id;}),set={};for(var i=0;i<ids.length;i++){if(set[ids[i]])return'問題IDが重複しています';set[ids[i]]=1;}for(var r=1;r<=3;r++){var rq=Q.filter(function(q){return qRound(q)===r;});if(rq.length!==200)return'第'+r+'回 '+rq.length+' / 200';for(var c in EXPECTED){var n=rq.filter(function(q){return q.c===c;}).length;if(n!==EXPECTED[c])return'第'+r+'回 '+c+' '+n+' / '+EXPECTED[c];}}return'';}
function lockApp(msg){var box=E('dataError');if(box){box.textContent='問題データの検証に失敗しました：'+msg;box.classList.remove('hidden');}['today','weak','mockShortcut','resume'].forEach(function(id){if(E(id))E(id).disabled=true;});document.querySelectorAll('#roundSeg button,#subjects button').forEach(function(b){b.disabled=true;});toast('問題データを確認してください');}
function bind(){E('today').onclick=todayStart;E('resume').onclick=resume;E('weak').onclick=weakStart;E('mockShortcut').onclick=function(){show('mock');};E('quizBack').onclick=function(){show('home');};E('quizHome').onclick=function(){show('home');};E('dont').onclick=function(){answer(null,true);};E('resultHome').onclick=function(){show('home');};document.querySelectorAll('.nav button').forEach(function(b){b.onclick=function(){show(b.getAttribute('data-v'));};});document.querySelectorAll('#roundSeg button').forEach(function(b){b.onclick=function(){S.selectedRound=Number(b.getAttribute('data-round'));save();};});document.querySelectorAll('#goalSeg button').forEach(function(b){b.onclick=function(){S.goal=Number(b.getAttribute('data-goal'));save();renderSettings();};});document.querySelectorAll('#fontSeg button').forEach(function(b){b.onclick=function(){S.font=b.getAttribute('data-font');save();renderSettings();};});E('shuffleQ').onchange=function(){S.shuffleQ=this.checked;save();};E('shuffleA').onchange=function(){S.shuffleA=this.checked;save();};E('examDate').onchange=function(){S.examDate=this.value;save();};E('exportBtn').onclick=exportData;E('importFile').onchange=function(){if(this.files&&this.files[0])importData(this.files[0]);this.value='';};E('resetBtn').onclick=function(){if(confirm('学習データをすべて消去しますか？')){S=fresh();save();toast('リセットしました');}};}
load();bind();refreshHome();show('home');var err=integrity();if(err){lockApp(err);}else{document.documentElement.setAttribute('data-app-ready','true');window.KANRI_APP_READY=true;}
if('serviceWorker'in navigator)window.addEventListener('load',function(){navigator.serviceWorker.register('./sw.js?v=061').catch(function(){});});
})();
