(function(){
'use strict';
var Q=(window.KANRI_Q||[]).filter(function(q){return !q.z||q.z==='approved';});
var C=['社会・環境','人体・疾病','食べ物','基礎栄養','応用栄養','栄養教育','臨床栄養','公衆栄養','給食経営','応用力'];
var EXPECTED={'社会・環境':16,'人体・疾病':26,'食べ物':25,'基礎栄養':14,'応用栄養':16,'栄養教育':13,'臨床栄養':26,'公衆栄養':16,'給食経営':18,'応用力':30};
var KEY='kanri_master_v061',OLD_KEYS=['kanri_master_v060','kanri_master_v030','kanriStable021'];
var QMAP={};for(var qi=0;qi<Q.length;qi++)QMAP[Q[qi].id]=Q[qi];
function fresh(){return{schema:61,goal:8,shuffleQ:true,shuffleA:false,font:'normal',examDate:'',selectedRound:1,weak:{},seen:{},hist:[],comp:{},mockComp:{1:0,2:0,3:0},ip:null,today:{date:'',count:0}};}
var S=fresh(),X=null;
function E(id){return document.getElementById(id);}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function dateKey(d){var y=d.getFullYear(),m=('0'+(d.getMonth()+1)).slice(-2),day=('0'+d.getDate()).slice(-2);return y+'-'+m+'-'+day;}
function todayKey(){return dateKey(new Date());}
function clone(o){return JSON.parse(JSON.stringify(o));}
function shuffle(a){var b=a.slice();for(var i=b.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1)),t=b[i];b[i]=b[j];b[j]=t;}return b;}
function qRound(q){return Number(q&&q.round)||1;}
function compKey(r,c){return String(r)+'|'+c;}
function validMap(obj){var out={};obj=obj||{};for(var id in obj)if(QMAP[id])out[id]=obj[id];return out;}
function normalize(o){var n=fresh();if(!o||typeof o!=='object')return n;['goal','shuffleQ','shuffleA','font','examDate','selectedRound'].forEach(function(k){if(o[k]!=null)n[k]=o[k];});n.weak=validMap(o.weak);n.seen=validMap(o.seen);n.hist=(o.hist||[]).filter(function(h){return h&&QMAP[h.id];}).map(function(h){var q=QMAP[h.id];return{id:h.id,c:h.c||q.c,round:Number(h.round)||qRound(q),ok:!!h.ok,ts:Number(h.ts)||Date.now(),mode:h.mode||'sprint'};});n.comp={};var oc=o.comp||{};for(var k in oc){if(k.indexOf('|')>0)n.comp[k]=Number(oc[k])||0;else if(C.indexOf(k)>=0)n.comp[compKey(1,k)]=Number(oc[k])||0;}n.mockComp=o.mockComp||{1:0,2:0,3:0};n.today=o.today||n.today;if(o.ip&&o.ip.ids){var ids=o.ip.ids.filter(function(id){return !!QMAP[id];});if(ids.length){n.ip=clone(o.ip);n.ip.ids=ids;n.ip.mode=n.ip.mode||n.ip.k||'today';n.ip.round=Number(n.ip.round)||qRound(QMAP[ids[0]]);n.ip.label=n.ip.label||'';if(n.ip.i>=ids.length)n.ip.i=ids.length-1;}}n.schema=61;return n;}
function load(){var o=null;try{for(var i=0;i<OLD_KEYS.length;i++){var raw=localStorage.getItem(i===0?KEY:OLD_KEYS[i]);if(raw){o=JSON.parse(raw);break;}}}catch(e){}S=normalize(o);if(!S.today||S.today.date!==todayKey())S.today={date:todayKey(),count:0};if([4,8,16].indexOf(Number(S.goal))<0)S.goal=8;if(['small','normal','large'].indexOf(S.font)<0)S.font='normal';if([1,2,3].indexOf(Number(S.selectedRound))<0)S.selectedRound=1;}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(S));}catch(e){}refreshHome();}
function toast(t){E('toast').textContent=t;E('toast').classList.remove('hidden');setTimeout(function(){E('toast').classList.add('hidden');},1800);}
function show(v){['home','quiz','result','mock','history','settings'].forEach(function(id){E(id).classList.add('hidden');});E(v).classList.remove('hidden');E('nav').classList.toggle('hidden',v==='quiz'||v==='result');var bs=document.querySelectorAll('.nav button');for(var i=0;i<bs.length;i++)bs[i].classList.toggle('active',bs[i].getAttribute('data-v')===v);if(v==='mock')renderMock();if(v==='history')renderHistory();if(v==='settings')renderSettings();window.scrollTo(0,0);}
function unique(a){var seen={},out=[];for(var i=0;i<a.length;i++)if(a[i]&&!seen[a[i].id]){seen[a[i].id]=1;out.push(a[i]);}return out;}
function pick(pool,n){var u=[],w=[],s=[];for(var i=0;i<pool.length;i++){var q=pool[i];if(!S.seen[q.id])u.push(q);else if(S.weak[q.id])w.push(q);else s.push(q);}if(S.shuffleQ){u=shuffle(u);w=shuffle(w);s=shuffle(s);}return unique(u.concat(w,s)).slice(0,Math.min(n,pool.length));}
function renderCountdown(){var box=E('countdown');if(!S.examDate){box.classList.add('hidden');return;}var d=new Date(S.examDate+'T00:00:00'),now=new Date();now.setHours(0,0,0,0);var days=Math.ceil((d-now)/86400000);if(days<0){box.classList.add('hidden');return;}var remain=Math.max(0,600-Object.keys(S.seen).length),pace=days?Math.ceil(remain/days):remain;box.innerHTML='<span>試験まで</span><b class="dnum">'+days+'日</b><small>600問完走まで 1日約'+pace+'問</small>';box.classList.remove('hidden');}
function refreshHome(){if(S.today.date!==todayKey())S.today={date:todayKey(),count:0};var goal=Number(S.goal)||8,done=Math.min(Number(S.today.count)||0,goal),circ=2*Math.PI*35;E('ringfill').style.strokeDasharray=circ;E('ringfill').style.strokeDashoffset=circ*(1-done/goal);E('todayDone').textContent=done;E('todayGoal').textContent='/ '+goal;E('todayNote').textContent=done>=goal?'今日の目標を達成しました':'あと'+(goal-done)+'問で今日の目標';E('todayLabel').textContent=goal+'問で始める';E('weakN').textContent=Object.keys(S.weak).length;var h=S.hist,ok=0;for(var i=0;i<h.length;i++)if(h[i].ok)ok++;E('homeTotal').textContent=h.length;E('homeRate').textContent=h.length?Math.round(ok/h.length*100)+'%':'—';E('homeWeak').textContent=Object.keys(S.weak).length;if(S.ip&&S.ip.ids&&S.ip.ids.length){E('resume').classList.remove('hidden');E('resumeText').textContent=(S.ip.mode==='mock'?'模試 第'+S.ip.round+'回 ':'')+(Math.min(S.ip.i+1,S.ip.ids.length))+' / '+S.ip.ids.length+'問';}else E('resume').classList.add('hidden');document.documentElement.setAttribute('data-font',S.font);renderCountdown();renderRoundSeg();renderSubjects();}
function renderRoundSeg(){var bs=document.querySelectorAll('#roundSeg button');for(var i=0;i<bs.length;i++){var r=Number(bs[i].getAttribute('data-round')),on=r===Number(S.selectedRound);bs[i].classList.toggle('active',on);bs[i].setAttribute('aria-pressed',on?'true':'false');}}
function renderSubjects(){var r=Number(S.selectedRound),root=E('subjects');root.innerHTML='';var completed=0;C.forEach(function(c){var arr=Q.filter(function(q){return qRound(q)===r&&q.c===c;}),ck=compKey(r,c),comp=Number(S.comp[ck])||0;if(comp)completed++;var seen=arr.filter(function(q){return !!S.seen[q.id];}).length,pct=arr.length?Math.round(seen/arr.length*100):0,last=null;for(var j=S.hist.length-1;j>=0;j--){if(S.hist[j].c===c&&Number(S.hist[j].round)===r){last=S.hist[j];break;}}var pill=last?(last.ok?'<span class="pill good">前回 正解</span>':'<span class="pill bad">前回 誤答</span>'):'<span class="pill neutral">未受験</span>',b=document.createElement('button');b.className='subject';b.innerHTML='<div class="miniRing" style="--p:'+pct+'"><span>'+pct+'%</span></div><div class="subjectcopy"><b>'+esc(c)+'</b><small>'+arr.length+'問・解答済 '+seen+'問・完答 '+comp+'回</small>'+pill+'</div>';b.onclick=function(){startSession(pick(arr,Number(S.goal)||8),'subject',c,r);};root.appendChild(b);});E('subjectDone').textContent='第'+r+'回 完答 '+completed+'/10';}
function startSession(arr,mode,label,round){if(!arr||!arr.length){toast('問題データを読み込めません');return;}X={mode:mode,label:label,round:Number(round)||0,ids:arr.map(function(q){return q.id;}),i:0,ok:0,answered:false,selected:null,started:Date.now()};S.ip=clone(X);persist();show('quiz');renderQuestion();}
function startMock(r){var arr=Q.filter(function(q){return qRound(q)===r;});if(arr.length!==200){toast('第'+r+'回の200問データが不足しています');return;}startSession(arr,'mock','第'+r+'回 模擬試験',r);}
function resume(){if(!S.ip||!S.ip.ids||!S.ip.ids.length)return;X=clone(S.ip);if(X.answered){if(X.i>=X.ids.length-1){finish();return;}X.i++;X.answered=false;X.selected=null;S.ip=clone(X);persist();}show('quiz');renderQuestion();}
function current(){return X&&QMAP[X.ids[X.i]]?QMAP[X.ids[X.i]]:null;}
function makeMark(type){if(type==='o')return '<svg class="mark mark-o" viewBox="0 0 44 44" aria-hidden="true"><circle cx="22" cy="22" r="16"></circle></svg>';return '<svg class="mark mark-x" viewBox="0 0 44 44" aria-hidden="true"><path d="M11 11 L33 33"></path><path class="late" d="M33 11 L11 33"></path></svg>';}
function renderQuestion(){var q=current();if(!q){finish();return;}var mock=X.mode==='mock';E('mockNotice').classList.toggle('hidden',!mock);E('qcat').textContent=(mock?'第'+qRound(q)+'回｜':'')+q.c+'｜'+q.t;E('qprog').textContent=(X.i+1)+' / '+X.ids.length;E('qtext').textContent=q.q;E('choices').innerHTML='';E('feedback').innerHTML='';E('dont').classList.remove('hidden');var opts=[];for(var i=0;i<q.a.length;i++)opts.push({text:q.a[i],orig:i});if(S.shuffleA)opts=shuffle(opts);opts.forEach(function(o,j){var b=document.createElement('button');b.className='choice';b.setAttribute('data-orig',o.orig);b.innerHTML='<span class="choiceNo">'+(j+1)+'</span><span class="choiceText">'+esc(o.text)+'</span>';b.onclick=function(){answer(o.orig,false);};E('choices').appendChild(b);});X.answered=false;X.selected=null;S.ip=clone(X);persist();}
function recordAttempt(q,ok,mode){if(ok){if(S.weak[q.id]){S.weak[q.id].st=(S.weak[q.id].st||0)+1;if(S.weak[q.id].st>=3){delete S.weak[q.id];if(mode!=='mock')toast('苦手から卒業しました');}}}else{var w=S.weak[q.id]||{st:0,n:0};w.st=0;w.n=(w.n||0)+1;S.weak[q.id]=w;}S.seen[q.id]=1;S.hist.push({id:q.id,c:q.c,round:qRound(q),ok:ok,ts:Date.now(),mode:mode});S.today.count=(Number(S.today.count)||0)+1;}
function answer(sel,dont){if(!X||X.answered)return;var q=current(),ok=!dont&&sel===q.x,mock=X.mode==='mock';X.answered=true;X.selected=dont?'dont':sel;if(ok)X.ok++;recordAttempt(q,ok,X.mode);var cs=E('choices').children;for(var i=0;i<cs.length;i++){var orig=Number(cs[i].getAttribute('data-orig'));cs[i].disabled=true;if(mock){if(!dont&&orig===sel)cs[i].classList.add('mockselected');else cs[i].classList.add('dim');}else if(orig===q.x){cs[i].classList.add('correct');cs[i].insertAdjacentHTML('beforeend',makeMark('o'));}else if(!dont&&orig===sel){cs[i].classList.add('wrong');cs[i].insertAdjacentHTML('beforeend',makeMark('x'));}else cs[i].classList.add('dim');}E('dont').classList.add('hidden');if(mock){E('feedback').innerHTML='<div class="mockanswer">回答を記録しました。模試終了まで正誤は表示しません。<button id="next" class="next">'+(X.i===X.ids.length-1?'採点する':'次の問題へ')+'</button></div>';}else{var streak=S.weak[q.id]?S.weak[q.id].st||0:3,source=q.s?'<a class="sourceLink" href="'+esc(q.s)+'" target="_blank" rel="noopener">一次資料を確認</a>':'';E('feedback').innerHTML='<div class="feedback"><div class="feedbackhead '+(ok?'ok':'ng')+'">'+(ok?'正解':'惜しい')+'</div><div class="memorybox"><span>ここだけ覚える</span><div class="memory">'+esc(q.m)+'</div></div><p class="reason">'+esc(q.r)+'</p><details><summary>もう少し詳しく</summary><p>'+esc(q.d)+'</p><small>基準：'+esc(q.y)+'</small>'+source+'</details><div class="streak"><span>苦手習得</span><b>'+Math.min(streak,3)+' / 3</b><i style="--w:'+(Math.min(streak,3)/3*100)+'%"></i></div><button id="next" class="next">'+(X.i===X.ids.length-1?'結果を見る':'次の問題へ')+'</button></div>';}E('next').onclick=next;S.ip=clone(X);persist();}
function next(){if(!X||!X.answered)return;if(X.i>=X.ids.length-1){finish();return;}X.i++;renderQuestion();}
function finish(){if(!X)return;var done=clone(X),total=done.ids.length,rate=total?Math.round(done.ok/total*100):0;if(done.mode==='subject'){var ck=compKey(done.round,done.label);S.comp[ck]=(Number(S.comp[ck])||0)+1;}if(done.mode==='mock')S.mockComp[done.round]=(Number(S.mockComp[done.round])||0)+1;S.ip=null;persist();E('score').textContent=done.ok+' / '+total;E('resultRate').textContent=rate+'%';E('resultWeak').textContent=Object.keys(S.weak).length+'問';E('resultEyebrow').textContent=done.mode==='mock'?'MOCK COMPLETE':'SPRINT COMPLETE';if(done.mode==='mock'){var above=done.ok>=120;E('rmsg').textContent=above?'120点以上です。次は苦手を短くつぶします。':'120点未満です。模試で見つかった苦手を短い反復へ戻します。';E('resultThirdLabel').textContent='120点目安';E('resultToday').textContent=above?'以上':'未満';E('resultToday').className=above?'mockscorePass':'mockscoreFail';E('resultAgainLabel').textContent='同じ回を再受験';E('resultAgain').onclick=function(){startMock(done.round);};}else{E('rmsg').textContent=rate>=80?'よく積み上がっています。':rate>=60?'合格につながるペースです。':'苦手が見えた分だけ、次が強くなる。';E('resultThirdLabel').textContent='今日';E('resultToday').textContent=S.today.count+'問';E('resultToday').className='';E('resultAgainLabel').textContent='同じ問題を解く';E('resultAgain').onclick=function(){startSession(done.ids.map(function(id){return QMAP[id];}).filter(Boolean),done.mode,done.label,done.round);};}E('resultWeakBtn').onclick=weakStart;show('result');X=done;}
function todayStart(){startSession(pick(Q,Number(S.goal)||8),'today','今日のスプリント',0);}
function weakStart(){var ids=Object.keys(S.weak),arr=[];for(var i=0;i<ids.length;i++)if(QMAP[ids[i]])arr.push(QMAP[ids[i]]);if(!arr.length){toast('現在の苦手はありません');return;}arr.sort(function(a,b){return(Number(S.weak[b.id].n)||0)-(Number(S.weak[a.id].n)||0);});if(S.shuffleQ)arr=shuffle(arr);startSession(arr.slice(0,Number(S.goal)||8),'weak','苦手復習',0);}
function renderMock(){var root=E('mockRounds');root.innerHTML='';[1,2,3].forEach(function(r){var arr=Q.filter(function(q){return qRound(q)===r;}),seen=arr.filter(function(q){return !!S.seen[q.id];}).length,complete=Number(S.mockComp[r])||0,d=document.createElement('section');d.className='mockround';d.innerHTML='<div class="mockroundhead"><b>第'+r+'回</b><span>200問</span></div><p>社会・環境16／人体・疾病26／食べ物25／基礎14／応用16／栄養教育13／臨床26／公衆16／給食18／応用力30</p><div class="mockprogress"><span>解答済 '+seen+' / 200</span><span>完答 '+complete+'回</span></div><button class="primary"><span><small>本番形式</small><b>第'+r+'回 200問を開始</b></span><span class="arrow">→</span></button>';d.querySelector('button').onclick=function(){startMock(r);};root.appendChild(d);});}
function renderHistory(){var h=S.hist,ok=0;for(var i=0;i<h.length;i++)if(h[i].ok)ok++;E('histTotal').textContent=h.length;E('histRate').textContent=h.length?Math.round(ok/h.length*100)+'%':'—';E('histWeak').textContent=Object.keys(S.weak).length;var mastery=Math.min(100,Math.round(Object.keys(S.seen).length/600*100));E('mastery').textContent=mastery+'%';E('donut').style.setProperty('--p',mastery);var rs=E('roundStats');rs.innerHTML='';[1,2,3].forEach(function(r){var arr=Q.filter(function(q){return qRound(q)===r;}),seen=arr.filter(function(q){return !!S.seen[q.id];}).length,p=Math.round(seen/200*100),row=document.createElement('div');row.className='roundstat';row.style.setProperty('--w',p+'%');row.innerHTML='<div><b>第'+r+'回</b><span>'+seen+' / 200問</span></div><i></i><small>模試完答 '+(Number(S.mockComp[r])||0)+'回</small>';rs.appendChild(row);});var bars=E('bars');bars.innerHTML='';C.forEach(function(c){var a=h.filter(function(x){return x.c===c;}),co=a.filter(function(x){return x.ok;}).length,p=a.length?Math.round(co/a.length*100):0,d=document.createElement('div');d.className='barrow';d.innerHTML='<div><span>'+esc(c)+'</span><b>'+(a.length?p+'%':'未学習')+'</b></div><i><u style="width:'+p+'%"></u></i>';bars.appendChild(d);});renderHeatmap();var wl=E('weakList'),wids=Object.keys(S.weak);wl.innerHTML='';if(!wids.length)wl.innerHTML='<div class="empty">苦手はありません。いい状態です。</div>';else{wids.sort(function(a,b){return(Number(S.weak[b].n)||0)-(Number(S.weak[a].n)||0);});wids.forEach(function(id){var q=QMAP[id];if(!q)return;var wr=document.createElement('button');wr.className='weakrow';wr.innerHTML='<span><b>第'+qRound(q)+'回｜'+esc(q.c)+'</b><small>'+esc(q.m)+'</small></span><em>'+(S.weak[id].st||0)+'/3</em>';wr.onclick=function(){startSession([q],'weak',q.c,qRound(q));};wl.appendChild(wr);});}}
function renderHeatmap(){var hm=E('heatmap');hm.innerHTML='';var counts={};S.hist.forEach(function(h){var k=dateKey(new Date(h.ts||Date.now()));counts[k]=(counts[k]||0)+1;});var now=new Date();now.setHours(0,0,0,0);for(var n=34;n>=0;n--){var d=new Date(now.getTime()-n*86400000),k=dateKey(d),c=counts[k]||0,lv=c===0?0:c<3?1:c<6?2:c<9?3:4,cell=document.createElement('span');cell.className='heat h'+lv;cell.title=k+' '+c+'問';hm.appendChild(cell);}}
function renderSettings(){document.querySelectorAll('#goalSeg button').forEach(function(b){b.classList.toggle('active',Number(b.getAttribute('data-goal'))===Number(S.goal));});document.querySelectorAll('#fontSeg button').forEach(function(b){b.classList.toggle('active',b.getAttribute('data-font')===S.font);});E('shuffleQ').checked=!!S.shuffleQ;E('shuffleA').checked=!!S.shuffleA;E('examDate').value=S.examDate||'';}
function exportData(){var blob=new Blob([JSON.stringify(S,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='kanrieiyoushi-manabi-sprint-v061.json';document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},500);}
function importData(file){var r=new FileReader();r.onload=function(){try{S=normalize(JSON.parse(r.result));persist();renderSettings();toast('学習データを読み込みました');}catch(e){toast('JSONを読み込めませんでした');}};r.readAsText(file);}
function integrity(){if(Q.length!==600)return'問題数 '+Q.length+' / 600';for(var r=1;r<=3;r++){var rq=Q.filter(function(q){return qRound(q)===r;});if(rq.length!==200)return'第'+r+'回 '+rq.length+' / 200';for(var c in EXPECTED){var n=rq.filter(function(q){return q.c===c;}).length;if(n!==EXPECTED[c])return'第'+r+'回 '+c+' '+n+' / '+EXPECTED[c];}}return'';}
function bind(){E('today').onclick=todayStart;E('resume').onclick=resume;E('weak').onclick=weakStart;E('mockShortcut').onclick=function(){show('mock');};E('quizBack').onclick=function(){show('home');};E('quizHome').onclick=function(){show('home');};E('dont').onclick=function(){answer(null,true);};E('resultHome').onclick=function(){show('home');};document.querySelectorAll('.nav button').forEach(function(b){b.onclick=function(){show(b.getAttribute('data-v'));};});document.querySelectorAll('#roundSeg button').forEach(function(b){b.onclick=function(){S.selectedRound=Number(b.getAttribute('data-round'));persist();};});document.querySelectorAll('#goalSeg button').forEach(function(b){b.onclick=function(){S.goal=Number(b.getAttribute('data-goal'));persist();renderSettings();};});document.querySelectorAll('#fontSeg button').forEach(function(b){b.onclick=function(){S.font=b.getAttribute('data-font');persist();renderSettings();};});E('shuffleQ').onchange=function(){S.shuffleQ=this.checked;persist();};E('shuffleA').onchange=function(){S.shuffleA=this.checked;persist();};E('examDate').onchange=function(){S.examDate=this.value;persist();};E('exportBtn').onclick=exportData;E('importFile').onchange=function(){if(this.files&&this.files[0])importData(this.files[0]);this.value='';};E('resetBtn').onclick=function(){if(confirm('学習データをすべて消去しますか？')){S=fresh();S.today={date:todayKey(),count:0};persist();toast('リセットしました');}};}
load();bind();var err=integrity();refreshHome();show('home');if(err){toast('データ検証FAIL: '+err);E('today').disabled=true;E('weak').disabled=true;}else{document.documentElement.setAttribute('data-app-ready','true');window.KANRI_APP_READY=true;}
if('serviceWorker'in navigator)window.addEventListener('load',function(){navigator.serviceWorker.register('./sw.js?v=061').catch(function(){});});
})();
