@preconcurrency import ARKit
import CoreGraphics
import CoreImage
import Foundation
import ImageIO
import SceneKit
import SwiftUI
import UIKit
import simd

private struct DenseMVSRecord:Codable,Sendable{let filePath:String;let timestamp:TimeInterval;let transform:[[Float]];let intrinsics:[[Float]];let width:Int;let height:Int}
private struct DenseMVSManifest:Codable,Sendable{let schemaVersion:Int;let source:String;let createdAt:Date;let maximumRangeMeters:Float;let frames:[DenseMVSRecord]}
private struct DenseGray:Sendable{let pixels:[UInt8];let width:Int;let height:Int;func sample(_ x:Float,_ y:Float)->Float?{let ix=Int(x.rounded()),iy=Int(y.rounded());guard ix>=0,iy>=0,ix<width,iy<height else{return nil};return Float(pixels[iy*width+ix])}}
private struct DenseMVSFrame:Sendable{let gray:DenseGray;let c2w:simd_float4x4;let w2c:simd_float4x4;let fx:Float;let fy:Float;let cx:Float;let cy:Float;let position:SIMD3<Float>;let forward:SIMD3<Float>}
private struct DenseMVSResult:Sendable{let url:URL;let vertices:Int;let faces:Int;let keyframes:Int}

private enum MeshPlaneSweepMVS {
    static func reconstruct(project:URL,manifest:DenseMVSManifest)throws->DenseMVSResult{
        let records=select(manifest.frames,max:14);let maxPixel=ProcessInfo.processInfo.physicalMemory>=6_000_000_000 ? 224:176
        var frames:[DenseMVSFrame]=[];for r in records{if let f=load(r,project:project,maxPixel:maxPixel){frames.append(f)}};guard frames.count>=5 else{throw err("MVSに必要な有効画像が5枚未満です")}
        let refs=referenceIndices(frames.count,max:6);var vertices:[SIMD3<Float>]=[];var faces:[SIMD3<Int>]=[]
        for ri in refs{let ref=frames[ri],neighbors=neighborIndices(refIndex:ri,frames:frames);guard neighbors.count>=2 else{continue};let stride=2,border=5,cols=max(0,(ref.gray.width-border*2)/stride),rows=max(0,(ref.gray.height-border*2)/stride);guard cols>2&&rows>2 else{continue};var grid=[Int?](repeating:nil,count:cols*rows),depths=[Float](repeating:0,count:cols*rows)
            for gy in 0..<rows{for gx in 0..<cols{let u=Float(border+gx*stride),v=Float(border+gy*stride);guard let refValue=ref.gray.sample(u,v) else{continue};var best=Float.greatestFiniteMagnitude,second=Float.greatestFiniteMagnitude,bestDepth:Float=0;let near:Float=0.12,far=min(max(0.45,manifest.maximumRangeMeters),2.8),steps=30;for di in 0..<steps{let t=Float(di)/Float(steps-1),inv=(1/near)*(1-t)+(1/far)*t,d=1/inv;let world=backproject(u:u,v:v,depth:d,frame:ref);var cost:Float=0;var n=0;for ni in neighbors{if let q=project(world,frame:frames[ni]),let val=frames[ni].gray.sample(q.x,q.y){cost += abs(val-refValue);n+=1}};guard n>=2 else{continue};cost/=Float(n);if cost<best{second=best;best=cost;bestDepth=d}else if cost<second{second=cost}}
                guard bestDepth>0,best<42,second-best>4.5 else{continue};let p=backproject(u:u,v:v,depth:bestDepth,frame:ref);let idx=vertices.count;vertices.append(p);grid[gy*cols+gx]=idx;depths[gy*cols+gx]=bestDepth}}
            func edgeOK(_ a:Int,_ b:Int)->Bool{let da=vertices[a],db=vertices[b],avg=max(0.1,(simd_length(da-ref.position)+simd_length(db-ref.position))/2);return simd_distance(da,db)<max(0.045,avg*0.085)}
            for y in 0..<(rows-1){for x in 0..<(cols-1){let i=y*cols+x;guard let a=grid[i],let b=grid[i+1],let c=grid[i+cols],let d=grid[i+cols+1] else{continue};if edgeOK(a,b)&&edgeOK(a,c)&&edgeOK(b,d)&&edgeOK(c,d){faces.append(.init(a,b,c));faces.append(.init(b,d,c))}}}
        }
        guard vertices.count>=500 && faces.count>=500 else{throw err("MVS対応点が不足しました。模様のある対象をゆっくり全周撮影してください")}
        let out=project.appendingPathComponent("visual-dense-mvs.obj");var s="# Scan Lab ARKit-pose plane-sweep dense MVS\n# keyframes \(refs.count) vertices \(vertices.count) faces \(faces.count)\n";for p in vertices{s+="v \(p.x) \(p.y) \(p.z)\n"};for f in faces{s+="f \(f.x+1) \(f.y+1) \(f.z+1)\n"};try s.write(to:out,atomically:true,encoding:.utf8);return .init(url:out,vertices:vertices.count,faces:faces.count,keyframes:refs.count)
    }
    private static func load(_ r:DenseMVSRecord,project:URL,maxPixel:Int)->DenseMVSFrame?{guard r.transform.count==4,r.transform.allSatisfy({$0.count==4}),r.intrinsics.count==3,r.intrinsics.allSatisfy({$0.count==3}) else{return nil};let u=project.appendingPathComponent(r.filePath);guard let src=CGImageSourceCreateWithURL(u as CFURL,nil),let img=CGImageSourceCreateThumbnailAtIndex(src,0,[kCGImageSourceCreateThumbnailFromImageAlways:true,kCGImageSourceThumbnailMaxPixelSize:maxPixel,kCGImageSourceCreateThumbnailWithTransform:false]as CFDictionary)else{return nil};let w=img.width,h=img.height;var px=[UInt8](repeating:0,count:w*h);guard let ctx=CGContext(data:&px,width:w,height:h,bitsPerComponent:8,bytesPerRow:w,space:CGColorSpaceCreateDeviceGray(),bitmapInfo:CGImageAlphaInfo.none.rawValue)else{return nil};ctx.draw(img,in:CGRect(x:0,y:0,width:w,height:h));let m=mat(r.transform),pos=SIMD3<Float>(m.columns.3.x,m.columns.3.y,m.columns.3.z),fr=SIMD3<Float>(-m.columns.2.x,-m.columns.2.y,-m.columns.2.z),f=simd_length_squared(fr)>1e-8 ? simd_normalize(fr):SIMD3<Float>(0,0,-1),sx=Float(w)/Float(max(1,r.width)),sy=Float(h)/Float(max(1,r.height));return .init(gray:.init(pixels:px,width:w,height:h),c2w:m,w2c:simd_inverse(m),fx:r.intrinsics[0][0]*sx,fy:r.intrinsics[1][1]*sy,cx:r.intrinsics[0][2]*sx,cy:r.intrinsics[1][2]*sy,position:pos,forward:f)}
    private static func select(_ f:[DenseMVSRecord],max:Int)->[DenseMVSRecord]{guard f.count>max else{return f};return (0..<max).map{f[Int((Double($0)*Double(f.count-1)/Double(max-1)).rounded())]}}
    private static func referenceIndices(_ n:Int,max:Int)->[Int]{let c=min(max,n);return (0..<c).map{Int((Double($0)*Double(n-1)/Double(max(1,c-1))).rounded())}}
    private static func neighborIndices(refIndex:Int,frames:[DenseMVSFrame])->[Int]{let r=frames[refIndex];return frames.indices.filter{$0 != refIndex}.compactMap{i->(Int,Float)? in let b=simd_distance(r.position,frames[i].position),dot=simd_dot(r.forward,frames[i].forward);guard b>=0.025,b<=0.75,dot>0.50 else{return nil};return(i,abs(b-0.16)+(1-dot)*0.12)}.sorted{$0.1<$1.1}.prefix(4).map{$0.0}}
    private static func backproject(u:Float,v:Float,depth:Float,frame:DenseMVSFrame)->SIMD3<Float>{let x=(u-frame.cx)/frame.fx*depth,y=-(v-frame.cy)/frame.fy*depth,c=SIMD4<Float>(x,y,-depth,1),w=frame.c2w*c;return .init(w.x,w.y,w.z)}
    private static func project(_ p:SIMD3<Float>,frame:DenseMVSFrame)->SIMD2<Float>?{let c=frame.w2c*SIMD4<Float>(p.x,p.y,p.z,1),d=-c.z;guard d>0.05 else{return nil};let x=frame.cx+frame.fx*c.x/d,y=frame.cy-frame.fy*c.y/d;guard x>=2,y>=2,x<Float(frame.gray.width-2),y<Float(frame.gray.height-2) else{return nil};return .init(x,y)}
    private static func mat(_ r:[[Float]])->simd_float4x4{simd_float4x4(columns:(.init(r[0][0],r[1][0],r[2][0],r[3][0]),.init(r[0][1],r[1][1],r[2][1],r[3][1]),.init(r[0][2],r[1][2],r[2][2],r[3][2]),.init(r[0][3],r[1][3],r[2][3],r[3][3])))}
    private static func err(_ s:String)->NSError{NSError(domain:"ScanLab.DenseMVS",code:1,userInfo:[NSLocalizedDescriptionKey:s])}
}

@MainActor
final class MeshDenseVisualRecorder:ObservableObject{
    private var project:URL?,images:URL?;private var frames:[DenseMVSRecord]=[];private var last:TimeInterval = -.greatestFiniteMagnitude;private let ci=CIContext(options:[.cacheIntermediates:false]);private var maximumRange:Float=2.75
    var isRecording:Bool{project != nil};var frameCount:Int{frames.count};var canFinish:Bool{frames.count>=30}
    func start(size:MeshScanSize)throws{discard();maximumRange=size.maximumRangeMeters;let docs=FileManager.default.urls(for:.documentDirectory,in:.userDomainMask)[0],root=docs.appendingPathComponent("SplatLab",isDirectory:true);try FileManager.default.createDirectory(at:root,withIntermediateDirectories:true);let p=root.appendingPathComponent(UUID().uuidString+".meshproject",isDirectory:true),im=p.appendingPathComponent("images",isDirectory:true);try FileManager.default.createDirectory(at:im,withIntermediateDirectories:true);project=p;images=im;frames=[];last = -.greatestFiniteMagnitude}
    func record(_ frame:ARFrame){guard case .normal=frame.camera.trackingState,frame.timestamp-last>=0.42,let images else{return};let image=CIImage(cvPixelBuffer:frame.capturedImage);guard let cg=ci.createCGImage(image,from:image.extent),let jpg=UIImage(cgImage:cg).jpegData(compressionQuality:0.92)else{return};let name=String(format:"mvs_%05d.jpg",frames.count),url=images.appendingPathComponent(name);do{try jpg.write(to:url,options:.atomic);let r=frame.camera.imageResolution;frames.append(.init(filePath:"images/\(name)",timestamp:frame.timestamp,transform:rows(frame.camera.transform),intrinsics:rows3(frame.camera.intrinsics),width:Int(r.width),height:Int(r.height)));last=frame.timestamp}catch{try? FileManager.default.removeItem(at:url)}}
    func finish(model:MeshScanModel)async{guard let project else{model.phase = .failed("MVS保存先がありません");return};let manifest=DenseMVSManifest(schemaVersion:2,source:"ARKit pose-guided plane-sweep MVS",createdAt:Date(),maximumRangeMeters:maximumRange,frames:frames);do{let enc=JSONEncoder();enc.outputFormatting=[.prettyPrinted,.sortedKeys];enc.dateEncodingStrategy = .iso8601;try enc.encode(manifest).write(to:project.appendingPathComponent("mesh-project.json"),options:.atomic)}catch{model.phase = .failed("MVS raw索引保存失敗: \(error.localizedDescription)");return};model.phase = .reconstructing;model.reconstructionProgress=0.18;model.statusMessage="既知のARKit姿勢を使って画像間対応を探索し、高密度Depthを再構築しています";do{let r=try await Task.detached(priority:.userInitiated){try MeshPlaneSweepMVS.reconstruct(project:project,manifest:manifest)}.value;model.rawOBJURL=r.url;model.resultURL=r.url;model.previewScene=try? SCNScene(url:r.url,options:nil);model.vertexCount=r.vertices;model.faceCount=r.faces;model.reconstructionProgress=1;model.phase = .finished;model.statusMessage="非LiDAR dense MVS：\(r.keyframes)視点から\(r.faces.formatted())面を生成";release()}catch{model.phase = .failed("非LiDAR dense MVSに失敗: \(error.localizedDescription)")}}
    func discard(){if let project{try? FileManager.default.removeItem(at:project)};release()};private func release(){project=nil;images=nil;frames=[];last = -.greatestFiniteMagnitude}
    private func rows(_ m:simd_float4x4)->[[Float]]{(0..<4).map{r in(0..<4).map{c in m[c][r]}}};private func rows3(_ m:simd_float3x3)->[[Float]]{(0..<3).map{r in(0..<3).map{c in m[c][r]}}}
}

@MainActor
struct MeshDenseVisualFallbackOverlay:View{
    @EnvironmentObject var model:MeshScanModel;@StateObject private var recorder=MeshDenseVisualRecorder();private var needed:Bool{!model.supportsLiDARMesh && !model.supportsPhotogrammetry}
    var body:some View{ZStack{if needed && model.phase == .ready{VStack{Spacer();VStack(spacing:10){Text("非LiDAR Dense Mesh").font(.headline);Text("ARKitの実カメラ姿勢を固定し、複数画像のplane-sweep stereoでDepthを推定します。特徴点ボクセルだけの旧経路より高密度です。").font(.caption).foregroundStyle(.secondary).multilineTextAlignment(.center);Button("Dense Meshを開始"){start()}.buttonStyle(PrimaryButtonStyle())}.padding(16).background(.black.opacity(0.95),in:RoundedRectangle(cornerRadius:20)).padding(.horizontal,18).padding(.bottom,24)}};if needed && recorder.isRecording && model.phase == .scanning{VStack{Spacer();VStack(spacing:9){Text("非LiDAR Dense撮影中").font(.subheadline.bold());Text("写真 \(recorder.frameCount) / 30+").monospacedDigit();Text(recorder.canFinish ? "生成可能。細部用に上下・斜めも追加すると有利です":"対象の全周を、重なりを保ちながらゆっくり撮影してください").font(.caption).foregroundStyle(.secondary).multilineTextAlignment(.center);if recorder.canFinish{Button("Dense Meshを生成"){model.session?.pause();Task{await recorder.finish(model:model)}}.buttonStyle(PrimaryButtonStyle())}}.padding(16).background(.black.opacity(0.95),in:RoundedRectangle(cornerRadius:20)).padding(.horizontal,14).padding(.bottom,12)}}}.task(id:model.phase){guard needed,model.phase == .scanning,recorder.isRecording else{return};while !Task.isCancelled && model.phase == .scanning && recorder.isRecording{if let f=model.session?.currentFrame{recorder.record(f);model.frameCount=recorder.frameCount;model.statusMessage=recorder.canFinish ? "Dense MVS生成可能":"Dense MVS用RGB＋pose収集中"};try? await Task.sleep(for:.milliseconds(220))}}.onChange(of:model.phase){_,p in if p == .ready && recorder.isRecording{recorder.discard()}}}
    private func start(){guard ARWorldTrackingConfiguration.isSupported,let s=model.session else{model.phase = .failed("ARKit World Tracking非対応です");return};do{try recorder.start(size:model.scanSize)}catch{model.phase = .failed("Dense MVS保存準備失敗: \(error.localizedDescription)");return};model.mode = .photogrammetry;model.frameCount=0;model.vertexCount=0;model.faceCount=0;model.resultURL=nil;model.rawOBJURL=nil;model.previewScene=nil;model.phase = .scanning;let c=ARWorldTrackingConfiguration();c.worldAlignment = .gravity;c.isLightEstimationEnabled=true;c.environmentTexturing = .automatic;c.planeDetection=[.horizontal,.vertical];s.run(c,options:[.resetTracking,.removeExistingAnchors])}
}
