import CoreGraphics
import Foundation
import ImageIO

/// Point-cloud export surface matching Scaniverse's PLY/LAS semantics.
///
/// S4's textured OBJ stores one UV per face corner and a `map_Kd` texture atlas.
/// When that real texture data is present, this exporter emits one colored point per
/// face corner so seams/thin structures keep their captured RGB instead of collapsing
/// to an arbitrary color per shared geometry vertex. If no real texture/vertex color
/// exists, coordinates are still exported but color fields are omitted rather than invented.
enum MeshPointCloudExportService {
    enum ExportError: LocalizedError {
        case emptyGeometry
        case invalidOBJ
        case pointCountOverflow(Int)
        case cannotCreateOutput
        case invalidTexture

        var errorDescription: String? {
            switch self {
            case .emptyGeometry:
                return "点群へ変換できるMesh頂点がありません。"
            case .invalidOBJ:
                return "MeshのOBJ構造を点群として読み込めません。"
            case .pointCountOverflow(let count):
                return "LAS 1.2で扱える点数を超えています（\(count)点）。"
            case .cannotCreateOutput:
                return "点群ファイルを作成できません。"
            case .invalidTexture:
                return "Meshの実テクスチャを読み込めません。"
            }
        }
    }

    private struct VertexColor: Equatable {
        let red: UInt16
        let green: UInt16
        let blue: UInt16
    }

    private struct Vertex {
        let x: Double
        let y: Double
        let z: Double
        let color: VertexColor?
    }

    private struct TexCoord {
        let u: Double
        let v: Double
    }

    private struct Corner {
        let vertex: Int
        let texCoord: Int?
    }

    private struct Triangle {
        let a: Corner
        let b: Corner
        let c: Corner

        var corners: [Corner] { [a, b, c] }
    }

    private struct Geometry {
        let vertices: [Vertex]
        let texCoords: [TexCoord]
        let triangles: [Triangle]
        let materialLibrary: String?
    }

    private enum PointPlan {
        case texturedCorners(TextureSampler)
        case coloredVertices
        case vertices

        func pointCount(for geometry: Geometry) -> Int {
            switch self {
            case .texturedCorners:
                let multiplied = geometry.triangles.count.multipliedReportingOverflow(by: 3)
                return multiplied.overflow ? Int.max : multiplied.partialValue
            case .coloredVertices, .vertices:
                return geometry.vertices.count
            }
        }

        var includesColor: Bool {
            switch self {
            case .texturedCorners, .coloredVertices: return true
            case .vertices: return false
            }
        }
    }

    private struct LASAxis {
        let scale: Double
        let offset: Double
    }

    private struct TextureSampler {
        let width: Int
        let height: Int
        let rgba: Data

        func color(at texCoord: TexCoord) -> VertexColor {
            let u = min(1, max(0, texCoord.u))
            let v = min(1, max(0, texCoord.v))
            let x = min(width - 1, max(0, Int((u * Double(width - 1)).rounded())))
            // OBJ UV uses a bottom-left V origin. The sampler buffer is rendered into
            // top-left row order, so invert V here exactly once.
            let y = min(height - 1, max(0, Int(((1 - v) * Double(height - 1)).rounded())))
            let offset = (y * width + x) * 4
            return rgba.withUnsafeBytes { raw in
                let bytes = raw.bindMemory(to: UInt8.self)
                return VertexColor(
                    red: UInt16(bytes[offset]) * 257,
                    green: UInt16(bytes[offset + 1]) * 257,
                    blue: UInt16(bytes[offset + 2]) * 257
                )
            }
        }
    }

    private static let las12HeaderSize = 227
    private static let streamFlushThreshold = 64 * 1024
    private static let maxTextureSampleDimension = 4_096

    static func exportPLY(sourceOBJ: URL, outputURL: URL) throws {
        try Task.checkCancellation()
        let geometry = try parseOBJ(sourceOBJ)
        guard !geometry.vertices.isEmpty else { throw ExportError.emptyGeometry }
        let plan = try pointPlan(for: geometry, sourceOBJ: sourceOBJ)
        let pointCount = plan.pointCount(for: geometry)
        guard pointCount > 0, pointCount != Int.max else { throw ExportError.pointCountOverflow(pointCount) }

        var header = """
        ply
        format binary_little_endian 1.0
        comment Generated by Scan Lab Native from captured Mesh data
        element vertex \(pointCount)
        property float x
        property float y
        property float z
        """
        if plan.includesColor {
            header += "\nproperty uchar red\nproperty uchar green\nproperty uchar blue"
        }
        header += "\nend_header\n"

        try? FileManager.default.removeItem(at: outputURL)
        guard FileManager.default.createFile(atPath: outputURL.path, contents: nil) else {
            throw ExportError.cannotCreateOutput
        }

        let handle = try FileHandle(forWritingTo: outputURL)
        do {
            try handle.write(contentsOf: Data(header.utf8))
            var buffer = Data()
            buffer.reserveCapacity(streamFlushThreshold + 64)
            var emitted = 0

            try forEachPoint(geometry: geometry, plan: plan) { vertex, color in
                if emitted % 4_096 == 0 { try Task.checkCancellation() }
                appendFloat32(Float(vertex.x), to: &buffer)
                appendFloat32(Float(vertex.y), to: &buffer)
                appendFloat32(Float(vertex.z), to: &buffer)
                if plan.includesColor, let color {
                    buffer.append(UInt8(color.red / 257))
                    buffer.append(UInt8(color.green / 257))
                    buffer.append(UInt8(color.blue / 257))
                }
                emitted += 1
                try flushIfNeeded(&buffer, to: handle)
            }

            guard emitted == pointCount else { throw ExportError.invalidOBJ }
            if !buffer.isEmpty { try handle.write(contentsOf: buffer) }
            try handle.close()
        } catch {
            try? handle.close()
            throw error
        }
    }

    /// Writes local-coordinate LAS 1.2 point records. No georeferencing is fabricated:
    /// S0 may add CRS/GPS metadata later only when a trusted capture-location contract exists.
    static func exportLAS12(sourceOBJ: URL, outputURL: URL) throws {
        try Task.checkCancellation()
        let geometry = try parseOBJ(sourceOBJ)
        guard !geometry.vertices.isEmpty else { throw ExportError.emptyGeometry }
        let plan = try pointPlan(for: geometry, sourceOBJ: sourceOBJ)
        let pointCount = plan.pointCount(for: geometry)
        guard pointCount > 0, pointCount <= Int(UInt32.max) else {
            throw ExportError.pointCountOverflow(pointCount)
        }

        let minX = geometry.vertices.map(\.x).min() ?? 0
        let maxX = geometry.vertices.map(\.x).max() ?? 0
        let minY = geometry.vertices.map(\.y).min() ?? 0
        let maxY = geometry.vertices.map(\.y).max() ?? 0
        let minZ = geometry.vertices.map(\.z).min() ?? 0
        let maxZ = geometry.vertices.map(\.z).max() ?? 0
        let xAxis = lasAxis(minimum: minX, maximum: maxX)
        let yAxis = lasAxis(minimum: minY, maximum: maxY)
        let zAxis = lasAxis(minimum: minZ, maximum: maxZ)

        let recordFormat: UInt8 = plan.includesColor ? 2 : 0
        let recordLength: UInt16 = plan.includesColor ? 26 : 20
        let legacyPointCount = UInt32(pointCount)
        let header = makeLAS12Header(
            pointCount: legacyPointCount,
            pointFormat: recordFormat,
            recordLength: recordLength,
            xAxis: xAxis,
            yAxis: yAxis,
            zAxis: zAxis,
            minX: minX,
            maxX: maxX,
            minY: minY,
            maxY: maxY,
            minZ: minZ,
            maxZ: maxZ
        )
        guard header.count == las12HeaderSize else { throw ExportError.invalidOBJ }

        try? FileManager.default.removeItem(at: outputURL)
        guard FileManager.default.createFile(atPath: outputURL.path, contents: nil) else {
            throw ExportError.cannotCreateOutput
        }

        let handle = try FileHandle(forWritingTo: outputURL)
        do {
            try handle.write(contentsOf: header)
            var buffer = Data()
            buffer.reserveCapacity(streamFlushThreshold + 64)
            var emitted = 0

            try forEachPoint(geometry: geometry, plan: plan) { vertex, color in
                if emitted % 4_096 == 0 { try Task.checkCancellation() }
                appendLittleEndian(quantize(vertex.x, axis: xAxis), to: &buffer)
                appendLittleEndian(quantize(vertex.y, axis: yAxis), to: &buffer)
                appendLittleEndian(quantize(vertex.z, axis: zAxis), to: &buffer)
                appendLittleEndian(UInt16(0), to: &buffer) // intensity
                buffer.append(0x09) // return 1 of 1
                buffer.append(0) // classification
                buffer.append(0) // scan angle rank
                buffer.append(0) // user data
                appendLittleEndian(UInt16(0), to: &buffer) // point source ID
                if plan.includesColor, let color {
                    appendLittleEndian(color.red, to: &buffer)
                    appendLittleEndian(color.green, to: &buffer)
                    appendLittleEndian(color.blue, to: &buffer)
                }
                emitted += 1
                try flushIfNeeded(&buffer, to: handle)
            }

            guard emitted == pointCount else { throw ExportError.invalidOBJ }
            if !buffer.isEmpty { try handle.write(contentsOf: buffer) }
            try handle.close()
        } catch {
            try? handle.close()
            throw error
        }
    }

    private static func pointPlan(for geometry: Geometry, sourceOBJ: URL) throws -> PointPlan {
        let hasCompleteInlineColor = !geometry.vertices.isEmpty && geometry.vertices.allSatisfy { $0.color != nil }
        let allCornersHaveUV = !geometry.triangles.isEmpty && geometry.triangles.allSatisfy { triangle in
            triangle.corners.allSatisfy { corner in
                guard let index = corner.texCoord else { return false }
                return index >= 0 && index < geometry.texCoords.count
            }
        }

        if allCornersHaveUV,
           let textureURL = textureURL(for: geometry, sourceOBJ: sourceOBJ),
           let sampler = try loadTextureSampler(textureURL) {
            return .texturedCorners(sampler)
        }
        if hasCompleteInlineColor { return .coloredVertices }
        return .vertices
    }

    private static func forEachPoint(
        geometry: Geometry,
        plan: PointPlan,
        body: (Vertex, VertexColor?) throws -> Void
    ) throws {
        switch plan {
        case .vertices:
            for vertex in geometry.vertices { try body(vertex, nil) }
        case .coloredVertices:
            for vertex in geometry.vertices { try body(vertex, vertex.color) }
        case .texturedCorners(let sampler):
            for triangle in geometry.triangles {
                for corner in triangle.corners {
                    guard corner.vertex >= 0, corner.vertex < geometry.vertices.count,
                          let textureIndex = corner.texCoord,
                          textureIndex >= 0, textureIndex < geometry.texCoords.count else {
                        throw ExportError.invalidOBJ
                    }
                    let vertex = geometry.vertices[corner.vertex]
                    let color = sampler.color(at: geometry.texCoords[textureIndex])
                    try body(vertex, color)
                }
            }
        }
    }

    private static func parseOBJ(_ url: URL) throws -> Geometry {
        let data = try Data(contentsOf: url, options: [.mappedIfSafe])
        guard !data.isEmpty else { throw ExportError.invalidOBJ }
        let text = String(decoding: data, as: UTF8.self)
        var vertices: [Vertex] = []
        var texCoords: [TexCoord] = []
        var triangles: [Triangle] = []
        var materialLibrary: String?
        vertices.reserveCapacity(max(128, data.count / 80))

        text.enumerateLines { line, _ in
            let trimmed = line.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty, !trimmed.hasPrefix("#") else { return }

            if trimmed.hasPrefix("mtllib "), materialLibrary == nil {
                let value = trimmed.dropFirst("mtllib ".count).trimmingCharacters(in: .whitespacesAndNewlines)
                if !value.isEmpty { materialLibrary = unquote(value) }
                return
            }

            let fields = trimmed.split(whereSeparator: { $0.isWhitespace })
            guard let kind = fields.first else { return }

            if kind == "v", fields.count >= 4,
               let x = Double(fields[1]), let y = Double(fields[2]), let z = Double(fields[3]),
               x.isFinite, y.isFinite, z.isFinite {
                var color: VertexColor?
                if fields.count >= 7,
                   let red = Double(fields[4]), let green = Double(fields[5]), let blue = Double(fields[6]),
                   red.isFinite, green.isFinite, blue.isFinite {
                    color = normalizedVertexColor(red: red, green: green, blue: blue)
                }
                vertices.append(Vertex(x: x, y: y, z: z, color: color))
                return
            }

            if kind == "vt", fields.count >= 3,
               let u = Double(fields[1]), let v = Double(fields[2]), u.isFinite, v.isFinite {
                texCoords.append(TexCoord(u: u, v: v))
                return
            }

            guard kind == "f", fields.count >= 4 else { return }
            var corners: [Corner] = []
            corners.reserveCapacity(fields.count - 1)
            for token in fields.dropFirst() {
                let pieces = token.split(separator: "/", omittingEmptySubsequences: false)
                guard let vertexPiece = pieces.first,
                      let rawVertex = Int(vertexPiece),
                      let vertexIndex = resolveOBJIndex(rawVertex, count: vertices.count) else {
                    corners.removeAll()
                    break
                }
                var textureIndex: Int?
                if pieces.count >= 2, !pieces[1].isEmpty, let rawTexture = Int(pieces[1]) {
                    textureIndex = resolveOBJIndex(rawTexture, count: texCoords.count)
                }
                corners.append(Corner(vertex: vertexIndex, texCoord: textureIndex))
            }
            guard corners.count >= 3 else { return }
            for index in 1..<(corners.count - 1) {
                triangles.append(Triangle(a: corners[0], b: corners[index], c: corners[index + 1]))
            }
        }

        guard !vertices.isEmpty else { throw ExportError.emptyGeometry }
        return Geometry(
            vertices: vertices,
            texCoords: texCoords,
            triangles: triangles,
            materialLibrary: materialLibrary
        )
    }

    private static func resolveOBJIndex(_ raw: Int, count: Int) -> Int? {
        guard raw != 0 else { return nil }
        let resolved = raw > 0 ? raw - 1 : count + raw
        return resolved >= 0 && resolved < count ? resolved : nil
    }

    private static func textureURL(for geometry: Geometry, sourceOBJ: URL) -> URL? {
        guard let materialLibrary = geometry.materialLibrary else { return nil }
        let mtlURL = sourceOBJ.deletingLastPathComponent().appendingPathComponent(materialLibrary)
        guard let data = try? Data(contentsOf: mtlURL), !data.isEmpty else { return nil }
        let text = String(decoding: data, as: UTF8.self)
        var textureName: String?
        text.enumerateLines { line, stop in
            let trimmed = line.trimmingCharacters(in: .whitespacesAndNewlines)
            if trimmed.hasPrefix("map_Kd ") {
                let value = trimmed.dropFirst("map_Kd ".count).trimmingCharacters(in: .whitespacesAndNewlines)
                if !value.isEmpty {
                    textureName = unquote(value)
                    stop = true
                }
            }
        }
        guard let textureName else { return nil }
        let textureURL = mtlURL.deletingLastPathComponent().appendingPathComponent(textureName)
        return FileManager.default.fileExists(atPath: textureURL.path) ? textureURL : nil
    }

    private static func loadTextureSampler(_ url: URL) throws -> TextureSampler? {
        guard let source = CGImageSourceCreateWithURL(url as CFURL, nil) else {
            throw ExportError.invalidTexture
        }
        let options: [CFString: Any] = [
            kCGImageSourceCreateThumbnailFromImageAlways: true,
            kCGImageSourceCreateThumbnailWithTransform: true,
            kCGImageSourceThumbnailMaxPixelSize: maxTextureSampleDimension,
            kCGImageSourceShouldCacheImmediately: true,
        ]
        guard let image = CGImageSourceCreateThumbnailAtIndex(source, 0, options as CFDictionary) else {
            throw ExportError.invalidTexture
        }
        let width = image.width
        let height = image.height
        guard width > 0, height > 0 else { throw ExportError.invalidTexture }

        let byteCount = width * height * 4
        var rgba = Data(count: byteCount)
        let colorSpace = CGColorSpace(name: CGColorSpace.sRGB) ?? CGColorSpaceCreateDeviceRGB()
        let drewImage = rgba.withUnsafeMutableBytes { raw -> Bool in
            guard let baseAddress = raw.baseAddress,
                  let context = CGContext(
                    data: baseAddress,
                    width: width,
                    height: height,
                    bitsPerComponent: 8,
                    bytesPerRow: width * 4,
                    space: colorSpace,
                    bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue | CGBitmapInfo.byteOrder32Big.rawValue
                  ) else { return false }
            // Store rows top-to-bottom so sampling can use y = (1 - v).
            context.translateBy(x: 0, y: CGFloat(height))
            context.scaleBy(x: 1, y: -1)
            context.draw(image, in: CGRect(x: 0, y: 0, width: width, height: height))
            return true
        }
        guard drewImage else { throw ExportError.invalidTexture }
        return TextureSampler(width: width, height: height, rgba: rgba)
    }

    private static func normalizedVertexColor(red: Double, green: Double, blue: Double) -> VertexColor {
        let values = [red, green, blue]
        let unitRange = values.allSatisfy { $0 >= 0 && $0 <= 1 }
        let byteRange = values.allSatisfy { $0 >= 0 && $0 <= 255 }
        let multiplier: Double = unitRange ? 65_535 : (byteRange ? 257 : 1)
        func convert(_ value: Double) -> UInt16 {
            UInt16(clamping: Int((value * multiplier).rounded()))
        }
        return VertexColor(red: convert(red), green: convert(green), blue: convert(blue))
    }

    private static func makeLAS12Header(
        pointCount: UInt32,
        pointFormat: UInt8,
        recordLength: UInt16,
        xAxis: LASAxis,
        yAxis: LASAxis,
        zAxis: LASAxis,
        minX: Double,
        maxX: Double,
        minY: Double,
        maxY: Double,
        minZ: Double,
        maxZ: Double
    ) -> Data {
        var header = Data()
        header.reserveCapacity(las12HeaderSize)
        header.append(contentsOf: [0x4c, 0x41, 0x53, 0x46]) // LASF
        appendLittleEndian(UInt16(0), to: &header) // File Source ID
        appendLittleEndian(UInt16(0), to: &header) // Global Encoding: no fake CRS/GPS time
        header.append(Data(repeating: 0, count: 16)) // Project ID GUID
        header.append(1)
        header.append(2)
        appendFixedASCII("Scan Lab Point Cloud", width: 32, to: &header)
        appendFixedASCII("Scan Lab Native", width: 32, to: &header)

        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = TimeZone(secondsFromGMT: 0) ?? .current
        let now = Date()
        appendLittleEndian(UInt16(calendar.ordinality(of: .day, in: .year, for: now) ?? 0), to: &header)
        appendLittleEndian(UInt16(calendar.component(.year, from: now)), to: &header)
        appendLittleEndian(UInt16(las12HeaderSize), to: &header)
        appendLittleEndian(UInt32(las12HeaderSize), to: &header)
        appendLittleEndian(UInt32(0), to: &header) // VLR count
        header.append(pointFormat)
        appendLittleEndian(recordLength, to: &header)
        appendLittleEndian(pointCount, to: &header)
        appendLittleEndian(pointCount, to: &header) // points by return 1
        for _ in 0..<4 { appendLittleEndian(UInt32(0), to: &header) }
        appendFloat64(xAxis.scale, to: &header)
        appendFloat64(yAxis.scale, to: &header)
        appendFloat64(zAxis.scale, to: &header)
        appendFloat64(xAxis.offset, to: &header)
        appendFloat64(yAxis.offset, to: &header)
        appendFloat64(zAxis.offset, to: &header)
        appendFloat64(maxX, to: &header)
        appendFloat64(minX, to: &header)
        appendFloat64(maxY, to: &header)
        appendFloat64(minY, to: &header)
        appendFloat64(maxZ, to: &header)
        appendFloat64(minZ, to: &header)
        return header
    }

    private static func lasAxis(minimum: Double, maximum: Double) -> LASAxis {
        let offset = (minimum + maximum) / 2
        let halfSpan = max(abs(maximum - offset), abs(minimum - offset))
        let safeIntegerRange = Double(Int32.max) - 4_096
        let scale = max(0.000_001, halfSpan / max(1, safeIntegerRange))
        return LASAxis(scale: scale, offset: offset)
    }

    private static func quantize(_ value: Double, axis: LASAxis) -> Int32 {
        let raw = ((value - axis.offset) / axis.scale).rounded()
        if raw <= Double(Int32.min) { return Int32.min }
        if raw >= Double(Int32.max) { return Int32.max }
        return Int32(raw)
    }

    private static func flushIfNeeded(_ buffer: inout Data, to handle: FileHandle) throws {
        guard buffer.count >= streamFlushThreshold else { return }
        try handle.write(contentsOf: buffer)
        buffer.removeAll(keepingCapacity: true)
    }

    private static func appendLittleEndian<T: FixedWidthInteger>(_ value: T, to data: inout Data) {
        var littleEndian = value.littleEndian
        withUnsafeBytes(of: &littleEndian) { data.append(contentsOf: $0) }
    }

    private static func appendFloat32(_ value: Float, to data: inout Data) {
        appendLittleEndian(value.bitPattern, to: &data)
    }

    private static func appendFloat64(_ value: Double, to data: inout Data) {
        appendLittleEndian(value.bitPattern, to: &data)
    }

    private static func appendFixedASCII(_ value: String, width: Int, to data: inout Data) {
        let bytes = Array(value.utf8.prefix(width))
        data.append(contentsOf: bytes)
        if bytes.count < width {
            data.append(Data(repeating: 0, count: width - bytes.count))
        }
    }

    private static func unquote(_ value: String) -> String {
        guard value.count >= 2,
              let first = value.first,
              let last = value.last,
              (first == "\"" && last == "\"") || (first == "'" && last == "'") else {
            return value
        }
        return String(value.dropFirst().dropLast())
    }
}
