import CoreGraphics
import Foundation
import ImageIO

/// Point-cloud export surface matching Scaniverse's PLY/LAS semantics.
/// Textured OBJ input is sampled at face corners so UV seams and thin structures preserve
/// captured RGB instead of collapsing to an arbitrary shared-vertex color.
enum MeshPointCloudExportService {
    enum ExportError: LocalizedError {
        case emptyGeometry
        case invalidOBJ
        case pointCountOverflow(Int)
        case cannotCreateOutput
        case invalidTexture

        var errorDescription: String? {
            switch self {
            case .emptyGeometry: return "点群へ変換できるMesh頂点がありません。"
            case .invalidOBJ: return "MeshのOBJ構造を点群として読み込めません。"
            case .pointCountOverflow(let count): return "LAS 1.2で扱える点数を超えています（\(count)点）。"
            case .cannotCreateOutput: return "点群ファイルを作成できません。"
            case .invalidTexture: return "Meshの実テクスチャを読み込めません。"
            }
        }
    }

    private struct VertexColor: Equatable {
        let red: UInt16
        let green: UInt16
        let blue: UInt16
    }

    private struct Vertex {
        let x: Double
        let y: Double
        let z: Double
        let color: VertexColor?
    }

    private struct TexCoord {
        let u: Double
        let v: Double
    }

    private struct Corner {
        let vertex: Int
        let texCoord: Int?
    }

    private struct Triangle {
        let a: Corner
        let b: Corner
        let c: Corner
        let material: String?
        var corners: [Corner] { [a, b, c] }
    }

    private struct Geometry {
        let vertices: [Vertex]
        let texCoords: [TexCoord]
        let triangles: [Triangle]
        let materialLibraries: [String]
    }

    private struct Bounds {
        var minX: Double
        var maxX: Double
        var minY: Double
        var maxY: Double
        var minZ: Double
        var maxZ: Double
    }

    private struct MaterialTextureSet {
        let byMaterial: [String: TextureSampler]
        let fallback: TextureSampler?

        func sampler(for material: String?) -> TextureSampler? {
            if let material, let sampler = byMaterial[material] { return sampler }
            return fallback
        }
    }

    private enum PointPlan {
        case texturedCorners(MaterialTextureSet)
        case coloredVertices
        case vertices

        func pointCount(for geometry: Geometry) -> Int {
            switch self {
            case .texturedCorners:
                let value = geometry.triangles.count.multipliedReportingOverflow(by: 3)
                return value.overflow ? Int.max : value.partialValue
            case .coloredVertices, .vertices:
                return geometry.vertices.count
            }
        }

        var includesColor: Bool {
            switch self {
            case .texturedCorners, .coloredVertices: return true
            case .vertices: return false
            }
        }
    }

    private struct LASAxis {
        let scale: Double
        let offset: Double
    }

    private struct TextureSampler {
        let width: Int
        let height: Int
        let rgba: Data

        func color(at texCoord: TexCoord) -> VertexColor {
            let u = min(1, max(0, texCoord.u))
            let v = min(1, max(0, texCoord.v))
            let x = min(width - 1, max(0, Int((u * Double(width - 1)).rounded())))
            let y = min(height - 1, max(0, Int(((1 - v) * Double(height - 1)).rounded())))
            let offset = (y * width + x) * 4
            return rgba.withUnsafeBytes { raw in
                let bytes = raw.bindMemory(to: UInt8.self)
                return VertexColor(
                    red: UInt16(bytes[offset]) * 257,
                    green: UInt16(bytes[offset + 1]) * 257,
                    blue: UInt16(bytes[offset + 2]) * 257
                )
            }
        }
    }

    private static let las12HeaderSize = 227
    private static let streamFlushThreshold = 64 * 1024
    private static let maxTextureSampleDimension = 4_096

    static func exportPLY(sourceOBJ: URL, outputURL: URL) throws {
        try Task.checkCancellation()
        let geometry = try parseOBJ(sourceOBJ)
        guard !geometry.vertices.isEmpty else { throw ExportError.emptyGeometry }
        let plan = try pointPlan(for: geometry, sourceOBJ: sourceOBJ)
        let pointCount = plan.pointCount(for: geometry)
        guard pointCount > 0, pointCount != Int.max else { throw ExportError.pointCountOverflow(pointCount) }

        var header = """
        ply
        format binary_little_endian 1.0
        comment Generated by Scan Lab Native from captured Mesh data
        element vertex \(pointCount)
        property float x
        property float y
        property float z
        """
        if plan.includesColor {
            header += "\nproperty uchar red\nproperty uchar green\nproperty uchar blue"
        }
        header += "\nend_header\n"

        try? FileManager.default.removeItem(at: outputURL)
        guard FileManager.default.createFile(atPath: outputURL.path, contents: nil) else {
            throw ExportError.cannotCreateOutput
        }

        let handle = try FileHandle(forWritingTo: outputURL)
        do {
            try handle.write(contentsOf: Data(header.utf8))
            var buffer = Data()
            buffer.reserveCapacity(streamFlushThreshold + 64)
            var emitted = 0
            try forEachPoint(geometry: geometry, plan: plan) { vertex, color in
                if emitted % 4_096 == 0 { try Task.checkCancellation() }
                appendFloat32(Float(vertex.x), to: &buffer)
                appendFloat32(Float(vertex.y), to: &buffer)
                appendFloat32(Float(vertex.z), to: &buffer)
                if plan.includesColor, let color {
                    buffer.append(UInt8(color.red / 257))
                    buffer.append(UInt8(color.green / 257))
                    buffer.append(UInt8(color.blue / 257))
                }
                emitted += 1
                try flushIfNeeded(&buffer, to: handle)
            }
            guard emitted == pointCount else { throw ExportError.invalidOBJ }
            if !buffer.isEmpty { try handle.write(contentsOf: buffer) }
            try handle.close()
        } catch {
            try? handle.close()
            throw error
        }
    }

    /// Writes local-coordinate LAS 1.2 records. No georeferencing is fabricated.
    static func exportLAS12(sourceOBJ: URL, outputURL: URL) throws {
        try Task.checkCancellation()
        let geometry = try parseOBJ(sourceOBJ)
        guard !geometry.vertices.isEmpty else { throw ExportError.emptyGeometry }
        let plan = try pointPlan(for: geometry, sourceOBJ: sourceOBJ)
        let pointCount = plan.pointCount(for: geometry)
        guard pointCount > 0, pointCount <= Int(UInt32.max) else {
            throw ExportError.pointCountOverflow(pointCount)
        }

        let bounds = bounds(for: geometry.vertices)
        let xAxis = lasAxis(minimum: bounds.minX, maximum: bounds.maxX)
        let yAxis = lasAxis(minimum: bounds.minY, maximum: bounds.maxY)
        let zAxis = lasAxis(minimum: bounds.minZ, maximum: bounds.maxZ)
        let recordFormat: UInt8 = plan.includesColor ? 2 : 0
        let recordLength: UInt16 = plan.includesColor ? 26 : 20
        let header = makeLAS12Header(
            pointCount: UInt32(pointCount),
            pointFormat: recordFormat,
            recordLength: recordLength,
            xAxis: xAxis,
            yAxis: yAxis,
            zAxis: zAxis,
            minX: bounds.minX,
            maxX: bounds.maxX,
            minY: bounds.minY,
            maxY: bounds.maxY,
            minZ: bounds.minZ,
            maxZ: bounds.maxZ
        )
        guard header.count == las12HeaderSize else { throw ExportError.invalidOBJ }

        try? FileManager.default.removeItem(at: outputURL)
        guard FileManager.default.createFile(atPath: outputURL.path, contents: nil) else {
            throw ExportError.cannotCreateOutput
        }

        let handle = try FileHandle(forWritingTo: outputURL)
        do {
            try handle.write(contentsOf: header)
            var buffer = Data()
            buffer.reserveCapacity(streamFlushThreshold + 64)
            var emitted = 0
            try forEachPoint(geometry: geometry, plan: plan) { vertex, color in
                if emitted % 4_096 == 0 { try Task.checkCancellation() }
                appendLittleEndian(quantize(vertex.x, axis: xAxis), to: &buffer)
                appendLittleEndian(quantize(vertex.y, axis: yAxis), to: &buffer)
                appendLittleEndian(quantize(vertex.z, axis: zAxis), to: &buffer)
                appendLittleEndian(UInt16(0), to: &buffer)
                buffer.append(0x09)
                buffer.append(0)
                buffer.append(0)
                buffer.append(0)
                appendLittleEndian(UInt16(0), to: &buffer)
                if plan.includesColor, let color {
                    appendLittleEndian(color.red, to: &buffer)
                    appendLittleEndian(color.green, to: &buffer)
                    appendLittleEndian(color.blue, to: &buffer)
                }
                emitted += 1
                try flushIfNeeded(&buffer, to: handle)
            }
            guard emitted == pointCount else { throw ExportError.invalidOBJ }
            if !buffer.isEmpty { try handle.write(contentsOf: buffer) }
            try handle.close()
        } catch {
            try? handle.close()
            throw error
        }
    }

    private static func bounds(for vertices: [Vertex]) -> Bounds {
        guard let first = vertices.first else {
            return Bounds(minX: 0, maxX: 0, minY: 0, maxY: 0, minZ: 0, maxZ: 0)
        }
        var result = Bounds(
            minX: first.x, maxX: first.x,
            minY: first.y, maxY: first.y,
            minZ: first.z, maxZ: first.z
        )
        for vertex in vertices.dropFirst() {
            result.minX = min(result.minX, vertex.x)
            result.maxX = max(result.maxX, vertex.x)
            result.minY = min(result.minY, vertex.y)
            result.maxY = max(result.maxY, vertex.y)
            result.minZ = min(result.minZ, vertex.z)
            result.maxZ = max(result.maxZ, vertex.z)
        }
        return result
    }

    private static func pointPlan(for geometry: Geometry, sourceOBJ: URL) throws -> PointPlan {
        let hasCompleteInlineColor = !geometry.vertices.isEmpty && geometry.vertices.allSatisfy { $0.color != nil }
        let allCornersHaveUV = !geometry.triangles.isEmpty && geometry.triangles.allSatisfy { triangle in
            triangle.corners.allSatisfy { corner in
                guard let index = corner.texCoord else { return false }
                return index >= 0 && index < geometry.texCoords.count
            }
        }
        if allCornersHaveUV,
           let textures = try materialTextureSet(for: geometry, sourceOBJ: sourceOBJ) {
            return .texturedCorners(textures)
        }
        if hasCompleteInlineColor { return .coloredVertices }
        return .vertices
    }

    private static func forEachPoint(
        geometry: Geometry,
        plan: PointPlan,
        body: (Vertex, VertexColor?) throws -> Void
    ) throws {
        switch plan {
        case .vertices:
            for vertex in geometry.vertices { try body(vertex, nil) }
        case .coloredVertices:
            for vertex in geometry.vertices { try body(vertex, vertex.color) }
        case .texturedCorners(let textures):
            for triangle in geometry.triangles {
                guard let sampler = textures.sampler(for: triangle.material) else {
                    throw ExportError.invalidTexture
                }
                for corner in triangle.corners {
                    guard corner.vertex >= 0, corner.vertex < geometry.vertices.count,
                          let textureIndex = corner.texCoord,
                          textureIndex >= 0, textureIndex < geometry.texCoords.count else {
                        throw ExportError.invalidOBJ
                    }
                    let vertex = geometry.vertices[corner.vertex]
                    try body(vertex, sampler.color(at: geometry.texCoords[textureIndex]))
                }
            }
        }
    }

    private static func parseOBJ(_ url: URL) throws -> Geometry {
        let data = try Data(contentsOf: url, options: [.mappedIfSafe])
        guard !data.isEmpty else { throw ExportError.invalidOBJ }
        let text = String(decoding: data, as: UTF8.self)
        var vertices: [Vertex] = []
        var texCoords: [TexCoord] = []
        var triangles: [Triangle] = []
        var materialLibraries: [String] = []
        var currentMaterial: String?
        vertices.reserveCapacity(max(128, data.count / 80))

        text.enumerateLines { line, _ in
            let trimmed = line.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty, !trimmed.hasPrefix("#") else { return }
            let fields = trimmed.split(whereSeparator: { $0.isWhitespace })
            guard let kind = fields.first else { return }
            let lowerKind = kind.lowercased()
            if lowerKind == "mtllib" {
                let arguments = parseArguments(trimmed)
                for library in arguments.dropFirst() where !materialLibraries.contains(library) {
                    materialLibraries.append(library)
                }
                return
            }
            if lowerKind == "usemtl" {
                let arguments = parseArguments(trimmed)
                let name = arguments.dropFirst().joined(separator: " ")
                    .trimmingCharacters(in: .whitespacesAndNewlines)
                currentMaterial = name.isEmpty ? nil : name
                return
            }
            if kind == "v", fields.count >= 4,
               let x = Double(fields[1]), let y = Double(fields[2]), let z = Double(fields[3]),
               x.isFinite, y.isFinite, z.isFinite {
                var color: VertexColor?
                if fields.count >= 7,
                   let red = Double(fields[4]), let green = Double(fields[5]), let blue = Double(fields[6]),
                   red.isFinite, green.isFinite, blue.isFinite {
                    color = normalizedVertexColor(red: red, green: green, blue: blue)
                }
                vertices.append(Vertex(x: x, y: y, z: z, color: color))
                return
            }
            if kind == "vt", fields.count >= 3,
               let u = Double(fields[1]), let v = Double(fields[2]), u.isFinite, v.isFinite {
                texCoords.append(TexCoord(u: u, v: v))
                return
            }
            guard kind == "f", fields.count >= 4 else { return }
            var corners: [Corner] = []
            corners.reserveCapacity(fields.count - 1)
            for token in fields.dropFirst() {
                let pieces = token.split(separator: "/", omittingEmptySubsequences: false)
                guard let vertexPiece = pieces.first,
                      let rawVertex = Int(vertexPiece),
                      let vertexIndex = resolveOBJIndex(rawVertex, count: vertices.count) else {
                    corners.removeAll()
                    break
                }
                var textureIndex: Int?
                if pieces.count >= 2, !pieces[1].isEmpty, let rawTexture = Int(pieces[1]) {
                    textureIndex = resolveOBJIndex(rawTexture, count: texCoords.count)
                }
                corners.append(Corner(vertex: vertexIndex, texCoord: textureIndex))
            }
            guard corners.count >= 3 else { return }
            for index in 1..<(corners.count - 1) {
                triangles.append(Triangle(
                    a: corners[0],
                    b: corners[index],
                    c: corners[index + 1],
                    material: currentMaterial
                ))
            }
        }
        guard !vertices.isEmpty else { throw ExportError.emptyGeometry }
        return Geometry(
            vertices: vertices,
            texCoords: texCoords,
            triangles: triangles,
            materialLibraries: materialLibraries
        )
    }

    private static func resolveOBJIndex(_ raw: Int, count: Int) -> Int? {
        guard raw != 0 else { return nil }
        let resolved = raw > 0 ? raw - 1 : count + raw
        return resolved >= 0 && resolved < count ? resolved : nil
    }

    /// Builds face-material-aware texture samplers. A single texture remains a safe fallback for
    /// legacy OBJ files without `usemtl`; multiple textures are never guessed across materials.
    private static func materialTextureSet(for geometry: Geometry, sourceOBJ: URL) throws -> MaterialTextureSet? {
        guard !geometry.materialLibraries.isEmpty else { return nil }
        let root = sourceOBJ.deletingLastPathComponent().standardizedFileURL
        let resolvedRoot = root.resolvingSymlinksInPath().standardizedFileURL
        var textureURLsByMaterial: [String: URL] = [:]
        var allTextureURLs: [URL] = []

        for materialLibrary in geometry.materialLibraries {
            try Task.checkCancellation()
            let normalizedLibrary = materialLibrary.replacingOccurrences(of: "\\", with: "/")
            let mtlURL = root.appendingPathComponent(normalizedLibrary).standardizedFileURL
            let resolvedMTL = mtlURL.resolvingSymlinksInPath().standardizedFileURL
            guard isContained(mtlURL, in: root),
                  isContained(resolvedMTL, in: resolvedRoot),
                  let data = try? Data(contentsOf: mtlURL), !data.isEmpty else { continue }

            let mtlRoot = mtlURL.deletingLastPathComponent().standardizedFileURL
            var currentMaterial: String?
            String(decoding: data, as: UTF8.self).enumerateLines { line, _ in
                let arguments = parseArguments(line)
                guard let command = arguments.first?.lowercased() else { return }
                if command == "newmtl" {
                    let name = arguments.dropFirst().joined(separator: " ")
                        .trimmingCharacters(in: .whitespacesAndNewlines)
                    currentMaterial = name.isEmpty ? nil : name
                    return
                }
                guard command == "map_kd", arguments.count >= 2,
                      let path = texturePath(in: Array(arguments.dropFirst())) else { return }
                let candidate = mtlRoot
                    .appendingPathComponent(path.replacingOccurrences(of: "\\", with: "/"))
                    .standardizedFileURL
                guard isContained(candidate, in: root),
                      FileManager.default.fileExists(atPath: candidate.path) else { return }
                let resolvedTexture = candidate.resolvingSymlinksInPath().standardizedFileURL
                guard isContained(resolvedTexture, in: resolvedRoot) else { return }
                if let currentMaterial, textureURLsByMaterial[currentMaterial] == nil {
                    textureURLsByMaterial[currentMaterial] = candidate
                }
                if !allTextureURLs.contains(candidate) { allTextureURLs.append(candidate) }
            }
        }

        guard !allTextureURLs.isEmpty else { return nil }
        let fallbackURL = allTextureURLs.count == 1 ? allTextureURLs[0] : nil

        // Do not silently apply an unrelated material's texture. Every face with an explicit
        // material must resolve its own map_Kd; faces without usemtl are allowed only when there
        // is exactly one unambiguous texture in the whole OBJ material set.
        for triangle in geometry.triangles {
            if let material = triangle.material {
                guard textureURLsByMaterial[material] != nil else { return nil }
            } else if fallbackURL == nil {
                return nil
            }
        }

        var samplerCache: [String: TextureSampler] = [:]
        func sampler(for url: URL) throws -> TextureSampler {
            let key = url.standardizedFileURL.path
            if let cached = samplerCache[key] { return cached }
            guard let loaded = try loadTextureSampler(url) else { throw ExportError.invalidTexture }
            samplerCache[key] = loaded
            return loaded
        }

        var byMaterial: [String: TextureSampler] = [:]
        for (material, url) in textureURLsByMaterial {
            if geometry.triangles.contains(where: { $0.material == material }) {
                byMaterial[material] = try sampler(for: url)
            }
        }
        let fallback = try fallbackURL.map { try sampler(for: $0) }
        return MaterialTextureSet(byMaterial: byMaterial, fallback: fallback)
    }

    /// Tokenizes OBJ/MTL arguments while preserving quoted paths, escaped whitespace and comments.
    private static func parseArguments(_ text: String) -> [String] {
        var result: [String] = []
        var current = ""
        var quote: Character?
        var escaping = false
        func flush() {
            guard !current.isEmpty else { return }
            result.append(current)
            current.removeAll(keepingCapacity: true)
        }
        for character in text {
            if escaping {
                if character.isWhitespace || character == "\"" || character == "'" || character == "\\" || character == "#" {
                    current.append(character)
                } else {
                    current.append("\\")
                    current.append(character)
                }
                escaping = false
                continue
            }
            if character == "\\" { escaping = true; continue }
            if let activeQuote = quote {
                if character == activeQuote { quote = nil } else { current.append(character) }
                continue
            }
            if character == "\"" || character == "'" { quote = character; continue }
            if character == "#" { break }
            if character.isWhitespace { flush() } else { current.append(character) }
        }
        if escaping { current.append("\\") }
        flush()
        return result
    }

    /// Extracts the filename after Wavefront map options. Unknown options conservatively consume
    /// one argument, while vector options consume up to three numeric values.
    private static func texturePath(in arguments: [String]) -> String? {
        var index = 0
        while index < arguments.count, arguments[index].hasPrefix("-") {
            let option = arguments[index].lowercased()
            index += 1
            switch option {
            case "-mm":
                index = min(arguments.count, index + 2)
            case "-o", "-s", "-t":
                var consumed = 0
                while index < arguments.count, consumed < 3, Float(arguments[index]) != nil {
                    index += 1
                    consumed += 1
                }
            default:
                if index < arguments.count { index += 1 }
            }
        }
        guard index < arguments.count else { return nil }
        let path = arguments[index...].joined(separator: " ").trimmingCharacters(in: .whitespacesAndNewlines)
        return path.isEmpty ? nil : path
    }

    private static func isContained(_ candidate: URL, in root: URL) -> Bool {
        if candidate.standardizedFileURL == root.standardizedFileURL { return true }
        let rootPath = root.standardizedFileURL.path.hasSuffix("/") ? root.standardizedFileURL.path : root.standardizedFileURL.path + "/"
        return candidate.standardizedFileURL.path.hasPrefix(rootPath)
    }

    private static func loadTextureSampler(_ url: URL) throws -> TextureSampler? {
        guard let source = CGImageSourceCreateWithURL(url as CFURL, nil) else { throw ExportError.invalidTexture }
        let options: [CFString: Any] = [
            kCGImageSourceCreateThumbnailFromImageAlways: true,
            kCGImageSourceCreateThumbnailWithTransform: true,
            kCGImageSourceThumbnailMaxPixelSize: maxTextureSampleDimension,
            kCGImageSourceShouldCacheImmediately: true,
        ]
        guard let image = CGImageSourceCreateThumbnailAtIndex(source, 0, options as CFDictionary) else {
            throw ExportError.invalidTexture
        }
        let width = image.width
        let height = image.height
        guard width > 0, height > 0 else { throw ExportError.invalidTexture }
        var rgba = Data(count: width * height * 4)
        let colorSpace = CGColorSpace(name: CGColorSpace.sRGB) ?? CGColorSpaceCreateDeviceRGB()
        let drew = rgba.withUnsafeMutableBytes { raw -> Bool in
            guard let base = raw.baseAddress,
                  let context = CGContext(
                    data: base,
                    width: width,
                    height: height,
                    bitsPerComponent: 8,
                    bytesPerRow: width * 4,
                    space: colorSpace,
                    bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue | CGBitmapInfo.byteOrder32Big.rawValue
                  ) else { return false }
            context.translateBy(x: 0, y: CGFloat(height))
            context.scaleBy(x: 1, y: -1)
            context.draw(image, in: CGRect(x: 0, y: 0, width: width, height: height))
            return true
        }
        guard drew else { throw ExportError.invalidTexture }
        return TextureSampler(width: width, height: height, rgba: rgba)
    }

    private static func normalizedVertexColor(red: Double, green: Double, blue: Double) -> VertexColor {
        let values = [red, green, blue]
        let unitRange = values.allSatisfy { $0 >= 0 && $0 <= 1 }
        let byteRange = values.allSatisfy { $0 >= 0 && $0 <= 255 }
        let multiplier: Double = unitRange ? 65_535 : (byteRange ? 257 : 1)
        func convert(_ value: Double) -> UInt16 { UInt16(clamping: Int((value * multiplier).rounded())) }
        return VertexColor(red: convert(red), green: convert(green), blue: convert(blue))
    }

    private static func makeLAS12Header(
        pointCount: UInt32,
        pointFormat: UInt8,
        recordLength: UInt16,
        xAxis: LASAxis,
        yAxis: LASAxis,
        zAxis: LASAxis,
        minX: Double,
        maxX: Double,
        minY: Double,
        maxY: Double,
        minZ: Double,
        maxZ: Double
    ) -> Data {
        var header = Data()
        header.reserveCapacity(las12HeaderSize)
        header.append(contentsOf: [0x4c, 0x41, 0x53, 0x46])
        appendLittleEndian(UInt16(0), to: &header)
        appendLittleEndian(UInt16(0), to: &header)
        header.append(Data(repeating: 0, count: 16))
        header.append(1)
        header.append(2)
        appendFixedASCII("Scan Lab Point Cloud", width: 32, to: &header)
        appendFixedASCII("Scan Lab Native", width: 32, to: &header)
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = TimeZone(secondsFromGMT: 0) ?? .current
        let now = Date()
        appendLittleEndian(UInt16(calendar.ordinality(of: .day, in: .year, for: now) ?? 0), to: &header)
        appendLittleEndian(UInt16(calendar.component(.year, from: now)), to: &header)
        appendLittleEndian(UInt16(las12HeaderSize), to: &header)
        appendLittleEndian(UInt32(las12HeaderSize), to: &header)
        appendLittleEndian(UInt32(0), to: &header)
        header.append(pointFormat)
        appendLittleEndian(recordLength, to: &header)
        appendLittleEndian(pointCount, to: &header)
        appendLittleEndian(pointCount, to: &header)
        for _ in 0..<4 { appendLittleEndian(UInt32(0), to: &header) }
        appendFloat64(xAxis.scale, to: &header)
        appendFloat64(yAxis.scale, to: &header)
        appendFloat64(zAxis.scale, to: &header)
        appendFloat64(xAxis.offset, to: &header)
        appendFloat64(yAxis.offset, to: &header)
        appendFloat64(zAxis.offset, to: &header)
        appendFloat64(maxX, to: &header)
        appendFloat64(minX, to: &header)
        appendFloat64(maxY, to: &header)
        appendFloat64(minY, to: &header)
        appendFloat64(maxZ, to: &header)
        appendFloat64(minZ, to: &header)
        return header
    }

    private static func lasAxis(minimum: Double, maximum: Double) -> LASAxis {
        let offset = (minimum + maximum) / 2
        let halfSpan = max(abs(maximum - offset), abs(minimum - offset))
        let safeIntegerRange = Double(Int32.max) - 4_096
        let scale = max(0.000_001, halfSpan / max(1, safeIntegerRange))
        return LASAxis(scale: scale, offset: offset)
    }

    private static func quantize(_ value: Double, axis: LASAxis) -> Int32 {
        let raw = ((value - axis.offset) / axis.scale).rounded()
        if raw <= Double(Int32.min) { return Int32.min }
        if raw >= Double(Int32.max) { return Int32.max }
        return Int32(raw)
    }

    private static func flushIfNeeded(_ buffer: inout Data, to handle: FileHandle) throws {
        guard buffer.count >= streamFlushThreshold else { return }
        try handle.write(contentsOf: buffer)
        buffer.removeAll(keepingCapacity: true)
    }

    private static func appendLittleEndian<T: FixedWidthInteger>(_ value: T, to data: inout Data) {
        var littleEndian = value.littleEndian
        withUnsafeBytes(of: &littleEndian) { data.append(contentsOf: $0) }
    }

    private static func appendFloat32(_ value: Float, to data: inout Data) {
        appendLittleEndian(value.bitPattern, to: &data)
    }

    private static func appendFloat64(_ value: Double, to data: inout Data) {
        appendLittleEndian(value.bitPattern, to: &data)
    }

    private static func appendFixedASCII(_ value: String, width: Int, to data: inout Data) {
        let bytes = Array(value.utf8.prefix(width))
        data.append(contentsOf: bytes)
        if bytes.count < width { data.append(Data(repeating: 0, count: width - bytes.count)) }
    }
}
