import Foundation
import ImageIO
import simd

private struct AuditEdge:Hashable{let a:Int;let b:Int;init(_ x:Int,_ y:Int){a=min(x,y);b=max(x,y)}}
private struct MeshParityReport:Codable{let schemaVersion:Int;let generatedAt:Date;let file:String;let vertices:Int;let triangles:Int;let boundsMeters:[Double];let boundaryEdgeRate:Double;let connectedComponents:Int;let textureWidth:Int?;let textureHeight:Int?;let referenceTriangleRatio:Double?;let referenceTextureRatio:Double?;let grade:String;let warnings:[String]}

private enum MeshParityAuditEngine{
    static func audit(url:URL)throws->MeshParityReport{let text=try String(contentsOf:url,encoding:.utf8);var v:[SIMD3<Float>]=[],faces:[SIMD3<Int>]=[];var mtlName:String?;for l in text.split(whereSeparator:\.isNewline){if l.hasPrefix("v "){let p=l.split(separator:" ");if p.count>=4,let x=Float(p[1]),let y=Float(p[2]),let z=Float(p[3]){v.append(.init(x,y,z))}}else if l.hasPrefix("f "){let ids=l.split(separator:" ").dropFirst().compactMap{t->Int? in guard let s=t.split(separator:"/",omittingEmptySubsequences:false).first,let r=Int(s) else{return nil};return r>0 ? r-1:v.count+r};if ids.count>=3{for i in 1..<(ids.count-1){faces.append(.init(ids[0],ids[i],ids[i+1]))}}}else if l.hasPrefix("mtllib "){mtlName=String(l.dropFirst(7)).trimmingCharacters(in:.whitespaces)}};guard !v.isEmpty && !faces.isEmpty else{throw NSError(domain:"ScanLab.MeshParityAudit",code:1,userInfo:[NSLocalizedDescriptionKey:"監査対象Meshが空です"])}
        var minP=SIMD3<Float>(repeating:.greatestFiniteMagnitude),maxP=SIMD3<Float>(repeating:-.greatestFiniteMagnitude);for p in v{minP=simd_min(minP,p);maxP=simd_max(maxP,p)};let ext=maxP-minP
        var edges:[AuditEdge:Int]=[:];for f in faces{edges[.init(f.x,f.y),default:0]+=1;edges[.init(f.y,f.z),default:0]+=1;edges[.init(f.z,f.x),default:0]+=1};let boundary=edges.values.filter{$0==1}.count,rate=Double(boundary)/Double(max(1,edges.count))
        var parent=Array(0..<v.count);func find(_ x:Int)->Int{var i=x;while parent[i] != i{parent[i]=parent[parent[i]];i=parent[i]};return i};func union(_ a:Int,_ b:Int){let x=find(a),y=find(b);if x != y{parent[y]=x}};for f in faces{union(f.x,f.y);union(f.y,f.z)};let comps=Set(faces.map{find($0.x)}).count
        var tw:Int?,th:Int?;if let mtlName{let mtlURL=url.deletingLastPathComponent().appendingPathComponent(mtlName);if let m=try? String(contentsOf:mtlURL,encoding:.utf8),let tex=m.split(whereSeparator:\.isNewline).first(where:{$0.hasPrefix("map_Kd ")}).map({String($0.dropFirst(7)).trimmingCharacters(in:.whitespaces)}){let texURL=url.deletingLastPathComponent().appendingPathComponent(tex);if let src=CGImageSourceCreateWithURL(texURL as CFURL,nil),let props=CGImageSourceCopyPropertiesAtIndex(src,0,nil) as? [CFString:Any]{tw=props[kCGImagePropertyPixelWidth] as? Int;th=props[kCGImagePropertyPixelHeight] as? Int}}}
        let maxDim=max(ext.x,max(ext.y,ext.z)),similar=maxDim>=0.40 && maxDim<=1.0;let triRatio=similar ? Double(faces.count)/275481.0:nil,texRatio=(similar && tw != nil) ? Double(max(tw!,th ?? 0))/8192.0:nil;var warnings:[String]=[];if faces.count<25_000{warnings.append("三角形密度が低い")};if tw == nil{warnings.append("テクスチャがない")}else if max(tw!,th ?? 0)<4096{warnings.append("テクスチャ解像度が4K未満")};if rate>0.22{warnings.append("境界エッジ率が高い")};if similar,let triRatio,triRatio<0.25{warnings.append("同程度サイズのScaniverse参照に対し形状密度が1/4未満")};let grade=warnings.isEmpty ? "REFERENCE_READY":(warnings.count<=1 ? "STRONG":"BELOW_REFERENCE");return .init(schemaVersion:1,generatedAt:Date(),file:url.lastPathComponent,vertices:v.count,triangles:faces.count,boundsMeters:[Double(ext.x),Double(ext.y),Double(ext.z)],boundaryEdgeRate:rate,connectedComponents:comps,textureWidth:tw,textureHeight:th,referenceTriangleRatio:triRatio,referenceTextureRatio:texRatio,grade:grade,warnings:warnings)}
}

extension MeshScanModel{
    func runMeshParityAudit(){guard phase == .finished,let u=resultURL,u.pathExtension.lowercased()=="obj" else{return};Task{do{let r=try await Task.detached(priority:.utility){try MeshParityAuditEngine.audit(url:u)}.value;let out=u.deletingLastPathComponent().appendingPathComponent("mesh-quality-report.json"),e=JSONEncoder();e.outputFormatting=[.prettyPrinted,.sortedKeys];e.dateEncodingStrategy = .iso8601;try e.encode(r).write(to:out,options:.atomic);self.statusMessage="品質監査 \(r.grade)：\(r.triangles.formatted())面・境界\(Int((r.boundaryEdgeRate*100).rounded()))%" + (r.warnings.isEmpty ? "":" / "+r.warnings.joined(separator:"、"))}catch{self.statusMessage="品質監査を完了できませんでした: \(error.localizedDescription)"}}}
}
