(async()=>{'use strict';const QUESTIONS=await window.QUESTIONS_READY;const FIELDS=[...new Set(QUESTIONS.map(q=>q.field))];const FIELD_SHORT={'ライフプラン':'ライフ','リスク管理':'リスク','金融資産運用':'金融','タックス':'税金','不動産':'不動産','相続':'相続'};
const STORE_KEY='fp3SwipeKnockStateV2';
const LEGACY_KEY='fp3TwelveKnockStateV1';
const SWIPE_COMMIT_DISTANCE=36,SWIPE_FLICK_DISTANCE=24,SWIPE_FLICK_TIME=280;
const $=id=>document.getElementById(id);
const defaultState=()=>({version:2,questionState:{},totalAnswered:0,totalCorrect:0,sessions:0,studyDates:[],examDate:'',fontSize:'16',activeSession:null,bestCombo:0,sound:true});
function safeStorage(){try{const t='__fp3_swipe_test__';localStorage.setItem(t,'1');localStorage.removeItem(t);return localStorage}catch{return null}}
const storage=safeStorage();
function loadState(){try{let raw=storage?.getItem(STORE_KEY);if(raw)return Object.assign(defaultState(),JSON.parse(raw));raw=storage?.getItem(LEGACY_KEY);return raw?Object.assign(defaultState(),JSON.parse(raw),{version:2}):defaultState()}catch{return defaultState()}}
let state=loadState(),session=null,pendingModalAction=null,audioContext=null;
function saveState(){try{storage?.setItem(STORE_KEY,JSON.stringify(state))}catch{}}
function today(){return new Date().toLocaleDateString('sv-SE')}
function shuffle(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function qState(id){return state.questionState[id]||{status:'new',attempts:0,correct:0}}
function priority(q){const s=qState(q.id).status;return s==='weak'?0:s==='unsure'?1:s==='new'?2:3}
function prioritized(pool){return shuffle(pool).sort((a,b)=>priority(a)-priority(b))}
function pickBalanced(countPerField){const out=[];for(const field of FIELDS)out.push(...prioritized(QUESTIONS.filter(q=>q.field===field)).slice(0,countPerField));return shuffle(out)}
function pickBalancedDaily(){return pickBalanced(2)}
function pickChallenge(){return pickBalanced(10).slice(0,60)}
function pickReview(){const weak=prioritized(QUESTIONS.filter(q=>['weak','unsure'].includes(qState(q.id).status)));if(weak.length>=12)return weak.slice(0,12);const ids=new Set(weak.map(q=>q.id));const fill=prioritized(QUESTIONS.filter(q=>!ids.has(q.id)));return [...weak,...fill.slice(0,12-weak.length)]}
function pickField(field){return prioritized(QUESTIONS.filter(q=>q.field===field)).slice(0,8)}
function modeLabel(mode,field){return mode==='daily'?'今日の12問':mode==='challenge'?'60問チャレンジ':mode==='review'?'迷い・間違い':field||'分野別8問'}
function startSession(mode,field){const queue=mode==='daily'?pickBalancedDaily():mode==='challenge'?pickChallenge():mode==='review'?pickReview():pickField(field);if(!queue.length)return;session={mode,field:field||'',queue:queue.map(q=>q.id),index:0,correct:0,wrong:0,unknown:0,markedUnsure:0,answered:false,lastChoice:null,score:0,combo:0,bestCombo:0};state.activeSession=session;saveState();showView('quiz');renderQuestion()}
function restoreSession(){if(!state.activeSession)return;session=Object.assign({score:0,combo:0,bestCombo:0,markedUnsure:0},state.activeSession);showView('quiz');renderQuestion()}
function currentQuestion(){return session?QUESTIONS.find(q=>q.id===session.queue[session.index]):null}
function renderQuestion(){const q=currentQuestion();if(!q)return finishSession();session.answered=false;session.lastChoice=null;state.activeSession=session;saveState();$('quizModeTitle').textContent=modeLabel(session.mode,session.field);$('fieldChip').textContent=FIELD_SHORT[q.field]||q.field;$('topicChip').textContent=q.topic;$('questionText').textContent=q.text;$('quizCounter').textContent=`${session.index+1}/${session.queue.length}`;$('progressBar').style.width=`${(session.index/session.queue.length)*100}%`;$('scoreValue').textContent=session.score.toLocaleString('ja-JP');$('comboValue').textContent=session.combo;$('feedbackPanel').className='feedback-panel is-hidden';$('uncertainMark').className='uncertain-mark is-hidden';$('uncertainMark').textContent='正解したけど迷った';$('questionCard').style.transform='';$('questionCard').removeAttribute('data-direction');[$('falseButton'),$('trueButton'),$('unknownButton')].forEach(b=>b.disabled=false);$('nextQuestion').textContent=session.index===session.queue.length-1?'結果を見る':'次の問題へ';window.scrollTo({top:0,behavior:'instant'})}
function answer(choice){if(!session||session.answered)return;const q=currentQuestion();if(!q)return;session.answered=true;session.lastChoice=choice;[$('falseButton'),$('trueButton'),$('unknownButton')].forEach(b=>b.disabled=true);const qs=qState(q.id);qs.attempts=(qs.attempts||0)+1;state.totalAnswered++;let correct=false,kind,title,points=0;
if(choice==='unknown'){session.unknown++;session.combo=0;qs.status='unsure';kind='is-unknown';title='保留'}else{correct=(choice==='true')===q.answer;if(correct){session.correct++;state.totalCorrect++;qs.correct=(qs.correct||0)+1;qs.status='ok';session.combo++;session.bestCombo=Math.max(session.bestCombo,session.combo);state.bestCombo=Math.max(state.bestCombo||0,session.combo);points=100+Math.min(session.combo,20)*5;session.score+=points;kind='is-correct';title='正解';$('uncertainMark').classList.remove('is-hidden')}else{session.wrong++;session.combo=0;qs.status='weak';kind='is-wrong';title='不正解'}}
state.questionState[q.id]=qs;state.activeSession=session;saveState();$('feedbackPanel').className=`feedback-panel ${kind}`;$('feedbackTitle').textContent=title;$('feedbackPoints').textContent=correct?`+${points}`:'+0';$('feedbackCorrect').textContent=`正解：${q.answer?'○ →':'← ×'}`;$('explanation').textContent=q.explanation;$('scoreValue').textContent=session.score.toLocaleString('ja-JP');$('comboValue').textContent=session.combo;playTone(correct,choice==='unknown');buzz(correct,choice==='unknown');try{$('feedbackPanel').scrollIntoView({behavior:'smooth',block:'start'})}catch{}}
function toggleUncertain(){if(!session||!session.answered||session.lastChoice==='unknown')return;const q=currentQuestion(),qs=qState(q.id),btn=$('uncertainMark'),on=btn.classList.toggle('on');if(on){qs.status='unsure';session.markedUnsure++;btn.textContent='迷いとして保存済み'}else{qs.status='ok';session.markedUnsure=Math.max(0,session.markedUnsure-1);btn.textContent='正解したけど迷った'}state.questionState[q.id]=qs;state.activeSession=session;saveState()}
function nextQuestion(){if(!session?.answered)return;if(session.index<session.queue.length-1){session.index++;renderQuestion()}else finishSession()}
function finishSession(){if(!session)return;state.sessions++;if(!state.studyDates.includes(today()))state.studyDates.push(today());state.activeSession=null;saveState();$('resultCorrect').textContent=session.correct;$('resultWrong').textContent=session.wrong;$('resultUnknown').textContent=session.unknown;$('resultBestCombo').textContent=session.bestCombo;$('resultScore').textContent=session.score.toLocaleString('ja-JP');$('resultTitle').textContent=session.mode==='challenge'?'60問チャレンジ完了':`${session.queue.length}問完了`;$('resultSub').textContent=`${session.queue.length}問中 ${session.correct}問正解`;const unresolved=session.wrong+session.unknown+session.markedUnsure;$('resultMessage').innerHTML=unresolved?`<b>${unresolved}問</b>を復習待ちに残しました。正解数だけでなく、迷いを減らすことを優先します。`:'全問を迷わず回答できました。次回は未回答問題を中心に出題します。';$('resultReview').hidden=countReview()===0;session=null;showView('result');renderHome();renderRecord()}
function countReview(){return QUESTIONS.filter(q=>['weak','unsure'].includes(qState(q.id).status)).length}
function streak(){const dates=[...new Set(state.studyDates)].sort();if(!dates.length)return 0;let d=new Date(today()+'T00:00:00'),set=new Set(dates);if(!set.has(today()))d.setDate(d.getDate()-1);let n=0;while(set.has(d.toLocaleDateString('sv-SE'))){n++;d.setDate(d.getDate()-1)}return n}
function renderHome(){$('streakMetric').textContent=`${streak()}日`;$('reviewMetric').textContent=`${countReview()}問`;const seen=Object.keys(state.questionState).length;$('seenMetric').textContent=`${Math.round(seen/QUESTIONS.length*100)}%`;$('bestComboMetric').textContent=state.bestCombo||0;$('reviewDescription').textContent=countReview()?`${countReview()}問が復習待ち`:'復習待ちはありません';$('resumeBtn').hidden=!state.activeSession;renderExamPill()}
function renderFields(){const counts=Object.fromEntries(FIELDS.map(f=>[f,QUESTIONS.filter(q=>q.field===f).length]));$('fieldButtons').innerHTML=FIELDS.map(f=>`<button class="field-btn" data-field="${escapeHtml(f)}"><b>${escapeHtml(FIELD_SHORT[f]||f)}</b><span>${counts[f]}問から優先8問</span></button>`).join('')}
function renderRecord(){$('totalAnswered').textContent=state.totalAnswered;$('overallAccuracy').textContent=state.totalAnswered?`${Math.round(state.totalCorrect/state.totalAnswered*100)}%`:'0%';$('totalSessions').textContent=state.sessions;$('bestComboRecord').textContent=state.bestCombo||0;$('fieldBars').innerHTML=FIELDS.map(f=>{const qs=QUESTIONS.filter(q=>q.field===f),ok=qs.filter(q=>qState(q.id).status==='ok').length,pct=Math.round(ok/qs.length*100);return `<div class="bar-row"><span>${escapeHtml(FIELD_SHORT[f]||f)}</span><div class="bar-bg"><div class="bar-fill" style="width:${pct}%"></div></div><b>${pct}%</b></div>`}).join('')}
function renderSettings(){$('examDate').value=state.examDate||'';$('fontSize').value=state.fontSize||'16';document.documentElement.style.setProperty('--font',`${state.fontSize||16}px`);$('soundButton').setAttribute('aria-pressed',String(state.sound));$('soundButton').textContent=state.sound?'♪':'×'}
function renderExamPill(){if(!state.examDate){$('examPill').textContent='受検日 未設定';return}const now=new Date(today()+'T00:00:00'),exam=new Date(state.examDate+'T00:00:00'),diff=Math.ceil((exam-now)/86400000);$('examPill').textContent=diff>=0?`受検まで ${diff}日`:'受検日経過'}
function showView(name){const map={home:'homeView',quiz:'quizView',result:'resultView',record:'recordView',settings:'settingsView'};document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(map[name]).classList.add('active');const showNav=!['quiz','result'].includes(name);$('bottomNav').style.display=showNav?'grid':'none';$('topBar').style.display=name==='quiz'?'none':'flex';document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==='home')renderHome();if(name==='record')renderRecord();if(name==='settings')renderSettings();window.scrollTo({top:0,behavior:'instant'})}
function openModal(title,text,action){$('modalTitle').textContent=title;$('modalText').textContent=text;pendingModalAction=action;$('modalBack').classList.add('show')}
function closeModal(){$('modalBack').classList.remove('show');pendingModalAction=null}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function playTone(correct,unknown=false){if(!state.sound)return;try{audioContext||=new(window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume();const now=audioContext.currentTime,freqs=unknown?[420]:correct?[660,990]:[200];freqs.forEach((freq,i)=>{const o=audioContext.createOscillator(),g=audioContext.createGain();o.type=correct?'sine':'square';o.frequency.value=freq;g.gain.setValueAtTime(.06,now+i*.07);g.gain.exponentialRampToValueAtTime(.001,now+i*.07+.16);o.connect(g).connect(audioContext.destination);o.start(now+i*.07);o.stop(now+i*.07+.16)})}catch{state.sound=false}}
function buzz(correct,unknown=false){try{navigator.vibrate?.(unknown?20:correct?12:[0,40,60,40])}catch{}}
function bindSwipe(){const card=$('questionCard');let id=null,x0=0,y0=0,dx=0,axis=null,startedAt=0;const reset=()=>{id=null;dx=0;axis=null;card.classList.remove('is-dragging');card.style.transform='';card.removeAttribute('data-direction')};card.addEventListener('pointerdown',e=>{if(!session||session.answered)return;id=e.pointerId;x0=e.clientX;y0=e.clientY;dx=0;axis=null;startedAt=performance.now();card.classList.add('is-dragging')});card.addEventListener('pointermove',e=>{if(id!==e.pointerId||!session||session.answered)return;const mx=e.clientX-x0,my=e.clientY-y0;if(!axis){if(Math.abs(mx)<8&&Math.abs(my)<8)return;axis=Math.abs(mx)>Math.abs(my)?'x':'y';if(axis==='x')card.setPointerCapture?.(e.pointerId)}if(axis!=='x')return;e.preventDefault();dx=mx;card.style.transform=`translate3d(${dx}px,0,0) rotate(${Math.max(-12,Math.min(12,dx/18))}deg)`;if(Math.abs(dx)>=SWIPE_FLICK_DISTANCE)card.dataset.direction=dx<0?'false':'true';else card.removeAttribute('data-direction')});const end=e=>{if(id!==e.pointerId)return;const moved=dx,wasHorizontal=axis==='x',quick=performance.now()-startedAt<=SWIPE_FLICK_TIME&&Math.abs(moved)>=SWIPE_FLICK_DISTANCE;reset();if(!wasHorizontal)return;if(moved<=-SWIPE_COMMIT_DISTANCE||(quick&&moved<0))answer('false');else if(moved>=SWIPE_COMMIT_DISTANCE||(quick&&moved>0))answer('true')};card.addEventListener('pointerup',end);card.addEventListener('pointercancel',end)}
$('dailyStart').addEventListener('click',()=>startSession('daily'));$('challengeStart').addEventListener('click',()=>startSession('challenge'));$('resumeBtn').addEventListener('click',restoreSession);$('reviewStart').addEventListener('click',()=>startSession('review'));$('fieldButtons').addEventListener('click',e=>{const b=e.target.closest('[data-field]');if(b)startSession('field',b.dataset.field)});$('falseButton').addEventListener('click',()=>answer('false'));$('trueButton').addEventListener('click',()=>answer('true'));$('unknownButton').addEventListener('click',()=>answer('unknown'));$('uncertainMark').addEventListener('click',toggleUncertain);$('nextQuestion').addEventListener('click',nextQuestion);$('quitQuiz').addEventListener('click',()=>openModal('学習を中断しますか？','進捗は保存され、ホームから再開できます。',()=>showView('home')));$('resultReview').addEventListener('click',()=>startSession('review'));$('resultHome').addEventListener('click',()=>showView('home'));$('bottomNav').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)showView(b.dataset.view)});$('examDate').addEventListener('change',e=>{state.examDate=e.target.value;saveState();renderExamPill()});$('fontSize').addEventListener('change',e=>{state.fontSize=e.target.value;saveState();renderSettings()});$('soundButton').addEventListener('click',()=>{state.sound=!state.sound;saveState();renderSettings()});$('resetData').addEventListener('click',()=>openModal('学習記録を消しますか？','回答履歴、弱点、連続学習、設定がすべて削除されます。',()=>{state=defaultState();saveState();renderSettings();renderHome();renderRecord();showView('home')}));$('modalCancel').addEventListener('click',closeModal);$('modalBack').addEventListener('click',e=>{if(e.target===$('modalBack'))closeModal()});$('modalConfirm').addEventListener('click',()=>{const action=pendingModalAction;closeModal();if(action)action()});window.addEventListener('keydown',e=>{if(!$('quizView').classList.contains('active'))return;if(e.key==='ArrowLeft'){e.preventDefault();answer('false')}if(e.key==='ArrowRight'){e.preventDefault();answer('true')}if(e.key==='ArrowDown'||e.key==='?'){e.preventDefault();answer('unknown')}if((e.key==='Enter'||e.key===' ')&&!$('feedbackPanel').classList.contains('is-hidden')){e.preventDefault();nextQuestion()}});bindSwipe();renderFields();renderHome();renderRecord();renderSettings();window.__FP3_TEST__={questionCount:QUESTIONS.length,fields:FIELDS,getState:()=>state,getSession:()=>session,getQuestions:()=>QUESTIONS,currentQuestion,startSession,answer,nextQuestion,showView,pickChallenge};})();