import Foundation

extension Lane3LongTrackSpectralPerceptualDifferentialAnalyzer {
    static func validate(_ c: Lane3SpectralDifferentialConfiguration, sampleRate: Double) throws {
        guard isPowerOfTwo(c.windowSize), c.windowSize >= 128, c.windowSize <= 16384, c.hopSize>0,c.hopSize<=c.windowSize,
              c.minimumFrequencyHz.isFinite,c.minimumFrequencyHz>=0,c.maximumFrequencyHz.isFinite,c.maximumFrequencyHz>c.minimumFrequencyHz,c.maximumFrequencyHz<=sampleRate/2,
              c.expectedFrequencyRatio.isFinite,c.expectedFrequencyRatio>0,c.expectedFrequencyRatio<=8,c.frequencyRatioSearchRadiusCents.isFinite,c.frequencyRatioSearchRadiusCents>=0,c.frequencyRatioSearchRadiusCents<=2400,
              c.frequencyRatioSearchStepCents.isFinite,c.frequencyRatioSearchStepCents>0,(c.frequencyRatioSearchRadiusCents==0 || c.frequencyRatioSearchStepCents<=c.frequencyRatioSearchRadiusCents),
              c.highBandStartHz.isFinite,c.highBandStartHz>=c.minimumFrequencyHz,c.highBandStartHz<c.maximumFrequencyHz,c.spectralFloorDB.isFinite,c.spectralFloorDB<=0,c.minimumWindowRMS.isFinite,c.minimumWindowRMS>=0,c.maximumWindows>0 else { throw Lane3LongTrackEvidenceError.invalidConfiguration }
    }
    static func isPowerOfTwo(_ x:Int)->Bool{x>0 && (x&(x-1))==0}
    static func alignedRanges(referenceCount:Int64,observedCount:Int64,lag:Int)->AlignedRange{let rs=Int64(max(0,-lag)),os=Int64(max(0,lag));return .init(referenceStart:rs,observedStart:os,count:max(0,min(referenceCount-rs,observedCount-os)))}
    static func selectedWindowStarts(comparableFrames:Int64,windowSize:Int,hopSize:Int,maximumWindows:Int)->[Int64]{guard comparableFrames>=Int64(windowSize) else{return[]};var s:[Int64]=[];var x:Int64=0;while x+Int64(windowSize)<=comparableFrames{s.append(x);x+=Int64(hopSize)};guard s.count>maximumWindows else{return s};if maximumWindows==1{return[s[s.count/2]]};return(0..<maximumWindows).map{let p=Double($0)*Double(s.count-1)/Double(maximumWindows-1);return s[Int(p.rounded())]}}
    static func hannWindow(_ n:Int)->[Double]{guard n>1 else{return[1]};return(0..<n).map{0.5-0.5*cos(2*Double.pi*Double($0)/Double(n-1))}}
    static func powerSpectrum(_ samples:[Double],window:[Double])->[Double]{var v=[Complex](repeating:.init(real:0,imag:0),count:samples.count);for i in samples.indices{v[i].real=samples[i]*window[i]};fft(&v);return(0...samples.count/2).map{max(0,v[$0].real*v[$0].real+v[$0].imag*v[$0].imag)}}
    static func fft(_ v:inout[Complex]){let n=v.count;var j=0;if n>1{for i in 1..<(n-1){var bit=n>>1;while j&bit != 0{j^=bit;bit>>=1};j^=bit;if i<j{v.swapAt(i,j)}}};var len=2;while len<=n{let angle = -2*Double.pi/Double(len);let wl=Complex(real:cos(angle),imag:sin(angle));var start=0;while start<n{var w=Complex(real:1,imag:0);for o in 0..<(len/2){let ei=start+o,oi=ei+len/2;let odd=multiply(v[oi],w),even=v[ei];v[ei] = .init(real:even.real+odd.real,imag:even.imag+odd.imag);v[oi] = .init(real:even.real-odd.real,imag:even.imag-odd.imag);w=multiply(w,wl)};start+=len};len<<=1}}
    static func multiply(_ a:Complex,_ b:Complex)->Complex{.init(real:a.real*b.real-a.imag*b.imag,imag:a.real*b.imag+a.imag*b.real)}
    static func warpedReferencePower(referencePower:[Double],ratio:Double,outputBinCount:Int)->[Double]{var out=[Double](repeating:0,count:outputBinCount);guard ratio>0 else{return out};for b in 0..<outputBinCount{let p=Double(b)/ratio,l=Int(floor(p)),u=l+1;guard l>=0,l<referencePower.count else{continue};if u<referencePower.count{let f=p-Double(l);out[b]=referencePower[l]*(1-f)+referencePower[u]*f}else{out[b]=referencePower[l]}};return out}
    static func normalizeSpectrum(_ p:[Double])->[Double]{let t=p.reduce(0){$0+max(0,$1)};return t>1e-30 ? p.map{max(0,$0)/t} : [Double](repeating:0,count:p.count)}
    static func analysisRange(sampleRate:Double,windowSize:Int,c:Lane3SpectralDifferentialConfiguration,binCount:Int)->Range<Int>{let hz=sampleRate/Double(windowSize),l=max(1,Int(ceil(c.minimumFrequencyHz/hz))),u=min(binCount-1,Int(floor(c.maximumFrequencyHz/hz)));return l..<max(l,u+1)}
    static func scaleCorrelation(referencePower:[Double],observedPower:[Double],ratio:Double,sampleRate:Double,configuration c:Lane3SpectralDifferentialConfiguration)->Double{let r=normalizeSpectrum(warpedReferencePower(referencePower:referencePower,ratio:ratio,outputBinCount:observedPower.count)),o=normalizeSpectrum(observedPower),range=analysisRange(sampleRate:sampleRate,windowSize:(referencePower.count-1)*2,c:c,binCount:observedPower.count);var dot=0.0,rr=0.0,oo=0.0;for b in range{let x=log1p(max(0,r[b])*1e9),y=log1p(max(0,o[b])*1e9);dot+=x*y;rr+=x*x;oo+=y*y};let d=sqrt(rr*oo);return d>1e-20 ? max(-1,min(1,dot/d)) : 0}
    static func estimateFrequencyRatio(referencePower:[Double],observedPower:[Double],sampleRate:Double,configuration c:Lane3SpectralDifferentialConfiguration)->(ratio:Double,correlation:Double){if c.frequencyRatioSearchRadiusCents==0{return(c.expectedFrequencyRatio,scaleCorrelation(referencePower:referencePower,observedPower:observedPower,ratio:c.expectedFrequencyRatio,sampleRate:sampleRate,configuration:c))};let steps=Int((c.frequencyRatioSearchRadiusCents/c.frequencyRatioSearchStepCents).rounded(.down));var br=c.expectedFrequencyRatio,bc = -Double.infinity;for s in (-steps)...steps{let cents=Double(s)*c.frequencyRatioSearchStepCents,r=c.expectedFrequencyRatio*pow(2,cents/1200),score=scaleCorrelation(referencePower:referencePower,observedPower:observedPower,ratio:r,sampleRate:sampleRate,configuration:c);if score>bc || (score==bc && abs(cents)<abs(centsError(actualRatio:br,expectedRatio:c.expectedFrequencyRatio))){bc=score;br=r}};return(br,bc)}
    struct Peak{let frequency:Double;let power:Double}
    static func spectralPeaks(_ power:[Double],sampleRate:Double,c:Lane3SpectralDifferentialConfiguration)->[Peak]{
        let windowSize=max(2,(power.count-1)*2),range=analysisRange(sampleRate:sampleRate,windowSize:windowSize,c:c,binCount:power.count)
        guard range.count>=3 else{return[]}
        let maximum=range.map{max(0,power[$0])}.max() ?? 0
        guard maximum>1e-30 else{return[]}
        let threshold=maximum*1e-5,hz=sampleRate/Double(windowSize)
        var peaks:[Peak]=[]
        let lower=max(range.lowerBound+1,1),upper=min(range.upperBound-1,power.count-1)
        guard lower<upper else{return[]}
        for bin in lower..<upper {
            let center=max(power[bin],1e-30)
            guard center>=threshold,center>power[bin-1],center>=power[bin+1] else{continue}
            let leftLog=log(max(power[bin-1],1e-30)),centerLog=log(center),rightLog=log(max(power[bin+1],1e-30))
            let denominator=leftLog-2*centerLog+rightLog
            var delta=0.0
            if abs(denominator)>1e-12 { delta=0.5*(leftLog-rightLog)/denominator; delta=max(-0.5,min(0.5,delta)) }
            peaks.append(.init(frequency:(Double(bin)+delta)*hz,power:center))
        }
        return Array(peaks.sorted{$0.power>$1.power}.prefix(32))
    }
    static func spectralPeakMatches(referencePower:[Double],observedPower:[Double],sampleRate:Double,configuration c:Lane3SpectralDifferentialConfiguration)->[Lane3SpectralPeakMatchObservation]{let r=spectralPeaks(referencePower,sampleRate:sampleRate,c:c),o=spectralPeaks(observedPower,sampleRate:sampleRate,c:c);var used=Set<Int>(),m:[Lane3SpectralPeakMatchObservation]=[];let tolerance=max(50,min(100,c.frequencyRatioSearchRadiusCents/2+c.frequencyRatioSearchStepCents*2));for rp in r{let expected=rp.frequency*c.expectedFrequencyRatio;guard expected>=c.minimumFrequencyHz,expected<=c.maximumFrequencyHz else{continue};var bi:Int?,be=Double.infinity,bs=0.0;for (i,op) in o.enumerated() where !used.contains(i){let s=centsError(actualRatio:op.frequency/max(rp.frequency,1e-12),expectedRatio:c.expectedFrequencyRatio),a=abs(s);if a<be{be=a;bs=s;bi=i}};if let bi,be<=tolerance{used.insert(bi);m.append(.init(referenceFrequencyHz:rp.frequency,expectedObservedFrequencyHz:expected,observedFrequencyHz:o[bi].frequency,ratioErrorCents:bs))}};return m.sorted{abs($0.ratioErrorCents)<abs($1.ratioErrorCents)}}
    static func logSpectralDistanceDB(expectedReference:[Double],observed:[Double],sampleRate:Double,windowSize:Int,configuration c:Lane3SpectralDifferentialConfiguration)->Double{let range=analysisRange(sampleRate:sampleRate,windowSize:windowSize,c:c,binCount:min(expectedReference.count,observed.count)),floorP=pow(10,c.spectralFloorDB/10);guard !range.isEmpty else{return 0};var s=0.0;for b in range{let d=10*log10(max(observed[b],floorP))-10*log10(max(expectedReference[b],floorP));s+=d*d};return sqrt(s/Double(range.count))}
    static func spectralCentroidHz(power:[Double],sampleRate:Double,windowSize:Int,configuration c:Lane3SpectralDifferentialConfiguration)->Double{let range=analysisRange(sampleRate:sampleRate,windowSize:windowSize,c:c,binCount:power.count),hz=sampleRate/Double(windowSize);var w=0.0,t=0.0;for b in range{let v=max(0,power[b]);w+=Double(b)*hz*v;t+=v};return t>1e-30 ? w/t : c.minimumFrequencyHz}
    static func spectralFlatness(power:[Double],sampleRate:Double,windowSize:Int,configuration c:Lane3SpectralDifferentialConfiguration)->Double{let range=analysisRange(sampleRate:sampleRate,windowSize:windowSize,c:c,binCount:power.count);guard !range.isEmpty else{return 0};var ls=0.0,a=0.0;for b in range{let v=max(power[b],1e-30);ls+=log(v);a+=v};let g=exp(ls/Double(range.count));a/=Double(range.count);return a>0 ? g/a:0}
    static func highBandEnergyFraction(power:[Double],sampleRate:Double,windowSize:Int,configuration c:Lane3SpectralDifferentialConfiguration)->Double{let range=analysisRange(sampleRate:sampleRate,windowSize:windowSize,c:c,binCount:power.count),hz=sampleRate/Double(windowSize);var h=0.0,t=0.0;for b in range{let v=max(0,power[b]);t+=v;if Double(b)*hz>=c.highBandStartHz{h+=v}};return t>1e-30 ? h/t:0}
    static func bandEnergyCosineDistance(referencePower:[Double],observedPower:[Double],sampleRate:Double,windowSize:Int,configuration c:Lane3SpectralDifferentialConfiguration)->Double{let edges=logEdges(minHz:max(c.minimumFrequencyHz,20),maxHz:c.maximumFrequencyHz,bands:8),r=bandEnergies(referencePower,sampleRate:sampleRate,windowSize:windowSize,edges:edges),o=bandEnergies(observedPower,sampleRate:sampleRate,windowSize:windowSize,edges:edges);var dot=0.0,rr=0.0,oo=0.0;for i in r.indices{dot+=r[i]*o[i];rr+=r[i]*r[i];oo+=o[i]*o[i]};let d=sqrt(rr*oo),cosine=d>1e-30 ? max(0,min(1,dot/d)):1;return 1-cosine}
    static func logEdges(minHz:Double,maxHz:Double,bands:Int)->[Double]{let a=log(max(minHz,1)),b=log(max(maxHz,minHz+1));return(0...bands).map{exp(a+(b-a)*Double($0)/Double(bands))}}
    static func bandEnergies(_ power:[Double],sampleRate:Double,windowSize:Int,edges:[Double])->[Double]{let hz=sampleRate/Double(windowSize);var out=[Double](repeating:0,count:edges.count-1);for b in 1..<power.count{let f=Double(b)*hz;if let i=(0..<(edges.count-1)).first(where:{f>=edges[$0]&&f<edges[$0+1]}){out[i]+=max(0,power[b])}};let t=out.reduce(0,+);return t>1e-30 ? out.map{$0/t}:out}
    static func spectralFlux(previous:[Double],current:[Double])->Double{let n=min(previous.count,current.count);guard n>0 else{return 0};var s=0.0;for i in 0..<n{let d=max(0,current[i]-previous[i]);s+=d*d};return sqrt(s/Double(n))}
    static func rms(_ x:[Double])->Double{guard !x.isEmpty else{return 0};var s=0.0,n=0;for v in x where v.isFinite{s+=v*v;n+=1};return n>0 ? sqrt(s/Double(n)):0}
    static func correlation(_ a:[Double],_ b:[Double])->Double{let n=min(a.count,b.count);guard n>=2 else{return n==1 ? 1:0};let am=a.prefix(n).reduce(0,+)/Double(n),bm=b.prefix(n).reduce(0,+)/Double(n);var num=0.0,aa=0.0,bb=0.0;for i in 0..<n{let x=a[i]-am,y=b[i]-bm;num+=x*y;aa+=x*x;bb+=y*y};let d=sqrt(aa*bb);return d<=1e-30 ? (zip(a.prefix(n),b.prefix(n)).allSatisfy{abs($0-$1)<=1e-12} ? 1:0) : max(-1,min(1,num/d))}
    static func mean(_ x:[Double])->Double{x.isEmpty ? 0:x.reduce(0,+)/Double(x.count)}
    static func median(_ x:[Double])->Double?{guard !x.isEmpty else{return nil};let s=x.sorted(),m=s.count/2;return s.count%2==0 ? (s[m-1]+s[m])/2:s[m]}
    static func percentile95(_ x:[Double])->Double{guard !x.isEmpty else{return 0};let s=x.sorted(),i=min(s.count-1,Int((0.95*Double(s.count-1)).rounded(.up)));return s[i]}
    static func centsError(actualRatio:Double,expectedRatio:Double)->Double{guard actualRatio>0,expectedRatio>0 else{return 0};return 1200*log2(actualRatio/expectedRatio)}
    static func powerLikeDBDelta(observed:Double,reference:Double)->Double{10*log10(max(observed,1e-12))-10*log10(max(reference,1e-12))}
}
