import Foundation

// MARK: - Cepstral envelope streaming analyzer (AW10-compatible report)

public enum Lane3LongTrackCepstralEnvelopeDifferentialAnalyzer {
    private struct Complex { var real:Double; var imag:Double }
    private struct Aligned {let referenceStart:Int64;let observedStart:Int64;let count:Int64}
    public static func analyze(reference:any Lane3PCMChunkReadable, observed:any Lane3PCMChunkReadable, globalLagFrames:Int=0, configuration c:Lane3CepstralEnvelopeConfiguration=Lane3CepstralEnvelopeConfiguration(), chunkFrames:Int=16_384) throws -> Lane3CepstralEnvelopeDifferentialReport {
        _ = try Lane3LongTrackPCMAccess.validatePair(reference:reference,observed:observed,chunkFrames:chunkFrames);try validate(c,sampleRate:reference.sampleRate)
        let a=aligned(reference.frameCount,observed.frameCount,globalLagFrames);guard a.count>=Int64(c.windowSize) else{throw Lane3LongTrackEvidenceError.insufficientComparableFrames}
        let starts=selectedStarts(a.count,c),window=hann(c.windowSize);var observations:[Lane3CepstralEnvelopeWindowObservation]=[],refAgg:[Double]?,obsAgg:[Double]?
        for local in starts{let rs=a.referenceStart+local,os=a.observedStart+local,rf=try Lane3LongTrackPCMAccess.readMono(reference,start:rs,count:c.windowSize).samples,of=try Lane3LongTrackPCMAccess.readMono(observed,start:os,count:c.windowSize).samples;if rms(rf)<c.minimumWindowRMS && rms(of)<c.minimumWindowRMS{continue};let rp=powerSpectrum(rf,window),op=powerSpectrum(of,window),range=analysisRange(reference.sampleRate,c,min(rp.count,op.count));guard range.count>=c.cepstralCoefficientCount+2 else{continue};let rl=range.map{10*log10(max(rp[$0],1e-20))},ol=range.map{10*log10(max(op[$0],1e-20))},re=lowOrderEnvelope(rl,c.cepstralCoefficientCount),oe=lowOrderEnvelope(ol,c.cepstralCoefficientCount),nr=removeMean(re),no=removeMean(oe),rt=spectralTilt(re,range,reference.sampleRate,c.windowSize),ot=spectralTilt(oe,range,reference.sampleRate,c.windowSize);observations.append(.init(referenceStartFrame:rs,observedStartFrame:os,envelopeRMSEDB:rmsDifference(nr,no),envelopeCorrelation:correlation(nr,no),spectralTiltDeltaDBPerOctave:ot-rt));if refAgg==nil{refAgg=re;obsAgg=oe}else{for i in re.indices{refAgg![i]+=re[i];obsAgg![i]+=oe[i]}}}
        guard !observations.isEmpty,var ra=refAgg,var oa=obsAgg else{throw Lane3LongTrackEvidenceError.insufficientComparableFrames};let divisor=Double(observations.count);ra=ra.map{$0/divisor};oa=oa.map{$0/divisor};let range=analysisRange(reference.sampleRate,c,c.windowSize/2+1),peaks=matchPeaks(ra,oa,range,reference.sampleRate,c.windowSize,c.formantPeakLimit),errors=peaks.map{abs($0.frequencyErrorCents)},rmsErrors=observations.map(\.envelopeRMSEDB),rn=try Lane3LongTrackPCMAccess.countNonFinite(reference,chunkFrames:chunkFrames),on=try Lane3LongTrackPCMAccess.countNonFinite(observed,chunkFrames:chunkFrames)
        return .init(evidenceScope:"LANE3_CEPSTRAL_ENVELOPE_FORMANT_PROXY_NON_PARITY",globalLagFramesApplied:globalLagFrames,windowsAnalyzed:observations.count,cepstralCoefficientCount:c.cepstralCoefficientCount,meanEnvelopeRMSEDB:mean(rmsErrors),p95EnvelopeRMSEDB:p95(rmsErrors),meanEnvelopeCorrelation:mean(observations.map(\.envelopeCorrelation)),meanAbsoluteSpectralTiltDeltaDBPerOctave:mean(observations.map{abs($0.spectralTiltDeltaDBPerOctave)}),formantPeakMatches:peaks,medianAbsoluteFormantPeakErrorCents:median(errors),p95AbsoluteFormantPeakErrorCents:errors.isEmpty ? nil:p95(errors),referenceNonFiniteSampleCount:rn,observedNonFiniteSampleCount:on,windowObservations:observations,standardizedPerceptualClaimAllowed:false,formantPreservationClaimAllowed:false,parityPromotionAllowed:false)
    }
    private static func validate(_ c:Lane3CepstralEnvelopeConfiguration,sampleRate:Double)throws{guard c.windowSize>0&&(c.windowSize&(c.windowSize-1))==0,c.windowSize>=256,c.windowSize<=16384,c.hopSize>0,c.hopSize<=c.windowSize,c.minimumFrequencyHz.isFinite,c.minimumFrequencyHz>0,c.maximumFrequencyHz.isFinite,c.maximumFrequencyHz>c.minimumFrequencyHz,c.maximumFrequencyHz<=sampleRate/2,c.cepstralCoefficientCount>=4,c.cepstralCoefficientCount<c.windowSize/4,c.minimumWindowRMS.isFinite,c.minimumWindowRMS>=0,c.maximumWindows>0,c.formantPeakLimit>0 else{throw Lane3LongTrackEvidenceError.invalidConfiguration}}
    private static func aligned(_ r:Int64,_ o:Int64,_ lag:Int)->Aligned{let rs=Int64(max(0,-lag)),os=Int64(max(0,lag));return .init(referenceStart:rs,observedStart:os,count:max(0,min(r-rs,o-os)))}
    private static func selectedStarts(_ count:Int64,_ c:Lane3CepstralEnvelopeConfiguration)->[Int64]{var s:[Int64]=[],x:Int64=0;while x+Int64(c.windowSize)<=count{s.append(x);x+=Int64(c.hopSize)};guard s.count>c.maximumWindows else{return s};if c.maximumWindows==1{return[s[s.count/2]]};return(0..<c.maximumWindows).map{let p=Double($0)*Double(s.count-1)/Double(c.maximumWindows-1);return s[Int(p.rounded())]}}
    private static func hann(_ n:Int)->[Double]{(0..<n).map{0.5-0.5*cos(2*Double.pi*Double($0)/Double(n-1))}}
    private static func powerSpectrum(_ x:[Double],_ w:[Double])->[Double]{var v=x.indices.map{Complex(real:x[$0]*w[$0],imag:0)};fft(&v);return(0...x.count/2).map{max(0,v[$0].real*v[$0].real+v[$0].imag*v[$0].imag)}}
    private static func fft(_ v:inout[Complex]){let n=v.count;var j=0;if n>1{for i in 1..<(n-1){var bit=n>>1;while j&bit != 0{j^=bit;bit>>=1};j^=bit;if i<j{v.swapAt(i,j)}}};var len=2;while len<=n{let a = -2*Double.pi/Double(len),wl=Complex(real:cos(a),imag:sin(a));var s=0;while s<n{var w=Complex(real:1,imag:0);for o in 0..<(len/2){let e=s+o,q=e+len/2,odd=mul(v[q],w),even=v[e];v[e] = .init(real:even.real+odd.real,imag:even.imag+odd.imag);v[q] = .init(real:even.real-odd.real,imag:even.imag-odd.imag);w=mul(w,wl)};s+=len};len<<=1}}
    private static func mul(_ a:Complex,_ b:Complex)->Complex{.init(real:a.real*b.real-a.imag*b.imag,imag:a.real*b.imag+a.imag*b.real)}
    private static func analysisRange(_ sr:Double,_ c:Lane3CepstralEnvelopeConfiguration,_ bins:Int)->Range<Int>{let hz=sr/Double(c.windowSize),l=max(1,Int(ceil(c.minimumFrequencyHz/hz))),u=min(bins-1,Int(floor(c.maximumFrequencyHz/hz)));return l..<max(l,u+1)}
    private static func lowOrderEnvelope(_ input:[Double],_ cc:Int)->[Double]{let n=input.count,r=min(cc,n);var coef=[Double](repeating:0,count:r);for k in 0..<r{for i in 0..<n{coef[k]+=input[i]*cos(Double.pi*(Double(i)+0.5)*Double(k)/Double(n))}};var out=[Double](repeating:0,count:n);for i in 0..<n{var s=coef[0]/Double(n);if r>1{for k in 1..<r{s+=(2/Double(n))*coef[k]*cos(Double.pi*(Double(i)+0.5)*Double(k)/Double(n))}};out[i]=s};return out}
    private static func removeMean(_ x:[Double])->[Double]{let m=mean(x);return x.map{$0-m}}
    private static func rms(_ x:[Double])->Double{x.isEmpty ? 0:sqrt(x.reduce(0){$0+$1*$1}/Double(x.count))}
    private static func rmsDifference(_ a:[Double],_ b:[Double])->Double{let n=min(a.count,b.count);guard n>0 else{return 0};var s=0.0;for i in 0..<n{s+=pow(a[i]-b[i],2)};return sqrt(s/Double(n))}
    private static func correlation(_ a:[Double],_ b:[Double])->Double{let n=min(a.count,b.count);guard n>=2 else{return 0};let am=a.prefix(n).reduce(0,+)/Double(n),bm=b.prefix(n).reduce(0,+)/Double(n);var num=0.0,aa=0.0,bb=0.0;for i in 0..<n{let x=a[i]-am,y=b[i]-bm;num+=x*y;aa+=x*x;bb+=y*y};let d=sqrt(aa*bb);return d>1e-20 ? max(-1,min(1,num/d)):1}
    private static func spectralTilt(_ e:[Double],_ range:Range<Int>,_ sr:Double,_ window:Int)->Double{guard e.count>=2 else{return 0};let hz=sr/Double(window);var x:[Double]=[],y:[Double]=[];for i in e.indices{let f=Double(range.lowerBound+i)*hz;if f>0{x.append(log2(f));y.append(e[i])}};let xm=mean(x),ym=mean(y);var n=0.0,d=0.0;for i in x.indices{n+=(x[i]-xm)*(y[i]-ym);d+=pow(x[i]-xm,2)};return d>1e-20 ? n/d:0}
    private static func matchPeaks(_ r:[Double],_ o:[Double],_ range:Range<Int>,_ sr:Double,_ window:Int,_ limit:Int)->[Lane3FormantPeakObservation]{let rp=peaks(r,range,sr,window,limit),op=peaks(o,range,sr,window,limit);var used=Set<Int>(),out:[Lane3FormantPeakObservation]=[];for ref in rp{var bi:Int?,be=Double.infinity;for(i,v)in op.enumerated() where !used.contains(i){let e=abs(1200*log2(v/ref));if e<be{be=e;bi=i}};if let bi,be<=600{used.insert(bi);out.append(.init(referenceFrequencyHz:ref,observedFrequencyHz:op[bi],frequencyErrorCents:1200*log2(op[bi]/ref)))}};return out}
    private static func peaks(_ e:[Double],_ range:Range<Int>,_ sr:Double,_ window:Int,_ limit:Int)->[Double]{guard e.count>=3 else{return[]};let hz=sr/Double(window);var f:[(Double,Double)]=[];for i in 1..<(e.count-1) where e[i]>e[i-1]&&e[i]>=e[i+1]{f.append((Double(range.lowerBound+i)*hz,e[i]))};return f.sorted{$0.1>$1.1}.prefix(limit).map{$0.0}.sorted()}
    private static func mean(_ x:[Double])->Double{x.isEmpty ? 0:x.reduce(0,+)/Double(x.count)}
    private static func median(_ x:[Double])->Double?{guard !x.isEmpty else{return nil};let s=x.sorted(),m=s.count/2;return s.count%2==0 ? (s[m-1]+s[m])/2:s[m]}
    private static func p95(_ x:[Double])->Double{guard !x.isEmpty else{return 0};let s=x.sorted(),i=min(s.count-1,Int((0.95*Double(s.count-1)).rounded(.up)));return s[i]}
}
