const SUBJECTS=["公衆衛生看護学概論","公衆衛生看護方法論I","公衆衛生看護方法論II","対象別公衆衛生看護活動論","学校保健・産業保健","健康危機管理","公衆衛生看護管理論","疫学","保健統計","保健医療福祉行政論"];
const QUESTIONS=[
{id:"P-A1",subject:"公衆衛生看護学概論",topic:"地域診断",q:"地域診断を深めるために、健康指標とあわせて確認する情報として最も適切なのはどれか。",c:["全国平均だけ","住民の生活環境・地域資源・地区差","担当者の印象だけ","一人の既往歴だけ"],a:1,e:"地域診断では健康状態だけでなく、生活環境、地域資源、住民の声、地区ごとの分布などを組み合わせて地域課題を捉える。",m:"地域診断は『健康状態＋生活環境＋地域資源＋住民の声』で見る。",s:"厚生労働省 令和8年5月15日 保健師活動通知",base:"基準日 2026-08-13"},
{id:"P-B1",subject:"公衆衛生看護方法論I",topic:"行動変容",q:"『来週から夕食後に20分歩いてみたい』と話す人への支援として最も適切なのはどれか。",c:["知識だけを追加で説明する","具体的な実行方法と振り返り方を一緒に決める","本人の意思にかかわらず目標を変更する","行動開始までは支援しない"],a:1,e:"行動を変える意向と具体的計画がある場合は、実行可能な目標、障壁への対処、振り返り方法を具体化する支援が有効である。",m:"行動する意思がある人には、実行できる計画まで具体化する。",s:"厚生労働省 標準的な健診・保健指導プログラム",base:"基準日 2026-08-13"},
{id:"P-C1",subject:"公衆衛生看護方法論II",topic:"プロセス評価",q:"保健指導の案内600人、申込180人、初回面接150人、継続完了90人だった。プロセス評価でまず見るのはどれか。",c:["10年後の死亡率","各段階の離脱がどこで起きたか","全国の平均寿命","会議資料の枚数"],a:1,e:"プロセス評価では、案内、申込、参加、継続など実施過程を分解して、どの段階が事業のボトルネックになっているか確認する。",m:"プロセス評価＝入口から継続まで、どこで落ちたかを見る。",s:"厚生労働省 標準的な健診・保健指導プログラム",base:"基準日 2026-08-13"},
{id:"P-D1",subject:"対象別公衆衛生看護活動論",topic:"難病患者支援",q:"在宅療養する難病患者と家族への保健師支援として最も適切なのはどれか。",c:["病状だけを確認する","病状・生活・家族負担・制度・地域資源を把握して支援を調整する","家族の希望を確認しない","状態が安定すれば災害時の備えは不要とする"],a:1,e:"難病患者の地域生活では医療だけでなく、生活、家族の介護負担、制度利用、地域資源や災害時の備えまで包括的に捉える。",m:"難病支援は『病気＋生活＋家族＋制度＋地域資源』。",s:"厚生労働省 難病対策",base:"基準日 2026-08-13"},
{id:"P-E1",subject:"学校保健・産業保健",topic:"職域健診",q:"事業者が定期健康診断で所見を認めた後の対応として適切なのはどれか。",c:["結果を氏名付きで掲示する","医師等の意見を踏まえて必要な就業上の措置や保健指導へつなげる","本人へ結果を知らせない","全員に同じ就業制限を行う"],a:1,e:"健康診断は実施して終わりではなく、結果に応じて医師等の意見を聴き、必要な就業上の措置や保健指導へつなげる。",m:"職域健診は『結果→医師意見→必要な事後措置』まで。",s:"厚生労働省 労働安全衛生・健康診断",base:"基準日 2026-08-13"},
{id:"P-F1",subject:"健康危機管理",topic:"平時準備",q:"災害時の健康危機対応を機能させるため、平時に最も優先する取組はどれか。",c:["発災後に連絡手順を考える","関係機関の役割・情報共有・指揮連絡・受援手順を決めて訓練する","名簿だけ作成する","保健部門だけで完結させる"],a:1,e:"健康危機管理では平時から役割分担、情報共有、連絡・指揮系統、受援体制を整え、訓練で実効性を検証して改善する。",m:"危機対応は平時に『役割・情報・連絡・受援』を決めて訓練する。",s:"厚生労働省 地域保健対策の推進に関する基本的な指針",base:"基準日 2026-08-13"},
{id:"P-H1",subject:"疫学",topic:"オッズ比",scenario:"架空のQ市で患者40人と対照60人のイベント参加歴を調べた。患者は参加あり30・なし10、対照は参加あり20・なし40だった。",q:"イベント参加と発症のオッズ比はいくつか。",c:["1.5","3","6","12"],a:2,e:"症例対照研究のオッズ比は ad÷bc で計算する。この例では30×40÷（10×20）＝6となる。",m:"2×2表のオッズ比は ad÷bc。",s:"CDC Principles of Epidemiology",base:"基準日 2026-08-13"},
{id:"P-I1",subject:"保健統計",topic:"健康寿命",scenario:"架空のA県では平均寿命84年、健康寿命75年だった。",q:"この2指標の差の解釈として最も適切なのはどれか。",c:["75歳を超えると全員要介護になる","健康上の制限なく生活する期間と生存期間には差があることを集団指標として示す","個人の余命を9年と確定する","罹患率が9%である"],a:1,e:"平均寿命と健康寿命はいずれも集団指標であり、差は個人の将来を確定するものではない。健康で生活できる期間を延ばす施策評価の参考となる。",m:"平均寿命と健康寿命の差を、個人の余命と読み替えない。",s:"厚生労働省 健康寿命の定義と算出方法",base:"基準日 2026-08-13"}
];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={target:8,index:0,session:[],answers:[],mode:"標準スプリント",history:JSON.parse(localStorage.getItem("hokenshiPrototypeHistory")||"[]"),weak:JSON.parse(localStorage.getItem("hokenshiPrototypeWeak")||"{}")};
function persist(){localStorage.setItem("hokenshiPrototypeHistory",JSON.stringify(state.history));localStorage.setItem("hokenshiPrototypeWeak",JSON.stringify(state.weak));}
function show(name){$$('.screen').forEach(x=>x.classList.toggle('active',x.dataset.screen===name));$('#tabbar').classList.toggle('hidden',['quiz','answer','result'].includes(name));$$('#tabbar button').forEach(b=>b.classList.toggle('selected',b.dataset.go===name));if(name==='record')renderRecord();scrollTo({top:0,behavior:'smooth'});}
function shuffled(arr){return [...arr].sort(()=>Math.random()-.5)}
function buildSession(filter){let pool=filter?QUESTIONS.filter(filter):QUESTIONS;if(!pool.length)pool=QUESTIONS;let out=[];while(out.length<state.target)out.push(...shuffled(pool));return out.slice(0,state.target)}
function start(filter,mode){state.mode=mode||"標準スプリント";state.session=buildSession(filter);state.index=0;state.answers=[];renderQuestion();show('quiz')}
function renderQuestion(){const q=state.session[state.index];$('#quiz-mode').textContent=state.mode;$('#quiz-progress').textContent=`${state.index+1} / ${state.session.length}`;$('#quiz-progress-bar').style.width=`${(state.index+1)/state.session.length*100}%`;$('#question-subject').textContent=q.subject;$('#question-topic').textContent=q.topic;$('#question-text').textContent=q.q;const sc=$('#scenario-text');sc.hidden=!q.scenario;sc.textContent=q.scenario||'';const wrap=$('#choices');wrap.innerHTML='';q.c.forEach((choice,i)=>{const b=document.createElement('button');b.className='choice';b.innerHTML=`<span class="num">${i+1}</span>${choice}`;b.onclick=()=>answer(i,false);wrap.appendChild(b)})}
function answer(selected,unknown){const q=state.session[state.index],correct=!unknown&&selected===q.a;state.answers.push({id:q.id,correct,unknown,subject:q.subject,at:new Date().toISOString()});if(correct){if(state.weak[q.id]){state.weak[q.id].streak=(state.weak[q.id].streak||0)+1;if(state.weak[q.id].streak>=3)delete state.weak[q.id]}}else state.weak[q.id]={streak:0,subject:q.subject,topic:q.topic};persist();$('#answer-mark').textContent=correct?'○':'×';$('#answer-mark').classList.toggle('wrong',!correct);$('#answer-subject').textContent=q.subject;$('#answer-question').textContent=q.q;$('#answer-choice').textContent=unknown?`わからない → 正解：${q.c[q.a]}`:`あなたの回答：${q.c[selected]}　／　正解：${q.c[q.a]}`;$('#answer-explanation').textContent=q.e;$('#answer-memory').textContent=q.m;$('#answer-source').textContent=q.s;$('#answer-baseline').textContent=q.base;show('answer')}
function next(){state.index++;if(state.index<state.session.length){renderQuestion();show('quiz')}else finish()}
function finish(){state.history.push(...state.answers);persist();const score=state.answers.filter(x=>x.correct).length,unknown=state.answers.filter(x=>x.unknown).length;$('#result-score').textContent=`${score} / ${state.answers.length}`;$('#result-unknown').textContent=unknown;$('#result-weak').textContent=state.answers.length-score;$('#today-count').textContent=Math.min(8,state.answers.length);document.querySelector('.ring').style.background=`conic-gradient(var(--indigo) ${Math.min(1,state.answers.length/8)*360}deg,rgba(37,59,110,.10) 0deg)`;show('result')}
function renderRecord(){const total=state.history.length,correct=state.history.filter(x=>x.correct).length;$('#record-total').textContent=`${total}問`;$('#record-accuracy').textContent=total?`${Math.round(correct/total*100)}%`:'—';const weak=Object.values(state.weak);$('#weak-count').textContent=`${weak.length}問`;$('#weak-summary').textContent=weak.length?`${[...new Set(weak.map(x=>x.subject))].slice(0,3).join('・')}を中心に復習対象があります。`:'まだ苦手問題はありません。';const heat=$('#heatmap');heat.innerHTML='';for(let i=0;i<35;i++){const el=document.createElement('i');if(i>29&&total)el.className=['on1','on2','on3'][Math.min(2,Math.floor(total/4))];heat.appendChild(el)}}
function renderSubjects(){const grid=$('#subject-grid');SUBJECTS.forEach(s=>{const b=document.createElement('button');b.className='subject-button';b.textContent=s;b.onclick=()=>start(q=>q.subject===s,s);grid.appendChild(b)})}
$('#start-sprint').onclick=()=>start(null,'標準スプリント');$('#start-weak').onclick=()=>{const ids=new Set(Object.keys(state.weak));start(q=>ids.has(q.id),'苦手復習')};$('#unknown').onclick=()=>answer(null,true);$('#next-question').onclick=next;$('#quiz-close').onclick=()=>show('home');$$('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));$$('#target-selector button').forEach(b=>b.onclick=()=>{state.target=Number(b.dataset.target);$$('#target-selector button').forEach(x=>x.classList.toggle('selected',x===b))});$('#export-record').onclick=()=>{const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),history:state.history,weak:state.weak},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='hokenshi-prototype-record.json';a.click();URL.revokeObjectURL(a.href)};renderSubjects();renderRecord();
