'use strict';
const STORAGE_KEY = 'manabiSprint.tourokuHanbaisha.v02';
const ACTIVE_KEY = 'manabiSprint.tourokuHanbaisha.active.v02';
const state = { mode:'all', sessionQuestions:[], index:0, answers:[], startedAt:0, timerId:null, answered:false, selectedIndex:null };
const $ = id => document.getElementById(id);
const screens={home:$('homeScreen'),quiz:$('quizScreen'),result:$('resultScreen'),history:$('historyScreen'),settings:$('settingsScreen')};

function defaultProgress(){return{rounds:0,lastScore:null,wrongIds:[],lastDuration:0,updatedAt:null}}
function loadProgress(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY));if(!p||typeof p!=='object')return defaultProgress();return{rounds:Number.isFinite(p.rounds)?p.rounds:0,lastScore:Number.isFinite(p.lastScore)?p.lastScore:null,wrongIds:Array.isArray(p.wrongIds)?p.wrongIds.filter(id=>QUESTIONS.some(q=>q.id===id)):[],lastDuration:Number.isFinite(p.lastDuration)?p.lastDuration:0,updatedAt:typeof p.updatedAt==='string'?p.updatedAt:null}}catch(_){localStorage.removeItem(STORAGE_KEY);return defaultProgress()}}
function saveProgress(p){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(p))}catch(_){}}
function saveActive(){if(!state.sessionQuestions.length)return;try{localStorage.setItem(ACTIVE_KEY,JSON.stringify({mode:state.mode,ids:state.sessionQuestions.map(q=>q.id),index:state.index,answers:state.answers,startedAt:state.startedAt,answered:state.answered,selectedIndex:state.selectedIndex}))}catch(_){}}
function clearActive(){try{localStorage.removeItem(ACTIVE_KEY)}catch(_){}}
function loadActive(){try{const a=JSON.parse(localStorage.getItem(ACTIVE_KEY));if(!a||!Array.isArray(a.ids)||!a.ids.length)return null;const qs=a.ids.map(id=>QUESTIONS.find(q=>q.id===id)).filter(Boolean);if(!qs.length||!Number.isInteger(a.index)||a.index<0||a.index>=qs.length)return null;return{mode:a.mode==='wrong'?'wrong':'all',questions:qs,index:a.index,answers:Array.isArray(a.answers)?a.answers:[],startedAt:Number.isFinite(a.startedAt)?a.startedAt:Date.now(),answered:!!a.answered,selectedIndex:Number.isInteger(a.selectedIndex)?a.selectedIndex:null}}catch(_){clearActive();return null}}
function formatTime(sec){const s=Math.max(0,Math.floor(sec));return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function setNav(name){document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.nav===name))}
function showScreen(name){Object.entries(screens).forEach(([k,el])=>el.classList.toggle('hidden',k!==name));$('bottomNav').classList.toggle('hidden',name==='quiz'||name==='result');$('mainTopbar').classList.toggle('hidden',name==='quiz');if(name==='home')setNav('home');if(name==='history')setNav('history');if(name==='settings')setNav('settings');window.scrollTo({top:0,behavior:'smooth'})}
function refreshHome(){const p=loadProgress();$('roundCount').textContent=p.rounds;$('lastScore').textContent=p.lastScore===null?'—':`${p.lastScore}%`;$('wrongCount').textContent=p.wrongIds.length;$('reviewButton').disabled=p.wrongIds.length===0;const a=loadActive();$('continueButton').classList.toggle('hidden',!a);if(a)$('continueMeta').textContent=`${a.index+1}/${a.questions.length}問目から再開`}
function refreshHistory(){const p=loadProgress();$('historyRounds').textContent=`${p.rounds}回`;$('historyScore').textContent=p.lastScore===null?'—':`${p.lastScore}%`;$('historyDuration').textContent=p.lastDuration?formatTime(p.lastDuration):'—';$('historyWrong').textContent=`${p.wrongIds.length}問`}

function startSession(mode){const p=loadProgress();const selected=mode==='wrong'?p.wrongIds.map(id=>QUESTIONS.find(q=>q.id===id)).filter(Boolean):QUESTIONS.slice();if(!selected.length)return;state.mode=mode;state.sessionQuestions=selected;state.index=0;state.answers=[];state.startedAt=Date.now();state.answered=false;state.selectedIndex=null;clearInterval(state.timerId);state.timerId=setInterval(updateTimer,500);saveActive();showScreen('quiz');renderQuestion()}
function resumeSession(){const a=loadActive();if(!a)return;state.mode=a.mode;state.sessionQuestions=a.questions;state.index=a.index;state.answers=a.answers;state.startedAt=a.startedAt;state.answered=a.answered;state.selectedIndex=a.selectedIndex;clearInterval(state.timerId);state.timerId=setInterval(updateTimer,500);showScreen('quiz');renderQuestion(true)}
function updateTimer(){if(state.startedAt)$('timer').textContent=formatTime((Date.now()-state.startedAt)/1000)}

function renderQuestion(fromResume=false){const q=state.sessionQuestions[state.index];$('progressLabel').textContent=`${state.index+1} / ${state.sessionQuestions.length}`;$('progressBar').style.width=`${((state.index+1)/state.sessionQuestions.length)*100}%`;$('questionTag').textContent=`${q.chapter} ・ ${q.topic}`;$('questionText').textContent=q.question;$('feedback').className='feedback';$('detailPanel').open=false;const choices=$('choices');choices.replaceChildren();q.choices.forEach((text,i)=>{const b=document.createElement('button');b.type='button';b.className='choice';b.dataset.index=i;b.innerHTML=`<span class="choice-letter">${String.fromCharCode(65+i)}</span><span></span>`;b.lastElementChild.textContent=text;b.addEventListener('click',()=>selectChoice(i));choices.appendChild(b)});
  if(!fromResume){state.answered=false;state.selectedIndex=null}else if(state.answered){paintAnswered(q)}else if(state.selectedIndex!==null){paintSelected()}
  $('answerButton').disabled=!state.answered&&state.selectedIndex===null;$('answerButton').textContent=state.answered?(state.index===state.sessionQuestions.length-1?'結果を見る':'次の問題へ'):'回答する';updateTimer();saveActive()}
function paintSelected(){[...$('choices').children].forEach((b,i)=>b.classList.toggle('selected',i===state.selectedIndex))}
function selectChoice(i){if(state.answered)return;state.selectedIndex=i;paintSelected();$('answerButton').disabled=false;saveActive()}
function confirmAnswer(){if(state.answered){nextQuestion();return}if(state.selectedIndex===null)return;const q=state.sessionQuestions[state.index];const isCorrect=state.selectedIndex===q.answer;state.answers.push({id:q.id,selectedIndex:state.selectedIndex,isCorrect});state.answered=true;paintAnswered(q);$('feedbackTitle').textContent=isCorrect?'正解です':`不正解です。正解は ${String.fromCharCode(65+q.answer)}。`;$('feedbackPoint').textContent=q.point;$('detailText').textContent=q.detail;$('feedback').className=`feedback show ${isCorrect?'ok':'ng'}`;$('answerButton').textContent=state.index===state.sessionQuestions.length-1?'結果を見る':'次の問題へ';saveActive()}
function paintAnswered(q){[...$('choices').children].forEach((b,i)=>{b.disabled=true;b.classList.remove('selected');if(i===q.answer)b.classList.add('correct');else if(i===state.selectedIndex)b.classList.add('incorrect');else b.classList.add('dimmed')});const a=state.answers.findLast?state.answers.findLast(x=>x.id===q.id):[...state.answers].reverse().find(x=>x.id===q.id);const ok=a?a.isCorrect:state.selectedIndex===q.answer;$('feedbackTitle').textContent=ok?'正解です':`不正解です。正解は ${String.fromCharCode(65+q.answer)}。`;$('feedbackPoint').textContent=q.point;$('detailText').textContent=q.detail;$('feedback').className=`feedback show ${ok?'ok':'ng'}`}
function nextQuestion(){if(!state.answered)return;if(state.index<state.sessionQuestions.length-1){state.index++;state.answered=false;state.selectedIndex=null;renderQuestion()}else finishSession()}
function finishSession(){clearInterval(state.timerId);const duration=Math.round((Date.now()-state.startedAt)/1000);const correct=state.answers.filter(a=>a.isCorrect).length;const total=state.sessionQuestions.length;const score=Math.round(correct/total*100);const wrongIds=state.answers.filter(a=>!a.isCorrect).map(a=>a.id);const p=loadProgress();const next={rounds:p.rounds+1,lastScore:score,wrongIds:state.mode==='all'?wrongIds:Array.from(new Set([...p.wrongIds.filter(id=>!state.answers.some(a=>a.id===id)),...wrongIds])),lastDuration:duration,updatedAt:new Date().toISOString()};saveProgress(next);clearActive();renderResult({correct,total,score,duration,wrongIds});showScreen('result')}
function renderResult(r){$('resultScore').textContent=`${r.score}%`;$('resultFraction').textContent=`${r.correct} / ${r.total}`;$('resultCorrect').textContent=r.correct;$('resultTime').textContent=formatTime(r.duration);$('resultWrong').textContent=r.wrongIds.length;$('resultTitle').textContent=state.mode==='wrong'?'復習を完了しました':'12問、完了しました';$('resultMessage').textContent=r.score===100?'全問正解です。この章の基礎を一周できました。':r.score>=75?'あと少しです。間違えた論点だけを短く復習できます。':'今回の誤答が、次に覚える範囲です。ここからもう一周できます。';const list=$('wrongList');list.replaceChildren();r.wrongIds.forEach(id=>{const q=QUESTIONS.find(x=>x.id===id);if(!q)return;const div=document.createElement('div');div.className='wrong-item';div.innerHTML='<div class="wrong-id"></div><div class="wrong-topic"></div>';div.children[0].textContent=q.id;div.children[1].textContent=q.topic;list.appendChild(div)});$('wrongSection').classList.toggle('hidden',!r.wrongIds.length);$('retryWrongButton').disabled=!r.wrongIds.length}
function leaveQuiz(){clearInterval(state.timerId);saveActive();showScreen('home');refreshHome()}
function resetProgress(){if(!confirm('学習履歴と途中データをすべて削除しますか？'))return;localStorage.removeItem(STORAGE_KEY);clearActive();refreshHome();refreshHistory()}

$('startButton').addEventListener('click',()=>startSession('all'));$('continueButton').addEventListener('click',resumeSession);$('reviewButton').addEventListener('click',()=>startSession('wrong'));$('historyShortcut').addEventListener('click',()=>{refreshHistory();showScreen('history')});$('quitButton').addEventListener('click',leaveQuiz);$('answerButton').addEventListener('click',confirmAnswer);$('retryWrongButton').addEventListener('click',()=>startSession('wrong'));$('retryAllButton').addEventListener('click',()=>startSession('all'));$('homeButton').addEventListener('click',()=>{showScreen('home');refreshHome()});$('resetButton').addEventListener('click',resetProgress);
document.querySelectorAll('.nav-btn').forEach(btn=>btn.addEventListener('click',()=>{const n=btn.dataset.nav;if(n==='home'){showScreen('home');refreshHome()}else if(n==='study'){const a=loadActive();a?resumeSession():startSession('all')}else if(n==='history'){refreshHistory();showScreen('history')}else if(n==='settings'){showScreen('settings')}}));
window.addEventListener('error',()=>{clearInterval(state.timerId);showScreen('home');refreshHome()});
refreshHome();refreshHistory();
