(()=>{
const Q=window.KANGOSHI_QUESTIONS||[], META=window.KANGOSHI_CONTENT_META||{}, KEY='kangoshiSprintStateV02';
const app=document.getElementById('app'); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const base=()=>({weak:{},history:[],seen:[],resume:null,font:'normal',completed:{}}); let state=load(),session=null,page='home';
function load(){try{return {...base(),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return base()}} function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function font(){document.documentElement.classList.remove('fs-large','fs-xlarge');if(state.font==='large')document.documentElement.classList.add('fs-large');if(state.font==='xlarge')document.documentElement.classList.add('fs-xlarge')}
function shuffle(a){const b=[...a];for(let i=b.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function pick(pool,n){const seen=new Set(state.seen);return [...shuffle(pool.filter(x=>!seen.has(x.id))),...shuffle(pool.filter(x=>seen.has(x.id)))].slice(0,Math.min(n,pool.length))}
const header=(title,c='')=>`<div class="header"><button data-action="home">ホーム</button><h1>${esc(title)}</h1>${c?`<span class="counter">${esc(c)}</span>`:''}</div>`;
const tabs=a=>`<nav class="tabbar"><button data-tab="home" class="${a==='home'?'active':''}"><span class="ic">⌂</span>ホーム</button><button data-tab="history" class="${a==='history'?'active':''}"><span class="ic">▤</span>学習記録</button><button data-tab="settings" class="${a==='settings'?'active':''}"><span class="ic">⚙</span>設定</button></nav>`;
function current(){return Q.find(x=>x.id===session?.ids[session.index])} function weakPool(){return Object.keys(state.weak).map(id=>Q.find(x=>x.id===id)).filter(Boolean).sort((a,b)=>(state.weak[b.id].misses||0)-(state.weak[a.id].misses||0))}
function persist(){if(session){state.resume={ids:session.ids,index:session.index,correct:session.correct,results:session.results,label:session.label};save()}}
function start(pool,label,n=12){if(!pool.length)return;const arr=pick(pool,n);session={ids:arr.map(x=>x.id),index:0,correct:0,results:[],label,started:Date.now(),selected:[],answered:false,numericValue:''};page='quiz';persist();render();scrollTo(0,0)}
function resume(){const r=state.resume;if(!r)return;session={...r,started:Date.now(),selected:[],answered:false,numericValue:''};page='quiz';render()}
function render(){font();if(page==='quiz')return quiz();if(page==='result')return result();if(page==='history')return history();if(page==='settings')return settings();if(page==='subjects')return subjects();if(page==='paywall')return paywall();home()}
function home(){const wc=Object.keys(state.weak).length;const resumeCard=state.resume?`<button class="resume" data-action="resume"><span class="icon">↻</span><span><span class="name">続きから</span><span class="meta">${esc(state.resume.label)}・${state.resume.index+1}/${state.resume.ids.length}問</span></span></button>`:'';
 app.innerHTML=`<section class="home-top"><div class="kicker">学びスプリント</div><div class="app-name">看護師国家試験</div><p class="lead">今日の12問を、合格の1歩に。</p></section>${resumeCard}<div class="verified-note">第115回の公式試験構成・回答形式を確認済み。MVP問題本文は独自作成で、製品版投入前に専門内容監査を行います。</div><section class="section"><button class="full-btn" data-action="daily"><span class="icon">12</span><span><span class="name">今日の12問</span><span class="meta">必修・一般・状況設定を横断</span></span></button><button class="full-btn" data-action="required"><span class="icon">必</span><span><span class="name">必修12問</span><span class="meta">基本事項を集中反復</span></span></button><button class="full-btn" data-action="weak" ${wc?'':'disabled'}><span class="icon">↺</span><span><span class="name">苦手復習</span><span class="meta">3連続正解で自動解除</span></span><span class="badge">${wc}問</span></button></section><section class="section"><h2>出題区分から学ぶ</h2><div class="category-grid">${cat('必修','required')}${cat('一般','general')}${cat('状況設定','scenario')}</div></section><section class="section"><button class="full-btn" data-action="subjects"><span class="icon">科</span><span><span class="name">科目・領域から学ぶ</span><span class="meta">領域別の解答状況・苦手を確認</span></span></button><button class="full-btn" data-action="mock"><span class="icon">試</span><span><span class="name">本番形式</span><span class="meta">製品版：午前120問＋午後120問</span></span></button><p class="section-note">Safari MVP：60問。単一選択・2つ選択・数値計算の3回答形式に対応。</p></section>${tabs('home')}`}
function cat(name,cls){const count=Q.filter(x=>x.category===name).length;return `<button class="category-card ${cls}" data-category="${name}"><span><strong>${name}</strong><span>${count}問・完答 ${state.completed[name]||0}回</span></span></button>`}
function scenario(q){if(!q.scenario)return'';return `<div class="scenario-box"><div class="scenario-label">状況設定 ${q.scenarioIndex+1}/${q.scenarioTotal}</div>${q.scenarioIndex===0?`<div class="scenario-text">${esc(q.scenario)}</div>`:`<details><summary>状況をもう一度見る</summary><div class="scenario-text">${esc(q.scenario)}</div></details>`}</div>`}
function quiz(){const q=current();if(!q)return finish();const n=session.index+1,total=session.ids.length,done=session.answered,last=session.results.at(-1);let answer='';
 if(q.answerType==='numeric'){
   answer=done?`<div class="numeric-answer">あなたの回答：<b>${esc(last.response)} ${esc(q.unit||'')}</b><br>正答：<b>${esc(q.answer)} ${esc(q.unit||'')}</b></div>`:`<div class="numeric-wrap"><label class="numeric-label" for="numericAnswer">数値を入力</label><div class="numeric-line"><input id="numericAnswer" class="numeric-input" inputmode="decimal" type="number" step="any" value="${esc(session.numericValue)}" aria-label="数値回答"><span class="numeric-unit">${esc(q.unit||'')}</span></div></div><button class="grade" data-action="numeric-grade">採点する</button><button class="dontknow" data-action="unknown">わからない</button>`;
 }else{
   const multi=q.answerType==='multiChoice'; const choices=q.choices.map((c,i)=>{let cls=session.selected.includes(i)?'selected':'';if(done){const ans=Array.isArray(q.answer)?q.answer:[q.answer];if(ans.includes(i))cls='correct';else if(session.selected.includes(i))cls='wrong'}return `<button class="choice ${cls}" data-choice="${i}" ${done?'disabled':''}><span class="num">${i+1}</span><span>${esc(c)}</span></button>`}).join('');
   answer=done?choices:multi?`<div class="select-state">${session.selected.length} / ${q.selectCount} 選択中</div>${choices}<button class="grade" data-action="multi-grade" ${session.selected.length===q.selectCount?'':'disabled'}>採点する</button><button class="dontknow" data-action="unknown">わからない</button>`:`${choices}<button class="dontknow" data-action="unknown">わからない</button>`;
 }
 const feedback=done?`<div class="feedback ${last.correct?'ok':'ng'}"><div class="feedback-title">${last.correct?'正解':'不正解'}</div><span class="learn-label">この問題で覚える一文</span><p class="feedback-point">${esc(q.point)}</p><details><summary>詳しい解説を見る</summary><p class="detail">${esc(q.detail)}</p></details></div><button class="next" data-action="next">${n===total?'結果を見る':'次の問題へ'}</button>`:'';
 const type=q.answerType==='multiChoice'?`<span class="tag multi">${q.selectCount}つ選択</span>`:q.answerType==='numeric'?`<span class="tag multi">数値計算</span>`:'';
 app.innerHTML=`${header(session.label,`${n} / ${total}`)}<section class="quiz"><div class="progress"><div style="width:${Math.round((session.index/total)*100)}%"></div></div><div class="tags"><span class="tag">${esc(q.category)}</span><span class="tag nurse">${esc(q.subject)}</span>${type}</div>${scenario(q)}<div class="qtext">${esc(q.question)}</div>${answer}${feedback}</section>`}
function correct(q,response,unknown){if(unknown)return false;if(q.answerType==='numeric'){const v=Number(response);return Number.isFinite(v)&&Math.abs(v-Number(q.answer))<=Number(q.tolerance||0)}const ans=Array.isArray(q.answer)?[...q.answer].sort():[q.answer];const got=[...response].sort();return ans.length===got.length&&ans.every((v,i)=>v===got[i])}
function grade(response,unknown=false){const q=current();if(!q||session.answered)return;const ok=correct(q,response,unknown);session.answered=true;if(ok)session.correct++;const w=state.weak[q.id];if(ok&&w){w.streak=(w.streak||0)+1;if(w.streak>=3)delete state.weak[q.id]}else if(!ok){state.weak[q.id]={streak:0,misses:(w?.misses||0)+1,lastMiss:Date.now()}}if(!state.seen.includes(q.id))state.seen.push(q.id);session.results.push({id:q.id,correct:ok,unknown,category:q.category,subject:q.subject,response:q.answerType==='numeric'?response:[...response]});persist();render()}
function next(){if(session.index===session.ids.length-1)return finish();session.index++;session.selected=[];session.answered=false;session.numericValue='';persist();render();scrollTo(0,0)}
function finish(){if(!session)return;const r={label:session.label,correct:session.correct,total:session.ids.length,elapsed:Math.max(1,Math.round((Date.now()-session.started)/1000)),at:Date.now(),results:session.results};state.history.unshift(r);state.history=state.history.slice(0,30);const cats=[...new Set(r.results.map(x=>x.category))];if(cats.length===1&&r.results.length===session.ids.length)state.completed[cats[0]]=(state.completed[cats[0]]||0)+1;state.resume=null;save();session.final=r;page='result';render()}
function result(){const r=session?.final||state.history[0];if(!r){page='home';return render()}const rate=Math.round(r.correct/r.total*100),wc=Object.keys(state.weak).length,rr=r.results.filter(x=>x.category==='必修'),req=rr.length?Math.round(rr.filter(x=>x.correct).length/rr.length*100):null;app.innerHTML=`${header('結果')}<div class="result"><div class="result-big">${r.correct} / ${r.total}</div><div class="result-sub">正答率 ${rate}%</div><div class="result-grid"><div class="metric"><b>${rate}%</b><span>正答率</span></div><div class="metric"><b>${Math.floor(r.elapsed/60)}:${String(r.elapsed%60).padStart(2,'0')}</b><span>所要時間</span></div><div class="metric"><b>${wc}</b><span>苦手</span></div></div>${req!==null?`<p class="section-note">必修正答率：${req}%</p>`:''}</div><div class="result-actions"><button class="next" data-action="daily">もう12問</button><button class="secondary" data-action="weak" ${wc?'':'disabled'}>間違えた問題を復習</button><button class="secondary" data-action="home">ホームへ</button></div>`}
function history(){const a=state.history.reduce((s,x)=>s+x.total,0),c=state.history.reduce((s,x)=>s+x.correct,0);app.innerHTML=`${header('学習記録')}<section class="stats"><div class="stat-row"><div class="stat"><b>${a}</b><span>累計解答</span></div><div class="stat"><b>${a?Math.round(c/a*100):0}%</b><span>正答率</span></div><div class="stat"><b>${Object.keys(state.weak).length}</b><span>苦手</span></div></div><div class="history">${state.history.length?state.history.map(x=>`<div class="history-item"><span>${esc(x.label)} ${x.correct}/${x.total}</span><span>${new Date(x.at).toLocaleDateString('ja-JP')}</span></div>`).join(''):`<div class="empty">まだ学習記録はありません。</div>`}</div></section>${tabs('history')}`}
function settings(){app.innerHTML=`${header('設定')}<section class="settings"><div class="setting-card"><h3>文字サイズ</h3><div class="seg"><button data-font="normal" class="${state.font==='normal'?'active':''}">標準</button><button data-font="large" class="${state.font==='large'?'active':''}">大</button><button data-font="xlarge" class="${state.font==='xlarge'?'active':''}">特大</button></div></div><div class="setting-card"><h3>問題データ</h3><p>${esc(META.version||'MVP')}・${Q.length}問。公式試験構成・回答形式は確認済み。個々の医学・看護学内容は製品版投入前に専門監査。</p></div><div class="setting-card"><h3>課金</h3><p>Safariでは購入を実行しません。iOS版はStoreKit 2の正式価格を表示します。</p><button class="secondary" data-action="paywall">課金画面を確認</button></div><div class="setting-card"><h3>学習データ</h3><button class="danger" data-action="reset">学習データをリセット</button></div></section>${tabs('settings')}`}
function subjects(){const g={};Q.forEach(q=>{g[q.subject]??={count:0,seen:0,weak:0};g[q.subject].count++;if(state.seen.includes(q.id))g[q.subject].seen++;if(state.weak[q.id])g[q.subject].weak++});app.innerHTML=`${header('科目・領域から学ぶ')}<section class="section"><div class="subject-list">${Object.entries(g).sort((a,b)=>a[0].localeCompare(b[0],'ja')).map(([n,v])=>`<button class="subject" data-subject="${esc(n)}"><strong>${esc(n)}</strong><span>${v.seen}/${v.count}解答・苦手${v.weak}</span></button>`).join('')}</div></section>${tabs('home')}`}
function paywall(){app.innerHTML=`${header('プレミアム')}<section class="paywall"><div class="paycard"><h2>看護師国試 プレミアム</h2><p>製品版では全問題、苦手復習、詳細履歴、本番形式、更新問題を解放する想定です。</p><div class="plans"><div class="plan"><b>月額</b><span>初回7日無料の候補</span></div><div class="plan"><b>買い切り</b><span>長期利用向け</span></div></div><button class="grade" disabled>Safari MVPでは購入しません</button><div class="disabled-note">iOS実装時にStoreKit 2へ接続し、displayPriceを使用します。</div></div></section>`}
app.addEventListener('input',e=>{if(e.target.id==='numericAnswer'&&session)session.numericValue=e.target.value});
app.addEventListener('click',e=>{const ch=e.target.closest('[data-choice]');if(ch&&page==='quiz'&&!session.answered){const q=current(),i=Number(ch.dataset.choice);if(q.answerType==='singleChoice')return grade([i]);const p=session.selected.indexOf(i);if(p>=0)session.selected.splice(p,1);else if(session.selected.length<q.selectCount)session.selected.push(i);return render()}const a=e.target.closest('[data-action]')?.dataset.action;if(a==='home'){page='home';return render()}if(a==='daily')return start(Q,'今日の12問');if(a==='required')return start(Q.filter(x=>x.category==='必修'),'必修12問');if(a==='weak'){const w=weakPool();if(w.length)return start(w,'苦手復習',Math.min(12,w.length));return}if(a==='resume')return resume();if(a==='multi-grade')return grade(session.selected);if(a==='numeric-grade')return grade(session.numericValue);if(a==='unknown')return grade(current().answerType==='numeric'?'':[],true);if(a==='next')return next();if(a==='subjects'){page='subjects';return render()}if(a==='mock'||a==='paywall'){page='paywall';return render()}if(a==='reset'){if(confirm('学習データを削除しますか？')){state=base();save();page='home';render()}return}const t=e.target.closest('[data-tab]')?.dataset.tab;if(t){page=t;return render()}const c=e.target.closest('[data-category]')?.dataset.category;if(c)return start(Q.filter(x=>x.category===c),`${c}12問`);const s=e.target.closest('[data-subject]')?.dataset.subject;if(s)return start(Q.filter(x=>x.subject===s),s);const f=e.target.closest('[data-font]')?.dataset.font;if(f){state.font=f;save();return render()}});
font();render();
})();
