(()=>{
const Q=window.KANGOSHI_QUESTIONS||[];
const META=window.KANGOSHI_CONTENT_META||{};
const KEY='kangoshiSprintStateV01';
const app=document.getElementById('app');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const defaults=()=>({weak:{},history:[],seen:[],resume:null,font:'normal',completed:{},premium:false});
let state=load();
let session=null;
let page='home';
function load(){try{return {...defaults(),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return defaults()}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function fmtSec(sec){const m=Math.floor(sec/60),s=sec%60;return `${m}:${String(s).padStart(2,'0')}`}
function shuffled(a){const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function picks(pool,n){const seen=new Set(state.seen);const fresh=shuffled(pool.filter(q=>!seen.has(q.id)));const old=shuffled(pool.filter(q=>seen.has(q.id)));return [...fresh,...old].slice(0,Math.min(n,pool.length))}
function applyFont(){document.documentElement.classList.remove('fs-large','fs-xlarge');if(state.font==='large')document.documentElement.classList.add('fs-large');if(state.font==='xlarge')document.documentElement.classList.add('fs-xlarge')}
function header(title,counter=''){return `<div class="header"><button type="button" data-action="home">ホーム</button><h1>${esc(title)}</h1>${counter?`<span class="counter">${esc(counter)}</span>`:''}</div>`}
function tabs(active){return `<nav class="tabbar" aria-label="メインナビ"><button data-tab="home" class="${active==='home'?'active':''}"><span class="ic">⌂</span>ホーム</button><button data-tab="history" class="${active==='history'?'active':''}"><span class="ic">▤</span>学習記録</button><button data-tab="settings" class="${active==='settings'?'active':''}"><span class="ic">⚙</span>設定</button></nav>`}
function render(){applyFont();if(page==='quiz')return renderQuiz();if(page==='result')return renderResult();if(page==='history')return renderHistory();if(page==='settings')return renderSettings();if(page==='subjects')return renderSubjects();if(page==='paywall')return renderPaywall();return renderHome()}
function renderHome(){
 const weakCount=Object.keys(state.weak).length;
 const resume=state.resume&&state.resume.ids?.length?`<button class="resume" data-action="resume"><span class="icon">↻</span><span><span class="name">続きから</span><span class="meta">${esc(state.resume.label)}・${state.resume.index+1}/${state.resume.ids.length}問</span></span></button>`:'';
 const cat=(name,cls,meta)=>`<button class="category-card ${cls}" data-category="${name}"><span><strong>${name}</strong><span>${meta}</span></span></button>`;
 app.innerHTML=`<section class="home-top"><div class="kicker">学びスプリント</div><div class="app-name">看護師国家試験</div><p class="lead">今日の12問を、合格の1歩に。</p></section>${resume}
 <div class="verified-note">MVP問題は独自作成です。厚生労働省の最新出題基準・公開問題利用条件の公式監査完了前のため、製品版データとしては未確定です。</div>
 <section class="section"><button class="full-btn" data-action="daily"><span class="icon">12</span><span><span class="name">今日の12問</span><span class="meta">必修・一般・状況設定を短く横断</span></span></button><button class="full-btn" data-action="required"><span class="icon">必</span><span><span class="name">必修12問</span><span class="meta">取りこぼしたくない基本を集中反復</span></span></button><button class="full-btn" data-action="weak" ${weakCount?'':'disabled'}><span class="icon">↺</span><span><span class="name">苦手復習</span><span class="meta">3連続正解で苦手から自動解除</span></span><span class="badge">${weakCount}問</span></button></section>
 <section class="section"><h2>出題区分から学ぶ</h2><div class="category-grid">${cat('必修','required',`24問・完答 ${state.completed['必修']||0}回`)}${cat('一般','general',`24問・完答 ${state.completed['一般']||0}回`)}${cat('状況設定','scenario',`12問・症例を連続で判断`)}</div></section>
 <section class="section"><button class="full-btn" data-action="subjects"><span class="icon">科</span><span><span class="name">科目・領域から学ぶ</span><span class="meta">領域ごとの解答数・苦手を確認</span></span></button><button class="full-btn" data-action="mock"><span class="icon">試</span><span><span class="name">本番形式</span><span class="meta">製品版で240問相当・即時採点OFF</span></span></button><p class="section-note">Safari MVP：${Q.length}問（必修24・一般24・状況設定12）。下部ナビはFP2級基準の3タブ固定。</p></section>${tabs('home')}`;
}
function start(pool,label,count=12,mode='study'){
 if(!pool.length)return;
 const selected=picks(pool,count);session={ids:selected.map(q=>q.id),index:0,correct:0,results:[],startedAt:Date.now(),label,mode,selected:[],answered:false,unknown:false};page='quiz';persistResume();render();scrollTo(0,0)
}
function startByIds(ids,label,mode='study',resumeIndex=0,resumeCorrect=0,results=[]){session={ids,index:resumeIndex,correct:resumeCorrect,results,startedAt:Date.now(),label,mode,selected:[],answered:false,unknown:false};page='quiz';persistResume();render();scrollTo(0,0)}
function current(){return Q.find(q=>q.id===session?.ids[session.index])}
function persistResume(){if(!session)return;state.resume={ids:session.ids,index:session.index,correct:session.correct,results:session.results,label:session.label,mode:session.mode};save()}
function renderScenario(q){if(!q.scenario)return'';const first=q.scenarioIndex===0;return `<div class="scenario-box"><div class="scenario-label">状況設定 ${q.scenarioIndex+1}/${q.scenarioTotal}</div>${first?`<div class="scenario-text">${esc(q.scenario)}</div>`:`<details><summary>状況をもう一度見る</summary><div class="scenario-text">${esc(q.scenario)}</div></details>`}</div>`}
function renderQuiz(){const q=current();if(!q){finish();return}const n=session.index+1,total=session.ids.length,pct=Math.round((session.index/total)*100);const multi=q.answerType==='multiChoice';const tags=`<div class="tags"><span class="tag">${esc(q.category)}</span><span class="tag nurse">${esc(q.subject)}</span>${multi?`<span class="tag multi">${q.selectCount}つ選択</span>`:''}</div>`;
 let choices=q.choices.map((c,i)=>{let cls='';if(session.selected.includes(i))cls='selected';if(session.answered){const ans=Array.isArray(q.answer)?q.answer:[q.answer];if(ans.includes(i))cls='correct';else if(session.selected.includes(i)||session.unknown)cls=session.selected.includes(i)?'wrong':''}return `<button class="choice ${cls}" data-choice="${i}" ${session.answered?'disabled':''}><span class="num">${i+1}</span><span>${esc(c)}</span></button>`}).join('');
 let action='';if(!session.answered){action=multi?`<div class="select-state">${session.selected.length} / ${q.selectCount} 選択中</div>${choices}<button class="grade" data-action="grade" ${session.selected.length===q.selectCount?'':'disabled'}>採点する</button><button class="dontknow" data-action="unknown">わからない</button>`:`${choices}<button class="dontknow" data-action="unknown">わからない</button>`}else{const last=session.results.at(-1);action=`${choices}<div class="feedback ${last.correct?'ok':'ng'}"><div class="feedback-title">${last.correct?'正解':'不正解'}</div><span class="learn-label">この問題で覚える一文</span><p class="feedback-point">${esc(q.point)}</p><details><summary>詳しい解説を見る</summary><p class="detail">${esc(q.detail)}</p></details></div><button class="next" data-action="next">${n===total?'結果を見る':'次の問題へ'}</button>`}
 app.innerHTML=`${header(session.label,`${n} / ${total}`)}<section class="quiz"><div class="progress"><div style="width:${pct}%"></div></div>${tags}${renderScenario(q)}<div class="qtext">${esc(q.question)}</div>${action}</section>`;
}
function sameAnswer(q,selected){const ans=Array.isArray(q.answer)?[...q.answer].sort():[q.answer];const got=[...selected].sort();return ans.length===got.length&&ans.every((v,i)=>v===got[i])}
function grade(selected,unknown=false){const q=current();if(!q||session.answered)return;const correct=!unknown&&sameAnswer(q,selected);session.selected=[...selected];session.answered=true;session.unknown=unknown;if(correct)session.correct++;
 const w=state.weak[q.id];if(correct&&w){w.streak=(w.streak||0)+1;if(w.streak>=3)delete state.weak[q.id]}else if(!correct){state.weak[q.id]={streak:0,misses:(w?.misses||0)+1,lastMiss:Date.now()}}
 if(!state.seen.includes(q.id))state.seen.push(q.id);session.results.push({id:q.id,correct,unknown,category:q.category,subject:q.subject});persistResume();render();
}
function next(){if(session.index>=session.ids.length-1)return finish();session.index++;session.selected=[];session.answered=false;session.unknown=false;persistResume();render();scrollTo(0,0)}
function finish(){if(!session)return;const elapsed=Math.max(1,Math.round((Date.now()-session.startedAt)/1000));const result={label:session.label,correct:session.correct,total:session.ids.length,elapsed,at:Date.now(),results:session.results};state.history.unshift(result);state.history=state.history.slice(0,30);const cats=[...new Set(session.results.map(r=>r.category))];if(cats.length===1&&session.results.length===session.ids.length)state.completed[cats[0]]=(state.completed[cats[0]]||0)+1;state.resume=null;save();session.final=result;page='result';render();scrollTo(0,0)}
function renderResult(){const r=session?.final||state.history[0];if(!r){page='home';return render()}const rate=Math.round((r.correct/r.total)*100);const requiredResults=r.results.filter(x=>x.category==='必修');const requiredRate=requiredResults.length?Math.round(requiredResults.filter(x=>x.correct).length/requiredResults.length*100):null;const weak=Object.keys(state.weak);app.innerHTML=`${header('結果')}<div class="result"><div class="result-big">${r.correct} / ${r.total}</div><div class="result-sub">${esc(r.label)}・正答率 ${rate}%</div><div class="result-grid"><div class="metric"><b>${rate}%</b><span>正答率</span></div><div class="metric"><b>${fmtSec(r.elapsed)}</b><span>所要時間</span></div><div class="metric"><b>${weak.length}</b><span>苦手</span></div></div>${requiredRate!==null?`<p class="section-note">このセットの必修正答率：${requiredRate}%</p>`:''}</div><div class="result-actions"><button class="next" data-action="again">もう12問</button><button class="secondary" data-action="weak" ${weak.length?'':'disabled'}>間違えた問題を復習</button><button class="secondary" data-action="home">ホームへ</button></div>`}
function renderHistory(){const h=state.history;const answered=h.reduce((a,x)=>a+x.total,0),correct=h.reduce((a,x)=>a+x.correct,0),rate=answered?Math.round(correct/answered*100):0;app.innerHTML=`${header('学習記録')}<section class="stats"><div class="stat-row"><div class="stat"><b>${answered}</b><span>累計解答</span></div><div class="stat"><b>${rate}%</b><span>正答率</span></div><div class="stat"><b>${Object.keys(state.weak).length}</b><span>苦手</span></div></div><div class="history">${h.length?h.map(x=>`<div class="history-item"><span>${esc(x.label)} ${x.correct}/${x.total}</span><span>${new Date(x.at).toLocaleDateString('ja-JP')}</span></div>`).join(''):`<div class="empty">まだ学習記録はありません。</div>`}</div></section>${tabs('history')}`}
function renderSettings(){app.innerHTML=`${header('設定')}<section class="settings"><div class="setting-card"><h3>文字サイズ</h3><div class="seg"><button data-font="normal" class="${state.font==='normal'?'active':''}">標準</button><button data-font="large" class="${state.font==='large'?'active':''}">大</button><button data-font="xlarge" class="${state.font==='xlarge'?'active':''}">特大</button></div></div><div class="setting-card"><h3>問題データ</h3><p>${esc(META.version||'MVP')}・${Q.length}問。公式出題基準／公開問題利用条件は監査待ち。監査完了前の問題を製品版へ自動昇格させない。</p></div><div class="setting-card"><h3>課金</h3><p>Safari版は課金UI確認のみ。iOS製品版ではStoreKit 2の正式価格を表示し、購入・復元・期限切れを実機確認する。</p><button class="secondary" data-action="paywall">課金画面を確認</button></div><div class="setting-card"><h3>学習データ</h3><button class="danger" data-action="reset">学習データをリセット</button></div></section>${tabs('settings')}`}
function renderSubjects(){const groups={};Q.forEach(q=>{groups[q.subject]??={count:0,seen:0,weak:0};groups[q.subject].count++;if(state.seen.includes(q.id))groups[q.subject].seen++;if(state.weak[q.id])groups[q.subject].weak++});app.innerHTML=`${header('科目・領域から学ぶ')}<section class="section"><div class="subject-list">${Object.entries(groups).sort((a,b)=>a[0].localeCompare(b[0],'ja')).map(([name,g])=>`<button class="subject" data-subject="${esc(name)}"><strong>${esc(name)}</strong><span>${g.seen}/${g.count}解答・苦手${g.weak}</span></button>`).join('')}</div></section>${tabs('home')}`}
function renderPaywall(){app.innerHTML=`${header('プレミアム')}<section class="paywall"><div class="paycard"><h2>看護師国試 プレミアム</h2><p>全問題、苦手復習、詳細履歴、本番形式、更新問題を解放する想定です。</p><div class="plans"><div class="plan"><b>月額</b><span>初回7日間無料。その後はStoreKit表示価格で自動更新</span></div><div class="plan"><b>買い切り</b><span>StoreKit表示価格で永久解放対象機能を利用</span></div></div><ul><li>学習中に課金画面を割り込ませない</li><li>購入を復元する導線を常設</li><li>価格は固定文字列ではなくdisplayPriceを使用</li></ul><button class="grade" disabled>Safari MVPでは購入しません</button><div class="disabled-note">iOS実装時にStoreKit 2へ接続。Safariでは誤購入防止のためダミー決済を実行しません。</div></div></section>`}
function weakPool(){return Object.keys(state.weak).map(id=>Q.find(q=>q.id===id)).filter(Boolean).sort((a,b)=>(state.weak[b.id].misses||0)-(state.weak[a.id].misses||0)||(state.weak[b.id].lastMiss||0)-(state.weak[a.id].lastMiss||0))}
app.addEventListener('click',e=>{
 const choice=e.target.closest('[data-choice]');if(choice&&page==='quiz'){const q=current(),i=Number(choice.dataset.choice);if(session.answered)return;if(q.answerType==='singleChoice')return grade([i]);const pos=session.selected.indexOf(i);if(pos>=0)session.selected.splice(pos,1);else if(session.selected.length<q.selectCount)session.selected.push(i);render();return}
 const a=e.target.closest('[data-action]')?.dataset.action;if(a==='daily')return start(Q,'今日の12問',12);if(a==='required')return start(Q.filter(q=>q.category==='必修'),'必修12問',12);if(a==='weak'){const p=weakPool();if(p.length)return start(p,'苦手復習',Math.min(12,p.length));return}if(a==='grade')return grade(session.selected);if(a==='unknown')return grade([],true);if(a==='next')return next();if(a==='home'){page='home';render();return}if(a==='again')return start(Q,'今日の12問',12);if(a==='subjects'){page='subjects';render();return}if(a==='mock'||a==='paywall'){page='paywall';render();return}if(a==='resume'&&state.resume){const r=state.resume;return startByIds(r.ids,r.label,r.mode,r.index,r.correct,r.results||[])}if(a==='reset'){if(confirm('学習履歴・苦手・途中データを削除しますか？')){state=defaults();save();page='home';render()}return}
 const tab=e.target.closest('[data-tab]')?.dataset.tab;if(tab){page=tab;render();scrollTo(0,0);return}
 const cat=e.target.closest('[data-category]')?.dataset.category;if(cat)return start(Q.filter(q=>q.category===cat),`${cat}12問`,12);
 const sub=e.target.closest('[data-subject]')?.dataset.subject;if(sub)return start(Q.filter(q=>q.subject===sub),`${sub}`,12);
 const f=e.target.closest('[data-font]')?.dataset.font;if(f){state.font=f;save();render();return}
});
applyFont();render();
})();
