'use strict';
(function(){
const KEY='manabiSprint.otsu4.v1';
const app=document.getElementById('app');
const byId=Object.fromEntries(QUESTIONS.map(q=>[q.id,q]));
let view='home',session=null,timerId=null,lastResult=null,paywallReturn='home';
const fresh=()=>({schemaVersion:1,contentVersion:CONTENT_VERSION,premiumPreview:false,weak:{},seenIds:{},completions:{},stats:{totalAnswered:0,totalCorrect:0,subjects:{'法令':{a:0,c:0},'物理・化学':{a:0,c:0},'性質・消火':{a:0,c:0}},history:[]},inProgress:null,settings:{fontSize:'normal'}});
function load(){try{const s=JSON.parse(localStorage.getItem(KEY)||'null');if(!s||typeof s!=='object')return fresh();const f=fresh();return{...f,...s,weak:s.weak||{},seenIds:s.seenIds||{},completions:s.completions||{},stats:{...f.stats,...(s.stats||{}),subjects:{...f.stats.subjects,...((s.stats||{}).subjects||{})},history:Array.isArray(s.stats?.history)?s.stats.history:[]},settings:{...f.settings,...(s.settings||{})}}}catch(e){return fresh()}}
let STATE=load();
function save(){try{localStorage.setItem(KEY,JSON.stringify(STATE))}catch(e){}}
function esc(v){return String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function shuffle(a){a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function applyFont(){document.documentElement.classList.toggle('fs-large',STATE.settings.fontSize==='large');document.documentElement.classList.toggle('fs-xlarge',STATE.settings.fontSize==='xlarge')}
function fmt(sec){sec=Math.max(0,Math.floor(sec));const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=sec%60;return h?`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function weakList(){return QUESTIONS.filter(q=>STATE.weak[q.id]&&STATE.weak[q.id].streak<3)}
function comp(k){return STATE.completions[k]||0}
function subjectRate(name){const s=STATE.stats.subjects[name];return s&&s.a?Math.round(s.c/s.a*100):null}
function tabbar(active){return `<nav class="tabbar" aria-label="メインナビゲーション"><button data-tab="home" class="${active==='home'?'active':''}"><span class="ic">⌂</span>ホーム</button><button data-tab="record" class="${active==='record'?'active':''}"><span class="ic">▥</span>学習記録</button><button data-tab="settings" class="${active==='settings'?'active':''}"><span class="ic">⚙</span>設定</button></nav>`}
function bindTabs(){app.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>go(b.dataset.tab))}
function go(v){clearInterval(timerId);view=v;render();window.scrollTo(0,0)}
function render(){applyFont();if(view==='home')renderHome();else if(view==='quiz')renderQuiz();else if(view==='result')renderResult();else if(view==='record')renderRecord();else if(view==='settings')renderSettings();else if(view==='paywall')renderPaywall()}
function activeValid(){const p=STATE.inProgress;if(!p||p.contentVersion!==CONTENT_VERSION||!Array.isArray(p.ids)||!p.ids.length)return false;return p.ids.every(id=>byId[id])&&Number.isInteger(p.index)&&p.index>=0&&p.index<p.ids.length}
function renderHome(){const hasActive=activeValid(),weak=weakList().length;const premium=STATE.premiumPreview;app.innerHTML=`<div class="home-top"><div class="brand-tag">学びスプリント</div><div class="brand-title">危険物 乙4</div><p class="brand-sub">今日も12問、合格に近づく。</p></div>
${hasActive?`<section><button id="resume" class="full-btn resume"><span class="icon">↻</span><span><span class="name">続きから</span><span class="meta">${STATE.inProgress.index+1} / ${STATE.inProgress.ids.length}問目から再開</span></span></button></section>`:''}
<section class="section"><button id="today" class="full-btn primary-card"><span class="icon">12</span><span><span class="name">今日の12問</span><span class="meta">法令・物化・性消を短く一周</span></span><span class="badge">${comp('today12')}回</span></button></section>
<section class="section"><h2>すぐ復習</h2><button id="weak" class="full-btn"><span class="icon">↺</span><span><span class="name">苦手復習</span><span class="meta">3連続正解で苦手から自動解除</span></span><span class="badge">${weak}問${premium?'':'・PREMIUM'}</span></button></section>
<section class="section"><h2>科目別</h2><div class="subject-grid">${['法令','物理・化学','性質・消火'].map((s,i)=>{const n=QUESTIONS.filter(q=>q.subject===s).length,r=subjectRate(s);return`<button class="subject-card" data-subject="${esc(s)}"><span><strong>${esc(s)}</strong><small>${n}問・完答 ${comp('subject:'+s)}回${r===null?'':`・直近累計 ${r}%`}</small></span><span class="metric">›</span></button>`}).join('')}</div></section>
<section class="section"><h2>集中・本番</h2><div class="two-grid"><button id="numbers" class="compact-btn locked"><strong>数字・指定数量</strong><small>倍数・指定数量を集中反復</small><span class="lock-pill">${premium?'試用中':'PREMIUM'}</span></button><button id="exam" class="compact-btn exam-card locked"><strong>本番35問</strong><small>120分・法令15／物化10／性消10</small><span class="lock-pill">${premium?'試用中':'PREMIUM'}</span></button></div></section>
<section class="section"><div class="notice">Safari価値検証版：独自36問を収録。製品版は360問を目標とし、法令改定時に問題データを更新できる構造で実装します。</div></section>${tabbar('home')}`;
if(hasActive)document.getElementById('resume').onclick=resume;document.getElementById('today').onclick=()=>start('today12');document.getElementById('weak').onclick=()=>premiumGate('weak');document.querySelectorAll('[data-subject]').forEach(b=>b.onclick=()=>start('subject',b.dataset.subject));document.getElementById('numbers').onclick=()=>premiumGate('numbers');document.getElementById('exam').onclick=()=>premiumGate('exam');bindTabs()}
function premiumGate(mode){if(STATE.premiumPreview)return start(mode);paywallReturn='home';STATE.pendingMode=mode;save();go('paywall')}
function selectFor(mode,arg){if(mode==='today12'){return[...shuffle(QUESTIONS.filter(q=>q.subject==='法令')).slice(0,5),...shuffle(QUESTIONS.filter(q=>q.subject==='物理・化学')).slice(0,3),...shuffle(QUESTIONS.filter(q=>q.subject==='性質・消火')).slice(0,4)]}if(mode==='subject')return QUESTIONS.filter(q=>q.subject===arg);if(mode==='numbers')return QUESTIONS.filter(q=>q.tags.includes('数字')||q.tags.includes('指定数量'));if(mode==='weak')return weakList();if(mode==='exam')return[...QUESTIONS.filter(q=>q.subject==='法令').slice(0,15),...QUESTIONS.filter(q=>q.subject==='物理・化学').slice(0,10),...shuffle(QUESTIONS.filter(q=>q.subject==='性質・消火')).slice(0,10)];return[]}
function start(mode,arg){const qs=selectFor(mode,arg);if(!qs.length){alert(mode==='weak'?'現在の苦手問題はありません。':'問題がありません。');return}const key=mode==='subject'?'subject:'+arg:mode;session={mode,key,ids:qs.map(q=>q.id),index:0,answers:{},startedAt:Date.now(),exam:mode==='exam'};persistSession();view='quiz';render()}
function persistSession(){if(!session)return;STATE.inProgress={...session,contentVersion:CONTENT_VERSION};save()}
function resume(){const p=STATE.inProgress;if(!activeValid()){STATE.inProgress=null;save();return go('home')}session={mode:p.mode,key:p.key,ids:p.ids,index:p.index,answers:p.answers||{},startedAt:p.startedAt||Date.now(),exam:!!p.exam};view='quiz';render()}
function current(){return byId[session.ids[session.index]]}
function elapsed(){return Math.floor((Date.now()-session.startedAt)/1000)}
function examRemain(){return 120*60-elapsed()}
function renderQuiz(){if(!session)return go('home');const q=current(),ans=session.answers[q.id],graded=!session.exam&&ans&&ans.graded;const rem=session.exam?examRemain():elapsed();if(session.exam&&rem<=0)return finish();app.innerHTML=`<header class="header"><button id="quit" class="quit">ホーム</button><h1>${session.exam?'本番35問':esc(session.key==='today12'?'今日の12問':session.key.replace('subject:',''))}</h1><span class="counter">${session.index+1} / ${session.ids.length}</span><span id="timer" class="timer">${fmt(rem)}</span></header><div class="progress-track"><div class="progress-bar" style="width:${(session.index+1)/session.ids.length*100}%"></div></div><div class="quiz-wrap"><div class="card quiz-card"><span class="tag">${esc(q.subject)} ・ ${esc(q.topic)}</span><h2 class="question">${esc(q.question)}</h2><div class="choices">${q.choices.map((c,i)=>{let cls='choice';if(session.exam&&ans?.selected===i)cls+=' selected';if(graded){if(i===q.answer)cls+=' correct';else if(i===ans.selected)cls+=' incorrect';else cls+=' dim'}return`<button class="${cls}" data-choice="${i}" ${graded?'disabled':''}><span class="choice-letter">${i+1}</span><span>${esc(c)}</span></button>`}).join('')}</div>${!session.exam&&!graded?`<button id="unknown" class="unknown">わからない</button>`:''}${graded?feedback(q,ans):''}${session.exam?examNav():''}</div></div>`;
document.getElementById('quit').onclick=leaveQuiz;document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>choose(Number(b.dataset.choice)));if(!session.exam&&!graded)document.getElementById('unknown').onclick=()=>grade(null,true);if(graded)document.getElementById('next').onclick=next;if(session.exam){document.getElementById('prev').onclick=prevExam;document.getElementById('nextExam').onclick=nextExam}timerId=setInterval(()=>{const el=document.getElementById('timer');if(!el)return;const t=session.exam?examRemain():elapsed();el.textContent=fmt(t);if(session.exam&&t<=0)finish()},500)}
function feedback(q,a){const ok=a.correct;return`<div class="feedback ${ok?'ok':'ng'}"><div class="feedback-title">${ok?'正解です':'不正解です'}</div><span class="learn-label">この問題で覚える一文</span><p class="feedback-point">${esc(q.point)}</p><details><summary>詳しい解説を見る</summary><p class="detail">${esc(q.detail)}</p></details></div><button id="next" class="next-btn">${session.index===session.ids.length-1?'結果を見る':'次の問題へ'}</button>`}
function examNav(){const last=session.index===session.ids.length-1;return`<div class="exam-nav"><button id="prev" class="outline-btn" ${session.index===0?'disabled':''}>前の問題</button><button id="nextExam" class="next-btn" style="margin:0">${last?'採点する':'次の問題'}</button></div><p class="section-note">本番モードでは回答中に正誤を表示しません。選び直しもできます。</p>`}
function choose(i){if(session.exam){session.answers[current().id]={selected:i};persistSession();return render()}grade(i,false)}
function grade(i,unknown){const q=current();if(session.answers[q.id]?.graded)return;const correct=!unknown&&i===q.answer;session.answers[q.id]={selected:i,unknown:!!unknown,correct,graded:true};persistSession();render()}
function next(){if(session.index<session.ids.length-1){session.index++;persistSession();render()}else finish()}
function prevExam(){if(session.index>0){session.index--;persistSession();render()}}
function nextExam(){if(session.index<session.ids.length-1){session.index++;persistSession();render()}else finish()}
function leaveQuiz(){persistSession();clearInterval(timerId);go('home')}
function applyWeak(q,a){STATE.seenIds[q.id]=true;const w=STATE.weak[q.id];if(a.correct){if(w){w.streak=(w.streak||0)+1;if(w.streak>=3)delete STATE.weak[q.id]}}else STATE.weak[q.id]={streak:0,wrongCount:(w?.wrongCount||0)+1,lastAnsweredAt:new Date().toISOString()}}
function finish(){clearInterval(timerId);const answers=session.answers;const rows=session.ids.map(id=>{const q=byId[id];let a=answers[id];if(session.exam){a={selected:a?.selected??null,unknown:a?.selected==null,correct:a?.selected===q.answer,graded:true};answers[id]=a}return{q,a:a||{selected:null,unknown:true,correct:false,graded:true}}});rows.forEach(({q,a})=>{applyWeak(q,a);STATE.stats.totalAnswered++;if(a.correct)STATE.stats.totalCorrect++;const ss=STATE.stats.subjects[q.subject]||(STATE.stats.subjects[q.subject]={a:0,c:0});ss.a++;if(a.correct)ss.c++});const correct=rows.filter(x=>x.a.correct).length,total=rows.length,duration=elapsed(),wrong=rows.filter(x=>!x.a.correct).map(x=>x.q.id);STATE.completions[session.key]=(STATE.completions[session.key]||0)+1;const subjectResults={};['法令','物理・化学','性質・消火'].forEach(s=>{const sr=rows.filter(x=>x.q.subject===s);if(sr.length)subjectResults[s]={correct:sr.filter(x=>x.a.correct).length,total:sr.length}});lastResult={mode:session.mode,key:session.key,correct,total,score:Math.round(correct/total*100),duration,wrong,subjectResults,exam:session.exam};STATE.stats.history.unshift({at:new Date().toISOString(),mode:session.mode,key:session.key,score:lastResult.score,correct,total,duration,subjectResults});STATE.stats.history=STATE.stats.history.slice(0,20);STATE.inProgress=null;save();view='result';render()}
function renderResult(){const r=lastResult;if(!r)return go('home');const examLines=r.exam?Object.entries(r.subjectResults).map(([s,v])=>{const rate=Math.round(v.correct/v.total*100),pass=rate>=60;return`<div class="subject-line ${pass?'pass':'fail'}"><span><b>${esc(s)}</b><br><small>${v.correct} / ${v.total}・${rate}%</small></span><b>${pass?'基準到達':'60%未満'}</b></div>`}).join(''):'';const examPass=r.exam&&Object.values(r.subjectResults).every(v=>v.correct/v.total>=.6);app.innerHTML=`<div class="result"><div class="card result-card"><div class="result-kicker">${r.exam?'MOCK EXAM':'SPRINT COMPLETE'}</div><div class="result-score">${r.correct} / ${r.total}</div><div class="result-sub">正答率 ${r.score}% ・ ${fmt(r.duration)}</div>${r.exam?`<h2>${examPass?'3科目すべて60%以上':'科目別に復習しましょう'}</h2><div class="subject-result">${examLines}</div>`:`<h2>${r.wrong.length?'今回の誤答を次の復習へ':'全問正解です'}</h2>`}<div class="stats"><div class="stat"><b>${r.correct}</b><span>正解</span></div><div class="stat"><b>${r.wrong.length}</b><span>復習対象</span></div><div class="stat"><b>${weakList().length}</b><span>苦手</span></div></div></div><div class="action-stack"><button id="again" class="btn-primary">${r.exam?'本番35問をもう一度':'もう12問'}</button>${r.wrong.length?`<button id="review" class="btn-secondary">間違えた問題を復習</button>`:''}<button id="home" class="btn-outline">ホームへ</button></div></div>`;document.getElementById('again').onclick=()=>start(r.exam?'exam':'today12');const rev=document.getElementById('review');if(rev)rev.onclick=()=>premiumGate('weak');document.getElementById('home').onclick=()=>go('home')}
function renderRecord(){const acc=STATE.stats.totalAnswered?Math.round(STATE.stats.totalCorrect/STATE.stats.totalAnswered*100):0;app.innerHTML=`<div class="home-top"><div class="brand-tag">学びスプリント</div><div class="brand-title">学習記録</div><p class="brand-sub">周回と苦手だけを、必要な分だけ。</p></div><section class="section"><div class="card record-card"><div class="row"><span>累計解答</span><b>${STATE.stats.totalAnswered}問</b></div><div class="row"><span>累計正答率</span><b>${STATE.stats.totalAnswered?acc+'%':'—'}</b></div><div class="row"><span>今日の12問 完答</span><b>${comp('today12')}回</b></div><div class="row"><span>現在の苦手</span><b>${weakList().length}問</b></div></div></section><section class="section"><h2>科目別</h2><div class="card record-card">${['法令','物理・化学','性質・消火'].map(s=>`<div class="row"><span>${s}</span><b>${subjectRate(s)===null?'—':subjectRate(s)+'%'}</b></div>`).join('')}</div></section><section class="section"><h2>直近履歴</h2><div class="history">${STATE.stats.history.length?STATE.stats.history.slice(0,5).map(h=>`<div class="history-item"><b>${h.mode==='exam'?'本番35問':h.key.replace('subject:','')}</b><small>${new Date(h.at).toLocaleString('ja-JP')}・${h.correct}/${h.total}・${fmt(h.duration)}</small></div>`).join(''):`<div class="notice">まだ学習記録はありません。</div>`}</div></section>${tabbar('record')}`;bindTabs()}
function renderSettings(){app.innerHTML=`<div class="home-top"><div class="brand-tag">学びスプリント</div><div class="brand-title">設定</div></div><section class="section"><h2>文字サイズ</h2><div class="font-buttons">${[['normal','標準'],['large','大'],['xlarge','特大']].map(([v,l])=>`<button data-font="${v}" class="${STATE.settings.fontSize===v?'active':''}">${l}</button>`).join('')}</div></section><section class="section"><div class="card settings-card"><div class="row"><span>問題データ</span><b>${CONTENT_VERSION}</b></div><div class="row"><span>法令確認基準日</span><b>${LAW_BASELINE}</b></div><div class="row"><span>課金状態</span><b>${STATE.premiumPreview?'Safari検証用に解放':'無料状態'}</b></div></div></section><section class="section"><button id="reset" class="full-btn"><span class="icon">↺</span><span><span class="name">学習データをリセット</span><span class="meta">端末内の履歴・苦手・途中状態を削除</span></span></button></section><section class="section"><div class="notice">製品版では、ここにプライバシーポリシー、利用規約、サポート、StoreKit 2の「購入を復元」を配置します。検証版には反応しないダミーボタンを置いていません。</div></section>${tabbar('settings')}`;document.querySelectorAll('[data-font]').forEach(b=>b.onclick=()=>{STATE.settings.fontSize=b.dataset.font;save();render()});document.getElementById('reset').onclick=()=>{if(confirm('学習データをすべて削除しますか？')){const font=STATE.settings.fontSize;STATE=fresh();STATE.settings.fontSize=font;save();go('home')}};bindTabs()}
function renderPaywall(){app.innerHTML=`<div class="header"><button id="back" class="quit">戻る</button><h1>乙4 プレミアム</h1></div><div class="section"><div class="card paywall"><span class="tag">買い切り予定</span><h2>苦手・数字・本番演習を解放</h2><p>製品版では全360問、苦手復習、数字・指定数量、本番35問を非消耗型の買い切りで解放します。初期価格候補は680円相当です。</p><ul class="pay-list"><li>全360問</li><li>3連続正解で解除する苦手復習</li><li>数字・指定数量の集中演習</li><li>120分・35問の本番再現</li></ul><button id="preview" class="next-btn">Safari検証用にプレミアム機能を試す</button><p class="section-note">このボタンは価値検証専用で、購入処理や課金は発生しません。製品版ではStoreKit 2へ置換します。</p></div></div>`;document.getElementById('back').onclick=()=>go(paywallReturn);document.getElementById('preview').onclick=()=>{STATE.premiumPreview=true;const mode=STATE.pendingMode;delete STATE.pendingMode;save();mode?start(mode):go('home')}}
window.addEventListener('error',()=>{clearInterval(timerId)});render();
})();
