
(()=>{
const $=id=>document.getElementById(id),KEY='sprintStudyV061History',SET='sprintStudyV063Setting';
let st={status:'idle',index:1,left:45,total:45,end:0,under:0,review:0,extend:0,results:[],started:0,timer:null,beeped:new Set()},audio={ctx:null,element:null,mode:'none',preview:false,previewTimer:null,unlocked:false,lastEnsure:0};
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const val=()=>({subject:$('subject').value.trim()||'今日の学習',unit:$('unit').value,seconds:Math.max(5,Math.min(600,+$('seconds').value||45)),count:Math.max(1,Math.min(999,+$('count').value||10)),countdown:+$('countdown').value,soundStyle:$('soundStyle').value,volume:+$('volume').value,bgm:$('bgm').value,bgmVolume:+$('bgmVolume').value,switchSound:$('switchSound').checked,timerBgm:$('timerBgm').checked});
const fmt=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(Math.ceil(s%60)).padStart(2,'0')}`;
const hist=()=>{try{const x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x:[]}catch{return[]}};const saveHist=a=>localStorage.setItem(KEY,JSON.stringify(a));
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)}
async function unlock(){try{if(!audio.ctx){audio.ctx=new (window.AudioContext||window.webkitAudioContext)();audio.ctx.onstatechange=()=>{if(audio.ctx.state==='running'){audio.unlocked=true;if(st.status==='running')ensureTimerBgm()}else if(st.status==='running'){$('audioState').textContent='音声停止中'}}}if(audio.ctx.state!=='running')await audio.ctx.resume();audio.unlocked=audio.ctx.state==='running';$('audioState').textContent=audio.unlocked?'音声準備済み':'音声停止中';$('audioState').classList.toggle('on',audio.unlocked);return audio.unlocked}catch{$('audioState').textContent='音声エラー';return false}}
function tone(freq,d=.08,scale=.16,type='sine',delay=0){const c=audio.ctx;if(!c||c.state!=='running')return;const t=c.currentTime+delay,o=c.createOscillator(),g=c.createGain(),v=Math.max(.0001,val().volume*scale);o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(v,t+.01);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g).connect(c.destination);o.start(t);o.stop(t+d+.03)}
function clickSound(){const c=audio.ctx;if(!c||c.state!=='running')return;const n=Math.max(1,Math.floor(c.sampleRate*.045)),b=c.createBuffer(1,n,c.sampleRate),d=b.getChannelData(0);for(let i=0;i<n;i++)d[i]=(Math.random()*2-1)*(1-i/n);const s=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();s.buffer=b;f.type='bandpass';f.frequency.value=950;g.gain.value=val().volume*.13;s.connect(f).connect(g).connect(c.destination);s.start()}
function countSound(){const x=val().soundStyle;if(x==='wood')clickSound();else if(x==='clear')tone(1100,.07,.14,'square');else tone(760,.08,.13)}
function switchBeep(kind='next'){if(!val().switchSound)return;const x=val().soundStyle;if(x==='wood'){clickSound();setTimeout(clickSound,90)}else if(x==='clear'){tone(kind==='finish'?980:880,.09,.17,'triangle');tone(kind==='finish'?1320:1120,.11,.14,'triangle',.1)}else{tone(kind==='finish'?880:660,.1,.16);tone(kind==='finish'?1100:880,.12,.13,'sine',.11)}}
const BGM_URL='https://drive.google.com/uc?export=download&id=1-91D-kuUxyz9TFXabcbvxWIqgtJEpPn1&confirm=t';
function getBgm(){if(audio.element)return audio.element;const a=new Audio();a.src=BGM_URL;a.preload='auto';a.loop=true;a.playsInline=true;a.volume=Math.max(0,Math.min(1,val().bgmVolume));a.addEventListener('canplay',()=>{if(audio.mode==='loading')$('audioState').textContent='BGM準備済み'});a.addEventListener('playing',()=>{$('audioState').textContent=audio.mode==='preview'?'BGM試聴中':'BGM再生中';$('audioState').classList.add('on')});a.addEventListener('waiting',()=>{$('audioState').textContent='BGM読込中'});a.addEventListener('error',()=>{$('audioState').textContent='音源を読み込めません';$('audioState').classList.remove('on');toast('音源の共有設定または通信状態を確認してください')});audio.element=a;return a}
function bgmLevel(){return Math.max(0,Math.min(1,val().bgmVolume))}
function stopBgm(reset=false){clearTimeout(audio.previewTimer);audio.previewTimer=null;audio.preview=false;audio.mode='none';$('previewBgm').textContent='BGMを12秒試聴';const a=audio.element;if(!a)return;a.pause();if(reset){try{a.currentTime=0}catch{}}$('audioState').textContent='BGM停止';$('audioState').classList.remove('on')}
async function startBgm(kind=val().bgm,mode='timer'){if(kind==='none'){stopBgm();return false}const a=getBgm();clearTimeout(audio.previewTimer);audio.mode=mode;audio.preview=mode==='preview';a.loop=true;a.volume=bgmLevel();if(mode==='preview'){try{a.currentTime=0}catch{};$('previewBgm').textContent='試聴を停止'}try{await a.play();if(mode==='preview')audio.previewTimer=setTimeout(()=>{if(audio.mode==='preview'){stopBgm(true);toast('BGM試聴を終了しました')}},12000);return true}catch(e){audio.mode='none';$('audioState').textContent='再生できません';$('audioState').classList.remove('on');toast('音源を再生できません。Driveの共有設定を確認してください');return false}}
async function ensureTimerBgm(force=false){const s=val();if(st.status!=='running'||!s.timerBgm||s.bgm==='none'){if(audio.mode==='timer')stopBgm();return false}const a=getBgm();a.volume=bgmLevel();if(force||a.paused||audio.mode!=='timer')return startBgm(s.bgm,'timer');$('audioState').textContent='BGM再生中';$('audioState').classList.add('on');return true}
function apply(x){$('seconds').value=x.seconds;$('count').value=x.count;$('unit').value=x.unit||'ページ';idle()}
function idle(){if(st.status!=='idle')return;const s=val();st.left=st.total=s.seconds;st.index=1;st.beeped.clear();$('timer').textContent=fmt(st.left);$('counter').textContent=`1 / ${s.count} ${s.unit}`;$('bar').style.width='100%'}
function controls(run){$('skipBtn').disabled=!run;$('goodBtn').disabled=!run;$('reviewBtn').disabled=!run;$('moreBtn').disabled=!run}
async function start(){const s=val();await unlock();if(s.timerBgm&&s.bgm!=='none')await startBgm(s.bgm,'timer');st={...st,status:'running',index:1,left:s.seconds,total:s.seconds,end:Date.now()+s.seconds*1000,under:0,review:0,extend:0,results:[],started:Date.now(),beeped:new Set()};$('phase').textContent='学習中';$('mainBtn').textContent='一時停止';controls(true);switchBeep('next');tick();clearInterval(st.timer);st.timer=setInterval(tick,100);setTimeout(()=>ensureTimerBgm(true),350)}
function tick(){if(st.status!=='running')return;st.left=Math.max(0,(st.end-Date.now())/1000);$('timer').textContent=fmt(st.left);$('bar').style.width=`${Math.max(0,st.left/st.total*100)}%`;const s=val();$('counter').textContent=`${st.index} / ${s.count} ${s.unit}`;const now=Date.now();if(now-audio.lastEnsure>2000){audio.lastEnsure=now;ensureTimerBgm()}const sec=Math.ceil(st.left),cd=s.countdown;if(cd>0&&sec>0&&sec<=cd&&!st.beeped.has(sec)){st.beeped.add(sec);countSound()}if(st.left<=0)next('unjudged')}
function next(outcome){const s=val();if(outcome==='understood')st.under++;if(outcome==='review')st.review++;st.results.push({index:st.index,outcome});switchBeep('next');if(st.index>=s.count){finish();return}st.index++;st.left=st.total=s.seconds;st.end=Date.now()+s.seconds*1000;st.beeped.clear();tick()}
function finish(){clearInterval(st.timer);stopBgm(true);st.status='idle';controls(false);$('mainBtn').textContent='開始';$('phase').textContent='完了';const s=val(),elapsed=Math.max(1,Math.round((Date.now()-st.started)/1000)),judged=st.under+st.review,rate=judged?Math.round(st.under/judged*100):null,item={id:Date.now(),date:new Date().toISOString(),subject:s.subject,unit:s.unit,count:s.count,seconds:elapsed,avg:Math.round(elapsed/s.count),under:st.under,review:st.review,rate,extend:st.extend,results:st.results};saveHist([item,...hist()].slice(0,200));switchBeep('finish');toast(`完了：理解率 ${rate??'-'}% ／ 要復習 ${st.review}${s.unit}`);render();setTimeout(idle,300)}
function pause(){clearInterval(st.timer);st.status='paused';st.left=Math.max(0,(st.end-Date.now())/1000);$('mainBtn').textContent='再開';$('phase').textContent='一時停止';stopBgm()}
async function resume(){await unlock();st.status='running';st.end=Date.now()+st.left*1000;$('mainBtn').textContent='一時停止';$('phase').textContent='学習中';await ensureTimerBgm(true);clearInterval(st.timer);st.timer=setInterval(tick,100)}
function reset(){clearInterval(st.timer);stopBgm(true);st.status='idle';controls(false);$('mainBtn').textContent='開始';$('phase').textContent='準備完了';idle()}
function render(){const a=hist(),units=a.reduce((n,x)=>n+x.count,0),secs=a.reduce((n,x)=>n+x.seconds,0),judged=a.reduce((n,x)=>n+x.under+x.review,0),under=a.reduce((n,x)=>n+x.under,0);$('sumSessions').textContent=a.length;$('sumUnits').textContent=units;$('sumTime').textContent=Math.round(secs/60)+'分';$('sumRate').textContent=judged?Math.round(under/judged*100)+'%':'-';if(!a.length){$('history').innerHTML='<div class="meta">まだ履歴はありません。</div>';return}$('history').innerHTML=a.map(x=>{const review=(x.results||[]).filter(r=>r.outcome==='review').map(r=>r.index).join('、');return `<div class="item"><strong>${esc(x.subject)}</strong><div class="meta">${new Date(x.date).toLocaleString('ja-JP')}<br>${x.count}${esc(x.unit)} ／ ${Math.round(x.seconds/60)}分 ／ 平均${x.avg}秒<br>理解率 ${x.rate??'-'}% ／ 要復習 ${x.review}${esc(x.unit)}${review?'<br>復習箇所：'+review:''}</div></div>`}).join('')}
function saveSettings(){localStorage.setItem(SET,JSON.stringify(val()));toast('設定を保存しました')}
function loadSettings(){try{const s=JSON.parse(localStorage.getItem(SET)||'null');if(!s)return;$('subject').value=s.subject||'今日の学習';$('unit').value=s.unit||'ページ';$('seconds').value=s.seconds||45;$('count').value=s.count||10;$('countdown').value=String(s.countdown??3);$('soundStyle').value=s.soundStyle||'soft';$('volume').value=s.volume??.55;$('bgm').value=s.bgm==='none'?'none':'deep-focus';$('bgmVolume').value=s.bgmVolume??.12;$('switchSound').checked=s.switchSound!==false;$('timerBgm').checked=s.timerBgm!==false}catch{}}
$('mainBtn').onclick=()=>st.status==='idle'?start():st.status==='running'?pause():resume();$('quickStart').onclick=()=>st.status==='idle'&&start();$('skipBtn').onclick=()=>next('unjudged');$('goodBtn').onclick=()=>next('understood');$('reviewBtn').onclick=()=>next('review');$('moreBtn').onclick=()=>{if(st.status==='running'||st.status==='paused'){st.left+=30;st.total+=30;if(st.status==='running')st.end+=30000;st.extend++;st.beeped.clear();toast('30秒延長しました')}};$('resetBtn').onclick=reset;$('saveSetting').onclick=saveSettings;
document.querySelectorAll('.q').forEach(b=>b.onclick=()=>{if(st.status!=='idle')reset();apply({seconds:+b.dataset.sec,count:+b.dataset.count,unit:b.dataset.unit});start();setTimeout(()=>$('timerCard').scrollIntoView({behavior:'smooth',block:'start'}),60)});
['seconds','count','unit'].forEach(id=>$(id).addEventListener('input',idle));$('volume').oninput=()=>{$('volumeValue').textContent=Math.round(+$('volume').value*100)+'%'};$('bgmVolume').oninput=()=>{$('bgmVolumeValue').textContent=Math.round(+$('bgmVolume').value*100)+'%';if(audio.element)audio.element.volume=bgmLevel()};
$('testSound').onclick=async()=>{if(await unlock()){switchBeep('next');setTimeout(countSound,450);toast('切替音とカウント音を再生しました')}else toast('音声を開始できませんでした')};$('previewBgm').onclick=async()=>{if(audio.preview){stopBgm(true);toast('BGM試聴を停止しました');return}if(val().bgm==='none'){toast('BGMを選択してください');return}await unlock();if(await startBgm(val().bgm,'preview'))toast('BGMを12秒間試聴します')};$('bgm').onchange=async()=>{if(val().bgm==='none'){stopBgm();return}if(audio.mode==='preview'){await unlock();startBgm(val().bgm,'preview')}else if(st.status==='running'){await unlock();ensureTimerBgm(true)}};$('timerBgm').onchange=async()=>{if(st.status!=='running')return;if($('timerBgm').checked){await unlock();ensureTimerBgm(true)}else if(audio.mode==='timer')stopBgm()};$('stopAudio').onclick=()=>{stopBgm(false);try{audio.ctx?.suspend()}catch{}$('audioState').textContent='停止中';$('audioState').classList.remove('on');toast('すべての音を停止しました')};$('resetAudio').onclick=()=>{$('countdown').value='3';$('soundStyle').value='soft';$('volume').value=.55;$('bgm').value='deep-focus';$('bgmVolume').value=.12;$('switchSound').checked=true;$('timerBgm').checked=true;$('volume').dispatchEvent(new Event('input'));$('bgmVolume').dispatchEvent(new Event('input'));toast('音設定を初期化しました')};
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===t));$('timerView').classList.toggle('hidden',t.dataset.view!=='timer');$('historyView').classList.toggle('hidden',t.dataset.view!=='history');if(t.dataset.view==='history')render()});$('clearHistory').onclick=()=>{if(confirm('履歴をすべて削除しますか？')){localStorage.removeItem(KEY);render()}};
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&st.status==='running'){tick();if(audio.ctx)audio.ctx.resume().catch(()=>{});ensureTimerBgm(true)}});loadSettings();$('volume').dispatchEvent(new Event('input'));$('bgmVolume').dispatchEvent(new Event('input'));getBgm();idle();render();
})();
