import copy, hashlib, json, tempfile, unittest
from pathlib import Path
import generic_route_decision as g
H=lambda s:hashlib.sha256(s.encode()).hexdigest()
C=lambda v:hashlib.sha256(json.dumps(v,sort_keys=True,separators=(',',':')).encode()).hexdigest()

def plan(**kw):
 p={'schema_version':1,'evidence_state':g.EVIDENCE_STATE,'parity_claim':'NONE','decision_id':'d1','policy':{'required_mode_classes':['FREE_CORE','MAJOR'],'allowed_service_regions':['JP','LOCAL_DEVICE'],'allowed_data_regions':['JP','LOCAL_DEVICE'],'maximum_mean_execution_total_ms':120000,'maximum_final_failure_fraction':.1,'maximum_retry_fraction':.25,'cost_currency':'USD','maximum_mean_cost_per_successful_run':2.0,'maximum_non_cancel_degraded_fraction':.2,'maximum_uploaded_asset_retention_seconds':86400,'require_deletion_control':True,'require_capacity_attestation':True,'minimum_overall_usability_delta':-.25,'minimum_primary_score_margin':.02,'ranking_weights':{'quality':.4,'latency':.25,'reliability':.2,'cost':.15},'engineering_policy_not_reference_fact':True}};p['policy'].update(kw);return p

def e07(kind='LICENSED_LOCAL_INFERENCE_SDK'):
 a=g.ROUTE_AUTHORITY[kind];d={'schema_version':1,'tool_version':'L1-E07-v1','evidence_kind':'PROVIDER_FALLBACK_SUBSTITUTION_CONFORMANCE','evidence_state':g.EVIDENCE_STATE,'conformance_state':'READY_FOR_HQ_E07_SUBSTITUTION_REVIEW' if a=='HOSTED_PROVIDER_ACCOUNT' else 'CONFORMANT_REQUIRES_GENERIC_LIVE_AUTHORITY_GATE','parity_claim':'NONE','substitution_id':'s','route_id':'r','route_kind':kind,'replaced_route_id':'old','fallback_order':g.FALLBACK_ORDER,'prior_fallback_dispositions':[],'adapter':{},'runtime':{'runtime_id':'rt','model_name':'m','model_version':'1','quality_profile':'q','artifact_sha256':H('artifact')},'capacity_authority':{'kind':a,'provenance_sha256':H('authority')},'commercial_basis_sha256':H('commercial'),'training_rights_evidence_sha256':H('training') if kind.startswith('PROJECT_') else None,'invariants':[],'compatibility':{'legacy_e05_e06_hosted_account_schema_compatible':a=='HOSTED_PROVIDER_ACCOUNT','generic_capacity_authority_live_gate_required':a!='HOSTED_PROVIDER_ACCOUNT','shared_app_contract_changed':False,'provider_neutral_publication_contract_preserved':True},'substitution_identity_sha256':H('identity'),'privacy':{},'parity_reason':'none'};d['e07_substitution_lock_sha256']=C({'identity':d['substitution_identity_sha256'],'report':d});return d

def e08(e7,s7,cap=('ADEQUATE','ADEQUATE','ADEQUATE'),cancel=True,state=None):
 kinds=['INPUT_INTERRUPTION','CANCEL_PRE_START','CANCEL_EXECUTING','CANCEL_FINALIZING','AMBIGUOUS_START_RETRY','RELAUNCH','OUTPUT_AVAILABILITY_LOSS','CAPACITY_LIMIT','LONG_TRACK','STORAGE_PRESSURE'];rows=[]
 for k in kinds:
  c=k.startswith('CANCEL_');rows.append({'scenario_kind':k,'project_state_after':'cancelled' if c else 'ready','work_start_request_count':0 if k=='CANCEL_PRE_START' else 1,'distinct_execution_count':0 if k=='CANCEL_PRE_START' else 1,'billable_execution_count':0 if k=='CANCEL_PRE_START' else 1,'logical_identity_preserved':True,'runtime_artifact_sha256':e7['runtime']['artifact_sha256'],'authority_provenance_sha256':e7['capacity_authority']['provenance_sha256']})
 checks={'all_required_scenarios_present':True,'authority_identity_consistent':True,'runtime_artifact_consistent':True,'no_duplicate_execution_or_billing':True,'no_automatic_ambiguous_start_repost':True,'logical_identity_preserved':True,'cancel_claims_truthful':cancel,'bounded_long_track_streaming':True,'storage_preflight_observed':True,'non_cancel_degraded_fraction_within_policy':True};names=('execution_capacity_status','cost_headroom_status','throughput_headroom_status');cp=dict(zip(names,cap));cn={**cp,'authority_provenance_sha256':e7['capacity_authority']['provenance_sha256'],'measurement_sha256':H('measurement'),'unknown':any(x=='UNKNOWN' for x in cap),'insufficient':any(x=='INSUFFICIENT' for x in cap)}
 if state is None:state='LIVE_AUTHORITY_REJECTED' if cn['insufficient'] or not all(checks.values()) else 'PENDING_EXTERNAL_EVIDENCE' if cn['unknown'] else 'READY_FOR_HQ_E08_LIVE_REVIEW'
 d={'schema_version':1,'tool_version':'L1-E08-v1','evidence_kind':'RUNTIME_AUTHORITY_LIVE_GATE','evidence_state':g.EVIDENCE_STATE,'gate_state':state,'parity_claim':'NONE','gate_id':'g','route_id':'r','route_kind':e7['route_kind'],'authority':{'kind':e7['capacity_authority']['kind'],'provenance_sha256':e7['capacity_authority']['provenance_sha256']},'runtime_artifact_sha256':e7['runtime']['artifact_sha256'],'source_evidence':{'e07_evidence_sha256':s7,'e07_substitution_lock_sha256':e7['e07_substitution_lock_sha256']},'summary':{'scenario_count':10,'non_cancel_degraded_fraction':0.0,'capacity':cp},'checks':checks,'scenarios':rows,'capacity_evidence':{'measurement_sha256':H('measurement'),'authority_provenance_sha256':e7['capacity_authority']['provenance_sha256']},'privacy':{},'parity_reason':'none'};payload={'domain':'l1-e08-runtime-authority-live-gate-v1','gate_id':'g','route_id':'r','route_kind':e7['route_kind'],'authority_kind':e7['capacity_authority']['kind'],'e07_source_sha256':s7,'e07_substitution_lock_sha256':e7['e07_substitution_lock_sha256'],'runtime_artifact_sha256':e7['runtime']['artifact_sha256'],'authority_provenance_sha256':e7['capacity_authority']['provenance_sha256'],'rows':rows,'capacity':cn,'checks':checks,'gate_state':state};d['e08_live_authority_lock_sha256']=C(payload);return d

def legacy(policy,lat=25000,cost=.4,delta=.2):
 q={'required_mode_classes':policy['required_mode_classes'],'allowed_service_regions':policy['allowed_service_regions'],'allowed_data_regions':policy['allowed_data_regions'],'maximum_mean_provider_total_ms':policy['maximum_mean_execution_total_ms'],'maximum_final_failure_fraction':policy['maximum_final_failure_fraction'],'maximum_retry_fraction':policy['maximum_retry_fraction'],'cost_currency':policy['cost_currency'],'maximum_mean_cost_per_successful_run':policy['maximum_mean_cost_per_successful_run'],'maximum_non_cancel_degraded_fraction':policy['maximum_non_cancel_degraded_fraction'],'maximum_uploaded_asset_retention_seconds':policy['maximum_uploaded_asset_retention_seconds'],'require_delete_api':policy['require_deletion_control'],'require_capacity_attestation':policy['require_capacity_attestation'],'minimum_overall_usability_delta':policy['minimum_overall_usability_delta'],'minimum_primary_score_margin':policy['minimum_primary_score_margin'],'ranking_weights':policy['ranking_weights'],'engineering_policy_not_reference_fact':True};src={k:H(k) for k in ('e01','e03','e04','e05','capacity')};row={'route_id':'hosted','decision':'ACCEPT_PRIMARY','eligible':True,'reasons':['old primary'],'metrics':{'mode_classes':['FREE_CORE','MAJOR'],'mean_provider_total_ms':lat,'mean_cost_per_successful_run':cost,'cost_currency':'USD','overall_usability_delta_project_minus_reference':delta,'non_cancel_degraded_fraction':0.0},'source_sha256':src,'source_locks':{},'score':.5};d={'schema_version':1,'tool_version':'L1-E06-v1','evidence_kind':'PROVIDER_ROUTE_DECISION','evidence_state':g.EVIDENCE_STATE,'decision_state':'PRIMARY_SELECTED','parity_claim':'NONE','decision_id':'old','policy':q,'routes':[row]};i=C({'domain':'l1-e06-provider-route-decision-v1','decision_id':'old','policy':q,'evidence_binding':{'hosted':src},'route_outcomes':{'hosted':'ACCEPT_PRIMARY'}});d['decision_identity_sha256']=i;d['decision_lock_sha256']=C({'identity':i,'routes':[row],'policy':q});return d

class T(unittest.TestCase):
 def setUp(self):
  self.t=tempfile.TemporaryDirectory();b=Path(self.t.name);self.repo=b/'repo';self.priv=b/'private';self.repo.mkdir();self.priv.mkdir();self.p=plan();self.n=g.normalized_policy(self.p)['policy']
 def tearDown(self):self.t.cleanup()
 def generic(self,kind='LICENSED_LOCAL_INFERENCE_SDK',cap=('ADEQUATE','ADEQUATE','ADEQUATE'),**mut):
  a=e07(kind);p7=self.priv/'e7.json';p7.write_text(json.dumps(a,sort_keys=True));s7=g.sha256_file(p7);b=e08(a,s7,cap,mut.pop('cancel',True),mut.pop('state',None));p8=self.priv/'e8.json';p8.write_text(json.dumps(b,sort_keys=True));s8=g.sha256_file(p8)
  op={'commercial_use_allowed':True,'input_confidential':True,'output_commercial_use_allowed':True,'output_export_allowed':True,'training_on_user_content_allowed':False,'service_region':'LOCAL_DEVICE','data_region':'LOCAL_DEVICE','uploaded_asset_retention_seconds':0,'deletion_control_available':True,'commercial_basis_sha256':a['commercial_basis_sha256']};bm={'mode_classes':['FREE_CORE','MAJOR'],'g1_objective_run_count':2,'g1_objective_floor_pass':True,'final_failure_fraction':0.0,'retry_fraction':0.0,'mean_execution_total_ms':30000.0,'mean_cost_per_successful_run':.5,'cost_currency':'USD','successful_run_count':4};df={'exact_input_bytes':True,'overall_usability_delta_project_minus_reference':.1,'material_inferiority_detected':False,'overall_usability_threshold_pass':True,'material_inferiority_vote_pass':True}
  for k,v in mut.items():
   if k.startswith('op_'):op[k[3:]]=v
   elif k.startswith('bm_'):bm[k[3:]]=v
   elif k.startswith('df_'):df[k[3:]]=v
  prov={}; kinds={'operational':'GENERIC_ROUTE_OPERATIONAL_MEASUREMENT','benchmark':'GENERIC_ROUTE_BENCHMARK_MEASUREMENT','differential':'GENERIC_ROUTE_DIFFERENTIAL_MEASUREMENT'}
  for name,m in [('operational',op),('benchmark',bm),('differential',df)]:
   d={'schema_version':1,'evidence_kind':kinds[name],'evidence_state':g.EVIDENCE_STATE,'parity_claim':'NONE','route_id':'r','route_kind':kind,'runtime_artifact_sha256':a['runtime']['artifact_sha256'],'measurement':m};p=self.priv/(name+'.json');p.write_text(json.dumps(d,sort_keys=True));prov[name]={'path':p.name,'sha256':g.sha256_file(p)}
  ev={'schema_version':1,'evidence_kind':'GENERIC_ROUTE_LIVE_EVALUATION','evidence_state':g.EVIDENCE_STATE,'parity_claim':'NONE','evaluation_state':mut.get('evaluation_state','READY_FOR_HQ_E09_ROUTE_EVALUATION'),'route_id':'r','route_kind':kind,'runtime':a['runtime'],'source_evidence':{'e07_evidence_sha256':s7,'e07_substitution_lock_sha256':a['e07_substitution_lock_sha256'],'e08_evidence_sha256':s8,'e08_live_authority_lock_sha256':b['e08_live_authority_lock_sha256']},'operational':op,'benchmark':bm,'differential':df,'provenance':prov,'privacy':{k:False for k in ('credential_values_emitted','authority_ids_emitted','private_paths_emitted','raw_billing_records_emitted','raw_reviewer_ids_emitted','raw_audio_emitted')}};pe=self.priv/'ev.json';pe.write_text(json.dumps(ev,sort_keys=True));return {'r':{'evidence_path_kind':g.PATH_GENERIC,'docs':{'e07':a,'e08':b,'evaluation':ev},'hashes':{'e07':s7,'e08':s8,'evaluation':g.sha256_file(pe)}}},(a,b,ev)
 def runr(self,inp):return g.decide_routes(plan=self.p,route_inputs=inp,repo_root=self.repo,private_root=self.priv)
 def test_matrix(self):
  checks=0
  def eq(a,b):
   nonlocal checks;self.assertEqual(a,b);checks+=1
  def raises(fn):
   nonlocal checks
   with self.assertRaises(g.RouteDecisionError):fn()
   checks+=1
  inp,_=self.generic();r=self.runr(inp);eq(r['decision_state'],'PRIMARY_SELECTED');eq(r['routes'][0]['decision'],'ACCEPT_PRIMARY');eq(r['parity_claim'],'NONE');eq(all(v is False for v in r['privacy'].values()),True)
  inp,_=self.generic('PROJECT_OWNED_MODEL_IF_RIGHTS_CLEARED_TRAINING_DATA_AVAILABLE');eq(self.runr(inp)['decision_state'],'PRIMARY_SELECTED')
  for cap,expect in [(('UNKNOWN','ADEQUATE','ADEQUATE'),'PENDING_EXTERNAL_EVIDENCE'),(('INSUFFICIENT','ADEQUATE','ADEQUATE'),'REJECT_CAPABILITY'),(('ADEQUATE','INSUFFICIENT','ADEQUATE'),'REJECT_COST'),(('ADEQUATE','ADEQUATE','INSUFFICIENT'),'REJECT_RELIABILITY')]:
   inp,_=self.generic(cap=cap);rr=self.runr(inp);eq(rr['decision_state'] if expect=='PENDING_EXTERNAL_EVIDENCE' else rr['routes'][0]['decision'],expect)
  cases=[('op_input_confidential',False,'REJECT_PRIVACY'),('op_deletion_control_available',False,'REJECT_PRIVACY'),('op_data_region','BAD','REJECT_PRIVACY'),('bm_mode_classes',['FREE_CORE'],'REJECT_CAPABILITY'),('bm_g1_objective_floor_pass',False,'REJECT_QUALITY'),('df_exact_input_bytes',False,'REJECT_QUALITY'),('df_material_inferiority_detected',True,'REJECT_QUALITY'),('bm_mean_execution_total_ms',130000.0,'REJECT_LATENCY'),('bm_mean_cost_per_successful_run',3.0,'REJECT_COST'),('bm_final_failure_fraction',.2,'REJECT_RELIABILITY')]
  for key,val,expect in cases:
   inp,_=self.generic(**{key:val});eq(self.runr(inp)['routes'][0]['decision'],expect)
  inp,parts=self.generic(); inp['r']['docs']['e07']['runtime']['model_version']='2';raises(lambda:self.runr(inp))
  inp,_=self.generic(cap=('UNKNOWN','ADEQUATE','ADEQUATE'),state='READY_FOR_HQ_E08_LIVE_REVIEW');raises(lambda:self.runr(inp))
  inp,parts=self.generic();inp['r']['docs']['evaluation']['runtime']['artifact_sha256']=H('bad');raises(lambda:self.runr(inp))
  inp,parts=self.generic();p=self.priv/'benchmark.json';d=json.loads(p.read_text());d['measurement']['mean_execution_total_ms']=99999.0;p.write_text(json.dumps(d,sort_keys=True));parts[2]['provenance']['benchmark']['sha256']=g.sha256_file(p);pe=self.priv/'ev.json';pe.write_text(json.dumps(parts[2],sort_keys=True));inp['r']['docs']['evaluation']=parts[2];inp['r']['hashes']['evaluation']=g.sha256_file(pe);raises(lambda:self.runr(inp))
  le=legacy(self.n);inpL={'hosted':{'evidence_path_kind':g.PATH_LEGACY,'docs':{'e06':le},'hashes':{'e06':C(le)}}};eq(self.runr(inpL)['decision_state'],'PRIMARY_SELECTED')
  bad=copy.deepcopy(le);bad['routes'][0]['metrics']['mean_provider_total_ms']=1;raises(lambda:self.runr({'hosted':{'evidence_path_kind':g.PATH_LEGACY,'docs':{'e06':bad},'hashes':{'e06':C(le)}}}))
  bad=copy.deepcopy(le);bad['policy']['maximum_mean_provider_total_ms']=999;raises(lambda:self.runr({'hosted':{'evidence_path_kind':g.PATH_LEGACY,'docs':{'e06':bad},'hashes':{'e06':C(bad)}}}))
  ginp,_=self.generic(cap=('UNKNOWN','ADEQUATE','ADEQUATE'));ginp.update(inpL);rr=self.runr(ginp);eq(rr['decision_state'],'PENDING_EXTERNAL_EVIDENCE');eq(any(x['decision']=='ACCEPT_PRIMARY' for x in rr['routes']),False)
  ginp,_=self.generic();slow=legacy(self.n,100000,1.8,-.1);ginp['hosted']={'evidence_path_kind':g.PATH_LEGACY,'docs':{'e06':slow},'hashes':{'e06':C(slow)}};rr=self.runr(ginp);eq([x['route_id'] for x in rr['routes'] if x['decision']=='ACCEPT_PRIMARY'],['r'])
  ginp,_=self.generic();a=self.runr(ginp)['e09_route_decision_lock_sha256'];ginp['r']['hashes']['evaluation']=H('other');b=self.runr(ginp)['e09_route_decision_lock_sha256'];eq(a==b,False);eq(set(self.runr(self.generic()[0])['supported_evidence_paths']),{g.PATH_LEGACY,g.PATH_GENERIC})
  ginp,_=self.generic();raises(lambda:g.decide_routes(plan=self.p,route_inputs=ginp,repo_root=self.repo,private_root=self.repo/'private'))
  self.assertEqual(checks,32)
if __name__=='__main__':unittest.main()
